### PR TITLE
Add runtime callback for memory growth

### PR DESCRIPTION
**Pull request by croes**
This pull request adds a runtime callback, similar to preRun, atMain,... for memory growth. Users can register callbacks for memory growth events with Module.addOnMemoryGrowth(callback).

### CODE REVIEW

**Comment by kripken** [comment]
I think it would be more consistent to have a Module callback, i.e. call `Module['onMemoryGrowth']` if that exists.

**Comment by juj** [comment]
Hmm, I think I'm slightly against this sort of thing. I don't think we should expose this to all code, and especially when memory growth is not enabled. What is the intent of adding this? For debug tracing? In that case, we should guard this so that it's clearly a debug only feature, and only enable it with relevant build flags, so that the code size of all user code won't increase with potentially unused features.

**Comment by kripken** [comment]
Are you objecting to the pull request in its current form, or to my suggestion that it consist of literally one line (if Module dot callback exists, call it)?

**Comment by croes** [comment]
We keep some TypedArray views on the Emscripten heap. Our intent is to invalidate these views when a memory growth occurs, so it's not just a debug feature.

**Comment by juj** [comment]
@croes: Hmm, I'm not quite sure about the spec here. My understanding with https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer/transfer was that existing views should be good? But now I'm starting to doubt that. What happens to the existing views to the old ArrayBuffer after .transfer() occurs? @kripken: do you know? The MDN site doesn't document that clearly. What if one is shrinking an ArrayBuffer via .transfer(), and had an existing view that then points outside the new range of the ArrayBuffer?

**Comment by juj** [comment]
My objection was that I'm thinking that the whole ArrayBuffer resizing should be handled automatically and under the hood, but with my last comment, I'm starting to doubt that myself. If user JS code indeed needs to be aware of the resize when it occurs, e.g. if existing views go stale by pointing to old data or similar, then we need some kind of hook (this makes me very sad). If we are doing hooks, then we need to have a structure that supports multiple registered hook functions, and not just only one.

Btw, in the Emscripten VFS, we do have a similar situation where the packaged files have views that can point inside the heap. I wonder if we have an issue there?

**Comment by kripken** [comment]
Note that we only use transfer when present, which is partial.

Yes, it does sound like we might have a VFS issue with existing views. In that case I'm surprised we've never gotten a bug report about it...

**Comment by kripken** [comment]
This PR is quite old, closing. Feel free to reopen if still relevant.

**Pull request closed without merging**
