### PR TITLE
OpenAL exception fix

### PR DESCRIPTION
**Pull request by gabrielcuvillier**
Under some circumstances the audioBuf field might be null, and this leads to a JS exception being thrown.

This happens probably due to caller doing invalid things using OpenAL API (the code I have is quite big, so I can't really say), but in all cases, this should not make the application crash. Maybe we should issue a warning ?

Seems to be a similar issue than #3170

### CODE REVIEW

**Comment by kripken** [comment]
I see, thanks. Ok, agreed this makes sense to do. Please just add yourself to AUTHORS before we merge.

**Comment by gabrielcuvillier** [comment]
I'm not sure this is related to @requires_sound_hardware because the test that fails looks like to be the simple test_hello_world. This is a little bit strange. The test is working on my environment (using "incoming" branch).

Where I am supposed to put the shell file for the test to use ? Do I have to create a new file "test_hello_world_shell.html" in the test folder root ? Sorry for the questions, I am new contributor.

**Comment by gabrielcuvillier** [comment]
In fact, on both pull requests I did recently, the test seems to fail before the test is being run, while building the prerequisite environment

There is the following issues:
shared:ERROR: Emscripten, llvm and clang build versions do not match, this is dangerous (1.38.20, 1.38.21, 1.38.21)
shared:ERROR: Make sure to rebuild llvm and clang after updating repos
>....>
Fatal: Module::getFunction: $runPostSets does not exist

Any advice?

**Comment by kripken** [comment]
I think the runPostSets issue is because of a recent change - you need to merge in very latest incoming to here.

**Comment by gabrielcuvillier** [comment]
This one is good finally

**Comment by kripken** [comment]
Great, thanks @gabrielcuvillier!

**Pull request merged**
