### PR TITLE
Wasm-only mode is not a requirement for async compilation

### LINKED ISSUE #5567: EMULATE_FUNCTION_POINTER_CASTS with WebAssembly should not disable async compilation
I was recently trying to asynchronously load my compiled WebAssembly. I used ``Module.instantiateWasm``, but kept running into issues such as "real__malloc is not callable".

After much hunting around in the emscripten source code I found that, for asynchronous loading of WebAssembly to work, you need to compile with "-s BINARYEN_ASYNC_COMPILATION=1" or "-s SWAPPABLE_ASM_MODULE=1".

I suggest updating the documentation for ``Module.instantiateWasm`` to mention these compilation flags, to avoid others having to go through the same pain.

Documentation URL: https://kripken.github.io/emscripten-site/docs/api_reference/module.html#Module.instantiateWasm

### PR DESCRIPTION
**Pull request by kripken**
Fixes #5567.

To be conservative, we disabled async compilation any time that asm2wasm was not emitting wasm-only code. That meant that if we had a fallback to asm.js, or used an asm.js feature like the emterpreter, async compilation was disabled. Things like `EMULATE_FUNCTION_POINTER_CASTS` also disable wasm-only mode for now (but perhaps shouldn't). However, this wasn't an actual hard limitation - turns out that just some tests needed to be updated. (Where we do need to disable async compilation is in things like using the binaryen interpreter to run the wasm, as there we do need to synchronously load the wasm, at least in how the current interpreter integration works - low priority, anyhow.)

### CODE REVIEW

**Comment by embeddedt** [comment]
I am still seeing this warning when I pass `EMULATE_FUNCTION_POINTER_CASTS` to Emscripten sdk-1.38.6-64bit, which appears to be the latest version.

**Comment by kripken** [comment]
@embeddedt it should be 1.38.21 - you may need to do `emsdk update` or `update-tags`

**Comment by embeddedt** [comment]
@kripken It told me to use `git pull` and then there were no updates available. Should I just get a fresh copy?

**Comment by kripken** [comment]
Try `update-tags`, that manually updates them. for `git pull` to work I think we need to update the repo, which I'm not sure of the status of, but probably will be sorted out this week.

**Comment by embeddedt** [comment]
@kripken Thanks. Now it found the latest version.

**Pull request merged**
