### PR TITLE
Add a test for SDL2 custom cursors

### PR DESCRIPTION
**Pull request by Daft-Freak**

### CODE REVIEW

**Comment by kripken** [comment]
I think this also needs to update the sdl2 ports tag?

**Comment by Daft-Freak** [comment]
Yep, added as first commit.

**Comment by kripken** [comment]
Did you add a tag in the SDL2 repo? I get
````
test_sdl2_custom_cursor (test_browser.browser) ... WARNING:root:retrieving port: sdl2 from https://github.com/emscripten-ports/SDL2/archive/version_13.zip
Traceback (most recent call last):
[..]
urllib2.HTTPError: HTTP Error 404: Not Found
FAIL
````

**Comment by Daft-Freak** [comment]
Oops, looks like I typo'd `version-13` instead of `version_13`. Should be fixed now.

**Comment by kripken** [comment]
Works now, thanks!

**Pull request merged**
