### PR TITLE
Eager tempfile deletion without atexit part2

### PR DESCRIPTION
**Pull request by juj**
Fixes Windows-specific failure on test other.test_eval_ctors and failures affecting all OSes on test other.test_function_eliminator_double_parsed_correctly.

### CODE REVIEW

**Comment by kripken** [comment]
In the `-w` diff,

````
          cld = shared.Building.closure_compiler(cld, pretty='minifyWhitespace' not in passes)
-        temp_files.note(cld)
+          temp_files_to_delete += [cld]
         elif cleanup:
````

Can't we keep using `.note()` as before, and then call `temp_files.clean()` at the end, instead of manually cleaning them up? I.e., the TempFiles class can do what you need.

**Comment by juj** [comment]
Hmm, I think not because `temp_files.clean()` will clean all so far noted created temp files up, which might contain other earlier `.note()`d files by some other part of the toolchain, that might still be used later for something else?

**Comment by kripken** [comment]
You can create another instance of TempFiles, then.

And perhaps even use it with `with`?

**Comment by juj** [comment]
Actually, scrap that, I realize that the stuff in js_optimizer.py was not the root cause for the failure in that test, that was misdebugged. The issue is actually directly in the test, which copies the result when it should have moved it. How does this look to you now?

**Comment by kripken** [comment]
lgtm

**Pull request merged**
