### PR TITLE
Fix precision lost when using 'constant' with Embind.

### PR DESCRIPTION
**Pull request by Becavalier**
It seems like when using "constant" with Embind, the negative value and float value will lost their precision when retrieving them from the JavaScript side.

@kripken

### CODE REVIEW

**Comment by Becavalier** [comment]
Maybe need @chadaustin 's help to review. : )

**Comment by jlee-imvu** [comment]
FWIW, this is basically the change I recommended in the comments for https://github.com/kripken/emscripten/pull/6397 , so... looks good to me. :)  Might be nice if you are able to add something like the test case portion of froydnj's commit, as well as perhaps a test case for negative constants.

If this PR goes in, it should presumably be fine to close PR 6397, as well as associated issue #5565.

**Comment by chadaustin** [comment]
If @jlee-imvu supports the change, so do I. :)

Add a test case or two and I can click the merge button.

**Comment by Becavalier** [comment]
Yes, here I have updated the test cases, and I directly using the same case for float number as #6397
@chadaustin

**Comment by chadaustin** [comment]
Thank you!

**Pull request merged**
