### PR TITLE
New feature added:  enable caching wasm module by IndexedDB.

### PR DESCRIPTION
**Pull request by Becavalier**
@kripken 

Hi, this is a PR for adding a new feature which developers can use to automatically caching entire WebAssembly.Module instance into the IndexedDB. although the "WebAssembly structured cloning support " is not enabled by default in Chrome, I think we can make some introductions in our website to note this point.

### CODE REVIEW

**Comment by kripken** [comment]
Thanks! However, there is some unlucky timing here, as browsers have just made a decision to stop supporting IndexedDB wasm caching. I learned about this yesterday here:

https://bugs.chromium.org/p/chromium/issues/detail?id=719007#c20

And I just confirmed that it is a consensus among all browsers to do so.

I hear that there are plans to support wasm caching in a different way that should be easier and work better, so we just need to wait for that it seems.

**Comment by Becavalier** [comment]
@kripken  OMG, the standard changes so fast. I get it, I'll keep on tracking this issue.

**Comment by gabrielcuvillier** [comment]
Hello, anyone have an idea about the plans for wasm caching since deprecation of IndexedDB usage for this purpose ?

**Comment by kripken** [comment]
The bug for automatic caching in chrome is here: https://bugs.chromium.org/p/chromium/issues/detail?id=719172 (see details in last comment for rollout status)

**Pull request closed without merging**
