### PR TITLE
Set EMCC_EXPERIMENTAL_USE_LLD by default

### PR DESCRIPTION
**Pull request by sbc100**
Hopefully this option can be remove completely in the near
future alone with the s2wasm tool.

### CODE REVIEW

**Comment by Becavalier** [comment]
So, with this LLVM backend for WebAssembly, do we still need "Binaryen" to optimize the final binary module for us?

**Comment by kripken** [comment]
@Becavalier Yes, and emscripten does run the binaryen optimizer after the LLVM backend - it shrinks the code by around 15% or so. (But we don't need the binaryen s2wasm tool to do linking for us any more).

**Comment by jgravelle-google** [comment]
We also need the `wasm-emscripten-finalize` tool to do emscripten-specific things to it. It adds some runtime functions, and enables compiler-magic features like EM_ASM/EM_JS

**Pull request merged**
