### PR TITLE
Fix glfw character callback typing keyboard shortcuts. Closes GH-5121

### PR DESCRIPTION
**Pull request by satoshinm**
Fixes text input appearing in `glfwSetCharCallback()` when pressing keyboard shortcuts.

Adds a check to not call the callback if ctrlKey (control) or metaKey (super/command) is set (*), matching the native glfw behavior and documentation at http://www.glfw.org/docs/latest/input.html#input_char which says this callback is for "text input" (note, not checking shiftKey and altKey since those can be used to type alternative characters).

Fixes https://github.com/kripken/emscripten/issues/5121 and the example there. Tested on Firefox 55.0a1 (2017-04-22), this change fixes Cmd-A and Ctrl-A both typing "a", as well as  Safari Technology Preview 28, fixes Cmd-A typing "a".

### CODE REVIEW

**Comment by satoshinm** [comment]
Note this issue may also apply to SDL, haven't looked into it (src/library_sdl.js `event.type === 'keypress'`?)

**Comment by kripken** [comment]
Thanks, this makes sense to me. If that callback is just for text input, then it does seem like it should ignore those things. (I'm not sure about SDL here.)

Just need a test for this.

**Comment by satoshinm** [comment]
Added a test, haven't added tests to emscripten before hopefully I did it right. Based it on [my original example app](https://github.com/satoshinm/emglfwbugs/blob/gh-pages/test_glfw_char_callback/test_glfw_char_callback.c) but cleaned up and added to tests/test_interactive.py, running with `python tests/runner.py interactive.test_glfw_char_callback` works. Note the test user has to manually type keys and inspect the output to validate the result.

**Comment by kripken** [comment]
Looks like a good start for the test. Let's move it from `interactive` to `browser`, though, so it's automatic. There are existing tests there with keyboard input, look for tests with `key` in the name (might even be a glfw one, in which case, maybe can add to it?)

**Comment by satoshinm** [comment]
Added tests to test/glfw_events, fits into that test well (run with `python tests/runner.py browser.test_glfw_events`).

However, even without my changes, this test was failing for me. Emscripten 1.37.9 and `incoming`, fails on Chrome 57.0.2987.133 and Safari TP 28, only passed on Firefox 53.0 and 55.0a1.

The problem seems to be not with emscripten itself but the synthetic keyboard event injection, using the deprecated [initKeyboardEvent](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/initKeyboardEvent); they recommend using [`new KeyboardEvent()`](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/KeyboardEvent) which works on Firefox and Safari (all of glfw_events passes) but Chrome is still broken: result code 0b1101101010101010101010111111, so all of the `keydown` tests are failing. Testing this snippet:

```js
window.onkeydown=(event)=>{console.log('keydown',event.keyCode)};
dispatchEvent(new KeyboardEvent('keydown',{keyCode:65}));
```

Firefox and Safari log "keydown 65", but Chrome logs "keydown 0" (??). No idea what is going on here, but real key events work fine, only the test is broken on Chrome, and the breakage was not a consequence of this change.

**Comment by satoshinm** [comment]
Zero keyCode from synthetic events is a long-standing bug in Chrome: http://stackoverflow.com/questions/10455626/keydown-simulation-in-chrome-fires-normally-but-not-the-correct-key

Workaround is to use generic events. After this fix, all glfw_events tests pass on all three browsers.

**Pull request merged**
