### PR TITLE
Remove jsevents object

### LINKED ISSUE #2999: Moving emscripten_webgl_* out of library_html5.js?
I'm looking at using some of the `emscripten_webgl_*` calls in IMVU code ... but it imposes a pretty large size hit due to the `JSEvents` stuff.

All of the functions apart from `emscripten_set_webglcontextlost_callback` and `emscripten_set_webglcontextrestored_callback` could readily be moved to a separate `library_webgl.js`, except for the usage of `JSEvents.findEventTarget` in `emscripten_webgl_create_context` ... which could be duplicated or moved to some where else?

### PR DESCRIPTION
**Pull request by juj**
This pull request removes the `JSEvents` object altogether in `src/library_html5.js` and replaces it with the use of explict `x__deps` dependency handling. This allows dead code elimination to remove a lot of unused functions when using the HTML5 events API. Also the functions are now prefixed with double underscores to clearly separate public and private APIs. This fixes #2999.

### CODE REVIEW

**Comment by juj** [comment]
The intent of this is also to prepare for fixing issue #3283 by changing the built-in default shell.html to reuse the HTML5 functions so that the fullscreen button and the HTML5 API fullscreen request code will play nice together. However I'm not sure yet how to model a dependency between default `shell.html` to `_emscripten_request_fullscreen`. Would you have an idea for this @kripken ?

**Comment by kripken** [comment]
I think if an HTML shell file depends on something, it would need to add it as used by adding it to `DEFAULT_LIBRARY_FUNCS_TO_INCLUDE`.

**Comment by kripken** [comment]
This is a lot of refactoring that leads to what I worry is worse code - now there will be lots of small globals (`_currentEventHandler, _eventHandlers`, etc.) as well as functions. It's all flattened out in the global namespace, with no obvious structure, unlike now. Is this really worth it to allow dependency management to remove some of this code?

If we are sure that the code size benefits are worth it, how about if there is still a `$JSEvents`, but it starts out almost empty, and at runtime we add properties to it when needed? Not sure if that would work or not.

Another option is to rely on closure. Closure advanced can remove parts of objects, so it would do dead code elimination in the code before this pull.

Another option is to add dependency management in emscripten to properties of objects, but that sounds complex.

**Comment by kripken** [comment]
Is this still important, @juj?

**Comment by juj** [comment]
This is not only important, but critical; though this PR that implements this removal has fallen out of date, so I'll close this out. In my fork november_2018 I've reimplemented this, but don't have time just now to submit a PR.

**Pull request closed without merging**
