### PR TITLE
Code size improvements

### PR DESCRIPTION
**Pull request by kripken**
This is a bunch of code size improvements that either depend on each other, or are tricky and need careful thought.

 * Optimize shell.js a little for node.js, avoid `require` we likely won't need.
 * Use node.js `console.log|warn`. This *seems* to remove the need for our node.js stdout hack, which is nice, and also probably more optimal (we always do a newline for each print, just like `console`; and, it's the same code as on the web - maybe we can only do `console` everywhere eventually).
 * Use `console.warn` on the web. It looks different in devtools, seems a nice improvement.
 * Remove `NO_BROWSER`. This refactors so that it isn't always needed, and will be pulled in on demand. This shrinks our code size for hello world by a significant chunk.
 * I noticed some flakiness is due to browser timeouts, so I increased them, and things are much more stable for me now.

cc @juj

### CODE REVIEW

**Comment by kripken** [comment]
@juj, if you can test this that would be great. I don't think we saw the node.js printing issue everywhere, so I'm worried that tests passing for me here isn't enough.

**Comment by kripken** [comment]
Added 2 commits,

 * Avoid exporting UTF16 and UTF32 methods by default. Not sure why we even have them? They don't seem to be used anywhere that I can see.
 * Enable the JSDCE pass. This cleans up code that is not used nor exported. In particular it can clean up those UTF16 and UTF32 methods.

**Comment by kripken** [comment]
One more thing I wanted to do, in this area - we include IDBFS etc. by default. @juj, I think we had a plan to optimize that, didn't we? We could require `emscripten_init_idbfs()` to use IDBFS etc., and that static call would be used to bring it in. Did we just never get around to doing that, or was there a reason not to, do you remember?

It might be nice to go further and have `emscripten_init_fs()` (which would be the opposite of `NO_FILESYSTEM`), which would really make us slim by default. But, it also means a lot of code wouldn't work out of the box, so not sure that makes sense.

**Comment by kripken** [comment]
On more thought, the risky thing in this pull is enabling JSDCE. We should definitely document this change. The risk is that someone might currently assume they can use non-exported things in another script tag, and JSDCE cleans up within the emitted .js file, assuming only exported (on Module) stuff will be used outside. Just like closure, basically.

This only kicks in in -O2 and above, so at least people would notice it's something to do with optimizations. I think it might be ok to leave it, with documentation. @juj, what do you think?

**Comment by kripken** [comment]
I looked into the filesystem stuff. I *think* we can do this thanks to our static syscalls. If we never see an `open()` syscall, then there is very little you can do with files. And if you do just printf etc., you never open, you just write to. I added a commit that enables `NO_FILESYSTEM` based on that. This is really good for reducing our hello world code size! I just hope I'm not missing some catch...

Also added a commit to fix `closure 2` mode (our smallest code size) on filesystem access (or actually a lot of other stuff), which was apparently broken all along.

**Comment by kripken** [comment]
The change from this pull: hello world goes from 467,160 to 307,931 at -O0, and on -Oz from 160,459 to 64,074 (-O2 is similar).

**Comment by kripken** [comment]
I also would like to remove the JS demangler - which I think @juj, you were in favor of earlier? I measured and it accounts for 4% of the size of -Oz hello world (!). After removing it -Oz is 61,668. (It is still possible to use the libcxxabi demangler as an option of course).

**Comment by kripken** [comment]
We have a few tests that use no files in C/C++ but do use them in JS. I added a `FORCE_FILESYSTEM` option for this and documented it. I think in practice this would be extremely rare, so I'm not too worried about it, but let me know if anyone has concerns.

**Comment by juj** [comment]
Initially looks great. The reason we have UTF-16 and UTF-32 was to add support for interopping `std::wstring`s and `wchar_t*` strings between C++ and JS. This was needed by some regex project a way back - our internal runtime doesn't have a need for them.

I think we should be careful in introducing code changes for developers, `emscripten_init_fs()` sounds like that(?), so prefer keeping that out, or optional if we want to do it.

Running tests now..

**Comment by kripken** [comment]
Actually, `emscripten_init_fs()` is no longer needed as I found a way in the commits here to do it automatically. As mentioned above, the only risk is not using any files in C, but using them in JS. That would probably be a tiny set of users, more expert-level anyhow, so I think the risk is worth it (and it's documented, of course).

**Comment by kripken** [comment]
Updated pull request with 8816b43fb43d229029ba74c2a643837cf27c8fd2 (in the middle so as not to break bisection), which makes pthreads code work with this (it was assuming FS was always there).

**Comment by juj** [comment]
I am seeing failures on `test_dlmalloc_partial_2` and `test_ccall` on Windows. How do those look on your system?

**Comment by kripken** [comment]
Strange, both of those pass (on all modes) over here. What's the mode (or is it default?) and what's the full error?

**Comment by juj** [comment]
The error on `test_ccall` looks like

	C:\code\emsdk\emscripten\incoming>python tests/runner.py test_ccall
	WARNING:root:use EM_ALL_ENGINES=1 in the env to run against all JS engines, which is slower but provides more coverage
	test_ccall (test_core.default) ... (checking sanity from test runner)
	INFO:root:(Emscripten: Running sanity checks)
	WARNING:root:function requested to be exported, but not implemented: "_main"
	(test did not pass in JS engine: ['C:/code/emsdk/node/4.1.1_64bit/bin/node'])
	ERROR

	======================================================================
	ERROR: test_ccall (test_core.default)
	----------------------------------------------------------------------
	Traceback (most recent call last):
	  File "C:\code\emsdk\emscripten\incoming\tests\test_core.py", line 6561, in test_ccall
	    self.do_run_from_file(src, output, post_build=post)
	  File "C:\code\emsdk\emscripten\incoming\tests\runner.py", line 554, in do_run_from_file
	    includes, force_c, build_ll_hook, extra_emscripten_args)
	  File "C:\code\emsdk\emscripten\incoming\tests\runner.py", line 588, in do_run
	    raise e
	Exception: Expected to find '*
	number,5
	number,3.14
	string,hello world
	12
	undefined
	14.56
	undefined
	cheez
	undefined
	arr-ay
	undefined
	more
	number,10
	650
	number,21
	*
	5
	atr
	10
	bret
	53
	*
	stack is ok.
	stack is ok.
	' in '*
	[ 'number', 5 ]
	[ 'number', '3.14' ]
	[ 'string', 'hello world' ]
	12
	undefined
	14.56
	undefined
	cheez
	undefined
	arr-ay
	undefined
	more
	[ 'number', 10 ]
	650
	[ 'number', 21 ]
	*
	5
	atr
	10
	bret
	53
	*
	stack is ok.
	stack is ok.
	', diff:

	--- expected
	+++ actual
	@@ -1,7 +1,7 @@
	 *
	-number,5
	-number,3.14
	-string,hello world
	+[ 'number', 5 ]
	+[ 'number', '3.14' ]
	+[ 'string', 'hello world' ]
	 12
	 undefined
	 14.56
	@@ -11,9 +11,9 @@
	 arr-ay
	 undefined
	 more
	-number,10
	+[ 'number', 10 ]
	 650
	-number,21
	+[ 'number', 21 ]
	 *
	 5
	 atr



	----------------------------------------------------------------------
	Ran 1 test in 1.969s

	FAILED (errors=1)

and the failure on `test_dlmalloc_partial_2` looks like

	C:\code\emsdk\emscripten\incoming>python tests/runner.py asm1.test_dlmalloc_partial_2
	WARNING:root:use EM_ALL_ENGINES=1 in the env to run against all JS engines, which is slower but provides more coverage
	test_dlmalloc_partial_2 (test_core.asm1) ... (checking sanity from test runner)
	INFO:root:(Emscripten: Running sanity checks)
	(test did not pass in JS engine: ['C:/code/emsdk/node/4.1.1_64bit/bin/node'])
	ERROR

	======================================================================
	ERROR: test_dlmalloc_partial_2 (test_core.asm1)
	----------------------------------------------------------------------
	Traceback (most recent call last):
	  File "C:\code\emsdk\emscripten\incoming\tests\test_core.py", line 5697, in test_dlmalloc_partial_2
	    self.do_run_from_file(src, output)
	  File "C:\code\emsdk\emscripten\incoming\tests\runner.py", line 554, in do_run_from_file
	    includes, force_c, build_ll_hook, extra_emscripten_args)
	  File "C:\code\emsdk\emscripten\incoming\tests\runner.py", line 588, in do_run
	    raise e
	Exception: Expected to NOT find 'ERROR' in 'got 0x7b
	freed a fake
	FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
	', diff:

	--- expected
	+++ actual
	@@ -1 +1,4 @@
	-ERROR
	+got 0x7b
	+freed a fake
	+FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
	+


	----------------------------------------------------------------------
	Ran 1 test in 12.935s

	FAILED (errors=1)

These look a bit odd. The node.js print mechanism changed, I wonder if it would be printing out some objects differently on different OSes?

**Comment by kripken** [comment]
The first might be a stdout/stderr change, maybe using console.log in node is not good on windows. Can you please bisect in this pull to see which commit breaks it?

And I guess the same for the second, bisection seems the best route, as it appears windows-only. But in that second error, I don't even have a guess.

**Comment by kripken** [comment]
Oh wait, I see what the first one is. It's that node's console.log does more "pretty" printing. But I wonder why only you see it... maybe different node version on windows?

**Comment by kripken** [comment]
Pushed a fix for `test_ccall` (again, in the right place).

**Comment by juj** [comment]
`test_ccall` fails due to

	755e84df9dc5a85f8f617d42c20b3c2dfa4acad2 is the first bad commit
	commit 755e84df9dc5a85f8f617d42c20b3c2dfa4acad2
	Author: Alon Zakai <alonzakai@gmail.com>
	Date:   Fri Feb 5 15:06:02 2016 -0800

	    use console.log|warn in node, avoiding process object printing, which lets us avoid NODE_STDOUT_FLUSH_WORKAROUND

	:040000 040000 4a6dfdcdf19e7e8807d2bbe24f11a19fc706de9b d65903d415adaf2690d6033d7015828699f4311a M  src
	:040000 040000 5123e517e3e88d9f68dd775538c851822dcf869c add630cc467444a3ccfa2bcd2988339c783b8329 M  tests

and `asm1.test_dlmalloc_partial_2 ` fails due to

	6727bab62ce45a9fe33ad5b659535fecd026d37b is the first bad commit
	commit 6727bab62ce45a9fe33ad5b659535fecd026d37b
	Author: Alon Zakai <alonzakai@gmail.com>
	Date:   Sat Feb 6 13:42:28 2016 -0800

	    automatically set NO_FILESYSTEM based on static syscall usage, and add a FORCE_FILESYSTEM option for the rare case where files are used only from JS

	:100755 100755 05e40cf5c098a28add589719ad4ad97644fe03a0 baea41d79cf96a77fe5ad545a228aa671bf21b98 M  emcc.py
	:100755 100755 902cc85d1ca5844ec75c4600781fb6a360748c38 8d38f9f6e989a5472237ca05fbb78ec8d5dc4296 M  emscripten.py
	:040000 040000 a66b4f6570372f8d1b7c7ccb9053f3809c6e8397 7202d3f553c156c7ec6ae31bcfd0897432ebd453 M  src
	:040000 040000 3f4005904dd495ad19abe09d79564e1f765ba66e 78b15a038754912728b3eb639d3de786e39d12e7 M  tests

**Comment by juj** [comment]
Which version of node.js are you running on? (or on SpiderMonkey?) Let me test if our currently shipped node.js 4.1.1 still has the bug that requires NODE_STDOUT_FLUSH_WORKAROUND, haven't checked that in a while.

**Comment by kripken** [comment]
0.10.25. However, in any case I'd like to use console.log, as it's the same API as in the other cases - hopefully we can consolidate them all and save a bunch of code here. And anyhow that test should be ok after the last push.

The other error, for `asm1.test_dlmalloc_partial_2`, is still very strange. Can you send me the zip of the temp dir?

**Comment by kripken** [comment]
I downloaded node 4.2.6 stable. I don't see a failure on that, but I *do* see a difference in output vs. spidermonkey. Investigating now, something is weird.

**Comment by kripken** [comment]
Ok, `test_dlmalloc_partial_2` is just a weird test. It replaces `malloc` with a dummy that returns `123`, and checks that it was in fact replaced. But the bad malloc messes up things like flushing of stdout, and this can lead to weird things like you saw. Fixed by just not exiting the runtime in that test.

**Comment by kripken** [comment]
Fixed a bug with preload plugins not working (they always need a filesystem, so I made that work).

**Comment by kripken** [comment]
@juj: the pthreads tests warn on `$FS` not being defined because they depend on `utime`, which needs FS. The reason is that in library_pthread.c, in the switch, we have `EM_PROXIED_UTIME`. I suppose the simplest thing is to just always enable FS when pthreads is on, I'll do that.

**Comment by kripken** [comment]
I added a few minor optimizations as well, that depend on the former stuff.

I'd like to land this soon if there are no objections as it's getting large and I worry about merge issues.

**Comment by juj** [comment]
Finished running full core test suite on this, I think this is good to merge. Let's see if bots give any remaining issues, and clean them up there. lgtm.

**Comment by kripken** [comment]
Cool, thanks. I'm doing some final checks here, then I'll merge later today.

**Comment by kripken** [comment]
Oddly the bots complain about code size, suggesting the builds there are larger than I see locally. This should be deterministic so I'm not sure what's wrong. I'll diff some builds between my machines tomorrow. Probably fine to just increase the test ranges, but I'd like to know why there is any discrepancy at all between the bots and me.

**Comment by kripken** [comment]
In case I don't see a difference on my other machines, @juj can you please build `./emcc tests/hello_world` and send me `a.out.js`, on either the osx or ubuntu bot? (both show the error)

**Comment by kripken** [comment]
JSDCE broke `other.test_emcc_wasm_0`, only noticeable when rebuilding the cache though so I missed it before. In any case, unless there is an objection I'll remove the `WASM` option - it's an early experiment towards wasm, not something worth using at this point, so not sure it's worth maintaining the test.

(Binaryen has proper support for the wip actual wasm format and eventually we'll integrate that.)

**Comment by kripken** [comment]
Code size issue looks like differences between LLVM outputs, perhaps the difference between assertions builds vs non.

**Comment by kripken** [comment]
I addressed both of those last issues on incoming.

**Comment by kripken** [comment]
Found a few more issues in browser tests, fixed. I also thought of a nice way to add a clear runtime error on usage of FS without it being included, in ASSERTIONS builds, added that too.

**Pull request merged**
