### PR TITLE
Reuse uncaughtException handler on Node.js to avoid memory leak.

### PR DESCRIPTION
**Pull request by loic**

### CODE REVIEW

**Comment by loic** [comment]
When reusing modules multiple time as in https://github.com/kripken/emscripten/issues/3167 we eventually hit the "Warning: Possible EventEmitter memory leak detected. 11 wakeup listeners added. Use emitter.setMaxListeners() to increase limit" warning because the `uncaughtException` handler is redefined every time.

**Comment by loic** [comment]
Closing for now, as it doesn't seem to work, Node.js must do something funky inside `process.on()` and behaves differently than regular `addEventListener()`.

**Comment by loic** [comment]
Instead of relying on https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener#Multiple_identical_event_listeners which doesn't seem to work, I moved the call to `process.on()` inside the `if`.

**Comment by nazar-pc** [comment]
Could you add a test case for this? Because it is not clear under which circumstances it happens.

**Comment by kripken** [comment]
This PR is quite old, closing. Feel free to reopen if still relevant.

**Pull request closed without merging**
