### PR TITLE
Changes for UTF-8 EM_ASM and EM_JS JS CODE.

### PR DESCRIPTION
**Pull request by Sevenops**
`EM_JS(void,testCode,(),{ console.log("ççüğişiş."); });`
This simple code doesn't work without this patch.
#7323

### CODE REVIEW

**Comment by kripken** [comment]
The tests here show errors with `TypeError: write() argument must be str, not bytes` - I think the `asstr` helper function might be useful here.

**Comment by Sevenops** [comment]
how about now ?

**Comment by kripken** [comment]
Thanks @Sevenops, looks good! Please just add yourself to AUTHORS before we merge.

**Comment by Sevenops** [comment]
done!

**Comment by kripken** [comment]
Great, thanks!

**Pull request merged**
