### PR TITLE
Openal relative audio fixes

### PR DESCRIPTION
**Pull request by TannerRogalsky**
2 minor changes: 
- Fix function name typo in the openal debug info (`alListenerfv` -> `alListener3f`)
- Make the cached copy of global audio listener's orientation match the actual default (as per [this document](https://developer.mozilla.org/en-US/docs/Web/API/AudioListener/setOrientation))

1 major:
- The logic for if a source was relative was reversed. A test has been added for this.

Tests `interactive.test_openal_playback` and `interactive.test_openal_buffers` were run without regressions.

### CODE REVIEW

**Comment by TannerRogalsky** [comment]
@juj Sorry to ping you but would you mind commenting on this? Should I add more tests?

**Comment by kripken** [comment]
Hmm, he went on vacation just today, for 2 weeks... Would it be ok to wait? Or if you'd prefer, I could try to review this, but it's not my area of expertise.

**Comment by TannerRogalsky** [comment]
Waiting is fine. Thanks, @kripken.

**Comment by juj** [comment]
Hey, thanks for the patience on this.

I'm not sure if flipping the relative source is (any more) correct here. We could define the following usage patterns for an audio source:

1. the audio source is mono or stereo 2D and does not have 3D position and shouldn't get any positional audio computation, i.e. just play back as it is.
2. the audio source is mono or stereo 2D and does not have 3D position, but one would like to do a simple 2D stereo panning to control whether to play out in left/right channel.
3. the audio source is mono positional 3D, and its position is specified in absolute coordinate space relative to a world origin. The volume in left/right channels is computed spatially in 3D.
4. the audio source is mono positional 3D, and its position is specified in unit relative to the listener position. The volume in left/right channels is computed spatially in 3D.

In Web Audio, in order to do achieve the above usage patterns, one would do:

1. Don't add any intermediate panning nodes, but play source back directly.
2. Add a [StereoPannerNode](https://developer.mozilla.org/fi/docs/Web/API/StereoPannerNode) to the audio source, and use that to control left/right bias.
3. Add a [PannerNode](https://developer.mozilla.org/en-US/docs/Web/API/PannerNode) to the audio source, and use that to specify the 3D world position of the source.
4. Proceed like in 3), but since Web Audio does not have support of specifying the positions of audio sources with respect to the listener but they are always absolute, it means that whenever one changes the listener position, one needs to iterate through all sound sources and update their position so that they remain in the same relative position to the listener.

In OpenAL, all sources are always 3D, and OpenAL does not really have a concept of 2D audio. In order to achieve the usage patterns 1-4, one would do:

1. If one never changes the listener position, one could just enforce the listener to world origin (0,0,0) (default), and set the audio to the same location as the listener, and set `alDistanceModel(AL_NONE)` so that there is no distance attenuation. But since the application could simultaneously have some 3D sounds so we need to assume that the listener position might change, then one should set the 2D audio sources to have `AL_SOURCE_RELATIVE=true` so that they stick along in the same location as the listener moves.
2. Place the audio source a distance of one unit away from the listener (in a half-circle) with `alDistanceModel(AL_NONE)` and `AL_SOURCE_RELATIVE=true`. Then the 180 degree half circle rotation around the listener will effectively perform the stereo panning.
3. Specify `AL_SOURCE_RELATIVE=false` and use `alSource3f` with `AL_POSITION` to specify the absolute location in world space.
4. Specify `AL_SOURCE_RELATIVE=true` and use `alSource3f` with `AL_POSITION` to specify the location relative to the listener.

So effectively whether we need to add a `PannerNode` to the sound source is independent of whether `AL_SOURCE_RELATIVE` is true or false. The reason that `library_openal.js` currently does it for case 3 only is that the implementation in OpenAL is not complete, and there is a simplifying assumption that if user is setting `AL_SOURCE_RELATIVE=false`, he is doing the case 3) above, and if he is setting `AL_SOURCE_RELATIVE=true`, he'd be doing 1).

Since OpenAL API does not really distinguish between 2D audio and 3D audio, but 2D audio is just cleverly positioned 3D audio, we can never really utilize the WebAudio StereoPannerNode for purpose 2), but that is not much of an issue.

In the current state for `library_openal.js`, use cases 1)-3) work properly, as long as they are not mixed in one application. Also, use case 2) needs to be done with `AL_SOURCE_RELATIVE=false`.

To implement correct behavior for 1)-4) and mixing them in a single application, I think the approach would be to implement support for `AL_SOURCE_RELATIVE=true` in `library_openal.js` via the following:
   - maintain a list of all audio sources which have `AL_SOURCE_RELATIVE=true`.
   - when `alSource3f` is called for an audio node that is in relative mode, convert the supplied position, velocity and orientation from relative to listener location to relative to world location, and apply those world locations to Web Audio.
   - when `alListener3f`/`alListenerfv` is called to change the position or orientation of the audio listener, go through the list of all sources that are in relative mode, and update their locations, velocities and orientations so that they stay in the same state relative to the updated listener position.

This might also need adding some support for `alDistanceModel` function, which currently only supports `AL_NONE`.

**Comment by juj** [comment]
Closing this on the basis of above comments and the upcoming PR #5367 will touch OpenAL code significantly, so this type of attempt will need to rebase on top of it.

**Comment by jpernst** [comment]
Just as a note, the new implementation PR should be fully compliant with the 1.1 spec with regards to source spatialization, and additionally supports the new `AL_SOFT_source_spatialize` extension to allow you to override it if you so desire. It includes some spatialization tests, so I'm reasonably sure it's correct, but it's entirely possible that there are still bugs, so please do let me know if you get a chance to try it out and the behavior seems to be incorrect.

**Pull request closed without merging**
