### PR TITLE
Add thorough type checking and fastpath modes for webidl_binder.py

### PR DESCRIPTION
**Pull request by BKcore**
__The goal of this PR is twofold: 1. Decrease the time spent in the wrapper to improve perf. 2. Give more thorough argument type errors in "debug" mode.___

- Setting `IDL_CHECKS=ALL` in your env will add thorough argument checking to the wrapper methods, catching NaNs, invalid pointers, invalid strings, etc. Note that we only special cased the most common argument types for simplicity; may extend later as needed.
- Setting `IDL_CHECKS=FAST` in your env will skip most type checking for performance (~3x faster than default on a vec3 setter).
- Setting `IDL_CHECKS` to anything else, or not setting it will behave as before, ensuring backward compatibility.
- Setting `IDL_VERBOSE=1` in your env will print debug info during render_function.
- Added inline type comments for readability: `argN <Type> [innerType]`.

`IDL_CHECKS=ALL`:
```js
// StringUser
function StringUser(arg0, arg1) {
  /* arg0 <String> [] */
  if(typeof arg0 !== 'undefined' && arg0 !== null) {
    assert(typeof arg0 === 'string' || (arg0 && typeof arg0 === 'object' && typeof arg0.ptr === 'number'), '[CHECK FAILED] StringUser::StringUser(arg0:str): Expecting <string>');
  }
  if (arg0 && typeof arg0 === 'object') arg0 = arg0.ptr;
  else arg0 = ensureString(arg0);
  /* arg1 <Long> [] */
  if(typeof arg1 !== 'undefined' && arg1 !== null) {
    assert(typeof arg1 === 'number' && !isNaN(arg1), '[CHECK FAILED] StringUser::StringUser(arg1:i): Expecting <integer>');
  }
  if (arg0 === undefined) { this.ptr = _emscripten_bind_StringUser_StringUser_0(); getCache(StringUser)[this.ptr] = this;return }
  if (arg1 === undefined) { this.ptr = _emscripten_bind_StringUser_StringUser_1(arg0); getCache(StringUser)[this.ptr] = this;return }
  this.ptr = _emscripten_bind_StringUser_StringUser_2(arg0, arg1);
  getCache(StringUser)[this.ptr] = this;
};
```

`IDL_CHECKS=FAST`:
```js
// StringUser
function StringUser(arg0, arg1) {
  /* arg0 <String> [] */
  if (arg0 && typeof arg0 === 'object') arg0 = arg0.ptr;
  else arg0 = ensureString(arg0);
  /* arg1 <Long> [] */
  if (arg0 === undefined) { this.ptr = _emscripten_bind_StringUser_StringUser_0(); getCache(StringUser)[this.ptr] = this;return }
  if (arg1 === undefined) { this.ptr = _emscripten_bind_StringUser_StringUser_1(arg0); getCache(StringUser)[this.ptr] = this;return }
  this.ptr = _emscripten_bind_StringUser_StringUser_2(arg0, arg1);
  getCache(StringUser)[this.ptr] = this;
};
```

legacy:
```js
// StringUser
function StringUser(arg0, arg1) {
  if (arg0 && typeof arg0 === 'object') arg0 = arg0.ptr;
  else arg0 = ensureString(arg0);
  if (arg1 && typeof arg1 === 'object') arg1 = arg1.ptr;
  else arg1 = ensureString(arg1);
  if (arg0 === undefined) { this.ptr = _emscripten_bind_StringUser_StringUser_0(); getCache(StringUser)[this.ptr] = this;return }
  if (arg1 === undefined) { this.ptr = _emscripten_bind_StringUser_StringUser_1(arg0); getCache(StringUser)[this.ptr] = this;return }
  this.ptr = _emscripten_bind_StringUser_StringUser_2(arg0, arg1);
  getCache(StringUser)[this.ptr] = this;
};
```

### CODE REVIEW

**Comment by kripken** [comment]
Hi @BKcore , can you please make a pull with this to the incoming branch? (We merge to there, and run tests, then only periodically to master.)

**Comment by kripken** [comment]
(I took a quick glance so far, looks very interesting!)

**Comment by BKcore** [comment]
Ah sorry, will do!

**Comment by BKcore** [comment]
Moved to #3395

**Pull request closed without merging**
