### PR TITLE
Auto check parameter type on writeFile

### LINKED ISSUE #6010: fgetc for virtual fs not working properly?
I have the following html calling an emscripten compiled c file:

```
<html><head>
<script src="asm_js_main.js"></script>
<script>
function start() {
    run_nasm = Module.cwrap('run_nasm', null, ['string'])
    
    FS.writeFile('player1.asm', 'mov ax,bx\r\n', { encoding:'binary' })
    
    run_nasm('player1.asm')
}
</script></head>
<body onload="start()">
</body></html>
```

with a single .c file that contains this code:

```
int run_nasm(const char* filename)
{
    const char* filename = argv[1];
    FILE* f = fopen(filename, "rt");
    while (!feof(f)) {
        char c = fgetc(f);
        int ic = (int)c;
        printf("%d\n", ic);
    }
}
```

The expected result is that it would print out the ascii codes of the given file and then -1
instead what it does is output 11 times '0' and then -1.

This indicates a bug in `fgets` but I was not able to locate the bug or find a workaround yet.

### PR DESCRIPTION
**Pull request by saschanaz**
Fixes #6010.

This also fixes an append mode bug on `writeFile`.

### CODE REVIEW

**Comment by juj** [comment]
Good catch on the append mode bug.

I think we would still want to retain a piece of documentation on `FS.writeFile()`, because when one sees JS strings, UTF-16 understandably associates in mind, but `FS.writeFile("testfile", "someString");` will write the string in to the file in UTF-8 form. Perhaps one day we might have a `FS.writeFile("testfile", "someString", { encoding: 'utf8' });` vs `FS.writeFile("testfile", "someString", { encoding: 'utf16le' } );` support, even if not today. So perhaps the changed implementation is good as-is, but we'd keep the documentation on `encoding` parameter in `writeFile`, saying that it defaults to `utf8` and only supported encoding is `utf8`? (and we just ignore it for now) That way the docs will still have a mention that strings will be serialized in utf-8 form, instead of the chance of anyone misassuming utf-16.

The portion where `utf8` vs `binary` is autodetected is good, no sense having to tell if one passed a typed array vs a string.

**Comment by saschanaz** [comment]
I agree that users might be confused with UTF-8 and UTF-16 but couldn't really agree we should keep `encoding: 'utf8'` documentation as it will describe nonexistent code. If we would do, I think we should at least insert a check:

```js
if (opts.encoding !== 'utf8') {
  throw new Error('Unsupported encoding: ' + opts.encoding)
}
```

**Comment by saschanaz** [comment]
But do we have any plan to support UTF-16 etc. in short term? Otherwise we may just describe that `string` data will always be decoded as UTF-8.

**Comment by juj** [comment]
> But do we have any plan to support UTF-16 etc. in short term? Otherwise we may just describe that string data will always be decoded as UTF-8.

I don't think short term (not that anyone has asked for it). I think we should document that encoding is UTF-8. 

> If we would do, I think we should at least insert a check:

I guess we could add that check, but only in `ASSERTIONS=1` mode to not consume space for release builds, since it's basically only to assert a contract. I could go either way, but let's retain a mention in the docs that encoding will be utf-8.

**Comment by juj** [comment]
Perfect, great work!

**Pull request merged**
