### PR TITLE
Add missing SIMD closure externs

### PR DESCRIPTION
**Pull request by dlunch**
Some SIMD functions are missing on closure extern file, preventing SIMD.js code to run with closure compiler. This commit resolves the problem.

### CODE REVIEW

**Comment by kripken** [comment]
Thanks, nice. Let's also add testing for this. Perhaps can just add closure to be run on one of the simd tests in `test_core.py`.

**Comment by dlunch** [comment]
Added closure flag at test_sse1.

**Comment by dlunch** [comment]
I added closure test at test_sse1_full and test_sse2_full and found some missing unofficial simd externs. I amended first commit to address these.

**Comment by kripken** [comment]
Looks pretty good, thanks. Please just add yourself to AUTHORS, and I think we can remove the checks for `is_wasm` (wasm doesn't have simd now anyhow, and is now ok with closure - we should update older tests too, I'll do that).

**Comment by kripken** [comment]
(I fixed the wasm-closure testing stuff in #5197)

**Comment by dlunch** [comment]
@kripken I removed wasm check and updated authors.

**Comment by juj** [comment]
Looks great to me, thanks for working on this! @kripken: feel free to merge if ok to you as well.

**Pull request merged**
