### PR TITLE
Emscripten support for removing wasm-link-metadata tool

### PR DESCRIPTION
**Pull request by jgravelle-google**
Companion to https://github.com/WebAssembly/binaryen/pull/1408

### CODE REVIEW

**Comment by aheejin** [comment]
#6176 will have conflicts with this, so we should either land that first and merge here or the other way.

**Comment by jgravelle-google** [comment]
https://github.com/kripken/emscripten/pull/6176 has been lgtm'd, so I'd merge that before this. I'll rebase both here and in binaryen.

**Comment by kripken** [comment]
(merging is usually easier than rebasing, and good enough if squashing the result anyhow later)

**Comment by jgravelle-google** [comment]
@sbc100 I should probably merge this to go with the binaryen side, can you take a look?

**Pull request merged**
