### PR TITLE
Windows test fixes

### PR DESCRIPTION
**Pull request by juj**

### CODE REVIEW

**Comment by kripken** [comment]
Wait, freetype and poppler have been working til now, haven't they?

Also, symlinks in nodefs?

**Comment by juj** [comment]
That was #694, those have been long time disabled on the bots, but I figure it's just better to disable them for everyone when running locally. Verified this PR to fix #3735 as well.

**Comment by juj** [comment]
I think symlinks have never worked either, I notice that I've got that disabled on the Windows bot, see http://clb.demon.fi:8112/builders/win-incoming/builds/943/steps/Tests-default/logs/stdio for lines `will skip "default.test_unistd_unlink"`. After this the test can be re-enabled on Windows.

**Comment by juj** [comment]
Actually, let me enable all tests to run on the Windows bot and remove each skip, to get things up to date.

**Comment by kripken** [comment]
lgtm

(not merging since not sure you're done working on this)

**Comment by juj** [comment]
Oh, right. Yeah, this is good to go now.

**Comment by kripken** [comment]
Great, thanks for looking into this stuff. Hopefully we can merge incoming to master soon, but i guess we should wait for the os x bot hardware issue too...

**Pull request merged**
