### PR TITLE
Quote Node's fs module calls

### LINKED ISSUE #3230: NODEFS won't work when using --closure 1
NODEFS calls to Node FileSystem functions are replaced by short names, which cause the whole thing to fail :

R.Xa instead of R.lstatSync
R.fa instead of R.writeSync
...
also, the output results of lstatSync are remapped from the original structure to a new structure, but the names are scrambled and therefore nothing work as expected.

setting closure to 0 fixes everything.

This problem was encountered while trying to recompile sql.js from https://github.com/kripken/sql.js/

### PR DESCRIPTION
**Pull request by Kagami**
Fixes #3230

I searched for them with `grep -r '\bfs\.' src`, fixed with `:%s/\vfs\.([^(]+)/fs['\1']/gc` in vim. So there shouldn't be issues with fs calls anymore.

@kripken do I need to provide test for this?

### CODE REVIEW

**Comment by kripken** [comment]
Yes, please add a test. Should be as easy as adding extra testing with closure in an existing test, look for closure in `tests/test_core.py`.

Looks good, just needs a test to merge.

**Comment by Kagami** [comment]
Done. `./tests/runner.py asm2.test_fs_nodefs_rw && ./tests/runner.py other.test_stdin` fails with first commit but works for the second. Also I fixed a few more unquoted properties.

It seems to be too dangerous to write code for Closure - too many places where things might be broken. There are [collection of externs for Node](https://github.com/dcodeIO/node.js-closure-compiler-externs) (it's part of Closure's repo actually), but emscripten doesn't use them. What do you think?

**Comment by kripken** [comment]
I wasn't aware of those node externs. If they fix this, and more things besides, perhaps we should just use them, instead of manually fixing things ourselves? I am ok with that. License of the extens looks fine to put in our `third_party` dir.

**Comment by Kagami** [comment]
Done.

**Comment by kripken** [comment]
Looks good, thanks. Just a few last things:

1. Please duplicate `test_nodefs_rw.c` instead of modifying it, as I see we don't have other testing of those calls, and I'd like see it work both with and without quoting - which I assume it will, with those externs?
2. Please add the LICENSE and COPYRIGHT (or whatever they have) files of the node externs together with the files. Unless it's the same as closure in general? If so then fine as is.
3. Please amend the commit adding the node externs to have "node externs authors" or "closure compiler authors" as the git author.

**Comment by Kagami** [comment]
Done.

1. You are right, quotes are no longer needed. Fixed.
2. Yes, it's the exact same [Apache 2.0 License](https://github.com/dcodeIO/node.js-closure-compiler-externs/blob/master/LICENSE).
3. Fixed.

**Comment by kripken** [comment]
The same license isn't enough though, we need the copyright as well, since it's a separate project from closure compiler? That looks like a separate repo.

I don't actually see one in that repo though. The Apache license file has just the unmodified boilerplate ;) Anyhow, how about just copying that LICENSE file as is into the directory along with the files, and please add a readme.txt with a link to the repo it is from.

**Comment by Kagami** [comment]
Fixed.

**Comment by kripken** [comment]
Thanks!

**Pull request merged**
