### PR TITLE
Remove isinff and isnanf emulation.

### PR DESCRIPTION
**Pull request by waywardmonkeys**
These are not standard functions and aren't used anywhere within
emscripten or needed by normal software.

Fixes issue #1112.

### CODE REVIEW

**Comment by kripken** [comment]
We added these for a reason - do you remember what it was?

**Comment by sunfishcode** [comment]
They were pretty common extensions before C99 made isinf/isnan/etc. type-generic macros, and they're still provided by some systems for compatibility.

**Comment by kripken** [comment]
I guess I'm not sure why we should remove them. We added them to make *some* app work at some point. Is there a harm by keeping them? Do they have security or stability concerns that motivate their removal, or is it just because it's cleaner to remove them?

**Comment by waywardmonkeys** [comment]
We got rid of some other old compat code since then. We used to have things for ``_finite`` and others that are gone now. We originally had these because they came from the pre-musl libc headers and I was just overly complete about not losing symbols at the time of the switch from newlib headers to musl headers.

We don't offer a "complete" emulation of the old deprecated non-standard math API, just a small subset, so I'd rather just get rid of the last remnants. In a quick search on GitHub, it seemed like almost (all?) usage was for libc implementations.

I probably didn't remove them before to limit the risk with the updates to the libc stuff ... and that's why I filed a bug to revisit it later.

**Comment by juj** [comment]
I would recommend keeping these kind of oneliner compatibility functions, as long as they don't obstruct us from updating to a newer MUSL version later on.

**Comment by waywardmonkeys** [comment]
Yet I didn't see software that actually uses them. We shouldn't keep around just part if an old and non-standard API.

**Comment by waywardmonkeys** [comment]
I looked more and found some stuff that uses this ... which is crap, but that's the world we live in.

I'll close this, but I may do a different approach with an inline function that has a deprecation attribute.

**Pull request closed without merging**
