### PR TITLE
needed for compling llvm [DON'T MERGE YET] more to come

### PR DESCRIPTION
**Pull request by UplinkCoder**

### CODE REVIEW

**Comment by juj** [comment]
Does there exist any standard documentation on the location of these? This mentions that it's needed for compiling llvm (with emscripten?). Can you point to the file in LLVM that has the different include path?

We should have all include files in standard locations, so let's figure out if it is LLVM doing an include in wrong directory, or if we have wrong compatibility with the standard.

**Comment by sunfishcode** [comment]
The standard place for unistd.h is <unistd.h>. Probably some ancient Unix systems had <sys/unistd.h>, so that name is provided as a common compatibility alias by GLIBC and others, and so it's not unreasonable for Emscripten to also provide such a compatibility alias.

On the other hand, it appears the last use of <sys/unistd.h> has now been removed, in https://github.com/kripken/emscripten-fastcomp/commit/dec806d5de754962b7e9e5dc0867d031d58ac875 , so it appears we no longer need this for compiling LLVM itself.

**Comment by juj** [comment]
Ok. @UplinkCoder: do you concur with the above? Is this pull request no longer needed?

**Comment by UplinkCoder** [comment]
It does seem like tis patch is no longer needed.
however, I am sure there was somthing else I needed to modify
I'll update the PR soon.

**Comment by waywardmonkeys** [comment]
If this is needed (or something like it), it should go into ``system/include/compat/`` instead of the main includes.

**Pull request closed without merging**
