### PR TITLE
Python 3 compatibility: use universal_newlines

### PR DESCRIPTION
**Pull request by saschanaz**
[`universal_newlines=True` enables text mode for `subprocess` functions](https://docs.python.org/3/library/subprocess.html#using-the-subprocess-module):

>If encoding or errors are specified, or universal_newlines is true, file objects for stdin, stdout and stderr are opened in text mode using the specified encoding and errors or the io.TextIOWrapper default. Otherwise, file objects are opened in binary mode.

This maximizes compatibility by returning native string type for both Python 2 and 3 whereas it currently always returns binary string.

### CODE REVIEW

**Comment by juj** [comment]
This will need very careful testing to be run on Windows under Python 2.7.5.3 64-bit, to make sure this does not affect the codegen to produce mixed newlines to the output.

**Comment by saschanaz** [comment]
`universal_newlines` always gives `\n` for newlines regardless of platform difference, so I think this will provide more safety over consistent newlines. (No code manually replaces `\n` to `\r\n` in my current knowledge)

**Comment by dschuff** [comment]
If we're going to do this kind of big change (and require that we have this flag everywhere), I'd much rather factor all of these subprocesses into a single utility, because it's going to be very easy to forget to add this in the future. Furthermore most of these Popen calls should probably just be `check_call` or `check_output` anyway, so if we're going to touch them all, maybe we should just create a single utility for this PR.

**Comment by saschanaz** [comment]
We already have `execute()` and its friends on shared.py, should we use it everywhere?

https://github.com/saschanaz/emscripten/blob/bd04aa319d163ab76aeffaaaf62569a3d3708505/tools/shared.py#L2527-L2553

**Comment by saschanaz** [comment]
This will be replaced by a future PR with `run_process`.

**Pull request closed without merging**
