### PR TITLE
fix threads.h (#5343)

### PR DESCRIPTION
**Pull request by etienne02**
Fix mutex and conditions includes #5343

### CODE REVIEW

**Comment by kripken** [comment]
This header is from musl, is this an upstream bug?

Also, do you have a testcase showing the problem this PR fixes?

**Comment by etienne02** [comment]
In musl, mutex_t and cond_t are always defined in bits/alltypes.h.in but here these types are defined whith __NEED_pthread_mutex_t and __NEED_pthread_cond_t. It's maybe the file bits/alltypes.h to modify and not threads.h.

**Comment by juj** [comment]
Thanks, this looks like a clear typo in upstream musl. I pushed a fix in directly in the above commit, since we have a specific convention of marking local changes to musl headers to keep it easy to update to newer versions.

**Comment by juj** [comment]
Sent an email to musl list about this, since looks like the typo is present also in latest musl tree.

**Comment by juj** [comment]
A contributor from musl reported that it's actually not a typo, but looking at the generated `allbits.h` in upstream musl, it reads as follows:

```c
#if defined(__NEED_pthread_mutex_t) && !defined(__DEFINED_pthread_mutex_t)
typedef struct { union { int __i[10]; volatile int __vi[10]; volatile void *volatile __p[5]; } __u; } pthread_mutex_t;
#define __DEFINED_pthread_mutex_t
#endif

#if defined(__NEED_mtx_t) && !defined(__DEFINED_mtx_t)
typedef struct { union { int __i[10]; volatile int __vi[10]; volatile void *volatile __p[5]; } __u; } mtx_t;
#define __DEFINED_mtx_t
#endif

#if defined(__NEED_pthread_cond_t) && !defined(__DEFINED_pthread_cond_t)
typedef struct { union { int __i[12]; volatile int __vi[12]; void *__p[6]; } __u; } pthread_cond_t;
#define __DEFINED_pthread_cond_t
#endif

#if defined(__NEED_cnd_t) && !defined(__DEFINED_cnd_t)
typedef struct { union { int __i[12]; volatile int __vi[12]; void *__p[6]; } __u; } cnd_t;
#define __DEFINED_cnd_t
#endif
```

That is, they alias to have both types. We have `alltypes.h` reading as

```c
#if defined(__NEED_pthread_mutex_t) && !defined(__DEFINED_pthread_mutex_t)
typedef struct { union { int __i[7]; volatile int __vi[7]; volatile void *__p[7]; } __u; } pthread_mutex_t;
typedef pthread_mutex_t mtx_t;
#define __DEFINED_pthread_mutex_t
#endif

#if defined(__NEED_pthread_cond_t) && !defined(__DEFINED_pthread_cond_t)
typedef struct { union { int __i[12]; volatile int __vi[12]; void *__p[12]; } __u; } pthread_cond_t;
typedef pthread_cond_t cnd_t;
#define __DEFINED_pthread_cond_t
#endif
```

which probably comes from an earlier musl version. The effect of defining both is basically the same though.

**Pull request closed without merging**
