### PR TITLE
emscripten_set_offscreencanvas_size_on_target_thread_js

### PR DESCRIPTION
**Pull request by kripken**
replacement for #7623 , as discussed there.

### CODE REVIEW

**Comment by kripken** [comment]
@nickshinpho @kainino0x perhaps you can test this? (I'm not sure what bug it is meant to fix.)

**Comment by kainino0x** [comment]
Deferring to Nick, I wasn't looking at this problem.

**Comment by nickshin** [comment]
let me test this tomorrow morning.  i had some problems integrating all of the changes from the github repo back to the epic perforce depot.  i have the "problem" commit narrowed down and anticipate to finish the integration (merge back) to perforce tonight.

**Comment by nickshinpho** [comment]
@kripken single and multi-threaded builds and runs ok with these changes.

**Comment by kripken** [comment]
This is urgent, so landing now. @juj please take a look later if you can, though.

**Pull request merged**
