### PR TITLE
Enable LLVM 4.0

### PR DESCRIPTION
**Pull request by ddcc**

### CODE REVIEW

**Comment by kripken** [comment]
This is a little tricky. In general we have only supported one LLVM version at a time, because it wasn't feasible to do more. To be more specific, for us to not warn on 4.0 being unsupported we would need to be sure that using 4.0 passes the full test suite and does not regress the benchmark suite.

A possible alternative is to support 3.9 with fastcomp and 4.0 with the llvm backend, i.e., to support just one version in each configuration. Their bitcode is incompatible anyhow due to the target being different. (However, @sunfishcode is moving to unify the triple, so if we did this we'd still need to keep the bitcodes separate.)

Another option is to just wait for the `next-merge` branches to be merged in. I'm going to look into that some more today, I'm not sure yet if it will update fastcomp to 4.0, but if it did that would solve this.

**Comment by ddcc** [comment]
Ah, I wasn't aware of that. I don't believe LLVM 3.9 has even been released; they're currently on RC1, but the master branch is now reporting as 4.0.

**Comment by kripken** [comment]
Right, yeah, I just saw that too, 4.0 is trunk, and 3.9 is being finalized.

Looks like rust has updated to somewhere in the middle of the 3.9 release branch, and since a goal is to sync with them, I'm updating the `next-merge` branches to the same commit. However, that means that we will stay on an LLVM that reports 3.9, so this issue is still present. Perhaps we should consider the different-version-for-asm-vs-wasm approach mentioned before.

**Comment by kripken** [comment]
This PR is quite old, closing. Feel free to reopen if still relevant.

**Pull request closed without merging**
