### PR TITLE
Remove `pre-main prep time:` logging on startup.

### PR DESCRIPTION
**Pull request by kkimdev**
#6156

### CODE REVIEW

**Comment by kripken** [comment]
lgtm, thanks!

Please just add yourself to AUTHORS before we merge (you can add that commit with `[ci skip]` in the title, to save unnecessary work on the test bots).

**Comment by kkimdev** [comment]
added. forgot to add [ci skip] at the last second sorry :( I guess we will just wait.

**Comment by kripken** [comment]
No worries, I can just cancel the builds :)

Thanks again, merging.

**Comment by kripken** [comment]
(Actually I think the builds auto-cancel anyhow when they are not needed, which is the case when the PR is merged.)

**Pull request merged**
