### PR TITLE
Expand big switches

### PR DESCRIPTION
**Pull request by kripken**
For #3534

Landing this needs to wait on the fastcomp pull first

### CODE REVIEW

**Comment by asRIA** [comment]
@juj I've tried to test this patch (incoming emcc (Emscripten gcc/clang-like replacement) 1.34.1 (commit 0c6bd9bab879e637c52e35d528ad2581d718fc47)) And unfortunately we have still issue with llvm optimizer

```
Traceback (most recent call last):
  File "C:\Emscripten\emscripten\incoming\\emcc", line 1260, in <module>
    shared.Building.llvm_opt(final, link_opts)
  File "C:\Emscripten\emscripten\incoming\tools\shared.py", line 1429, in llvm_opt
    assert os.path.exists(target), 'Failed to run llvm optimizations: ' + output
AssertionError: Failed to run llvm optimizations:
make.exe[2]: *** [build/stritz.js] Error 1
make.exe[1]: *** [CMakeFiles/stritz.dir/all] Error 2
make.exe: *** [all] Error 2
```

I've tested compilation with commented out known places with big 'switch/case' but it still break during call `opt`
During debugging opt we have similar error stack size exceeded
```
 	opt.exe!llvm::SmallDenseMap<llvm::Use const * __ptr64,unsigned int,16,llvm::DenseMapInfo<llvm::Use const * __ptr64>,llvm::detail::DenseMapPair<llvm::Use const * __ptr64,unsigned int> >::getLargeRep() Line 957	C++
 	opt.exe!llvm::SmallDenseMap<llvm::Use const * __ptr64,unsigned int,16,llvm::DenseMapInfo<llvm::Use const * __ptr64>,llvm::detail::DenseMapPair<llvm::Use const * __ptr64,unsigned int> >::getBuckets() Line 968	C++
 	opt.exe!llvm::DenseMapBase<llvm::SmallDenseMap<llvm::Use const * __ptr64,unsigned int,16,llvm::DenseMapInfo<llvm::Use const * __ptr64>,llvm::detail::DenseMapPair<llvm::Use const * __ptr64,unsigned int> >,llvm::Use const * __ptr64,unsigned int,llvm::DenseMapInfo<llvm::Use const * __ptr64>,llvm::detail::DenseMapPair<llvm::Use const * __ptr64,unsigned int> >::getBuckets() Line 387	C++
 	opt.exe!llvm::DenseMapBase<llvm::SmallDenseMap<llvm::Use const * __ptr64,unsigned int,16,llvm::DenseMapInfo<llvm::Use const * __ptr64>,llvm::detail::DenseMapPair<llvm::Use const * __ptr64,unsigned int> >,llvm::Use const * __ptr64,unsigned int,llvm::DenseMapInfo<llvm::Use const * __ptr64>,llvm::detail::DenseMapPair<llvm::Use const * __ptr64,unsigned int> >::LookupBucketFor<llvm::Use const * __ptr64>(const llvm::Use * const & Val, const llvm::detail::DenseMapPair<llvm::Use const *,unsigned int> * & FoundBucket) Line 480	C++
 	opt.exe!llvm::DenseMapBase<llvm::SmallDenseMap<llvm::Use const * __ptr64,unsigned int,16,llvm::DenseMapInfo<llvm::Use const * __ptr64>,llvm::detail::DenseMapPair<llvm::Use const * __ptr64,unsigned int> >,llvm::Use const * __ptr64,unsigned int,llvm::DenseMapInfo<llvm::Use const * __ptr64>,llvm::detail::DenseMapPair<llvm::Use const * __ptr64,unsigned int> >::lookup(const llvm::Use * const & Val) Line 161	C++
>	opt.exe!`anonymous-namespace'::BitcodeReader::ParseUseLists::__l26::<lambda>(const llvm::Use & L, const llvm::Use & R) Line 2594	C++
 	opt.exe!llvm::Value::mergeUseListsImpl<bool <lambda>(const llvm::Use &, const llvm::Use &) >(llvm::Use * L, llvm::Use * R, llvm::Use * * Next, `anonymous-namespace'::BitcodeReader::ParseUseLists::__l26::bool <lambda>(const llvm::Use &, const llvm::Use &) Cmp) Line 609	C++
 	opt.exe!llvm::Value::mergeUseListsImpl<bool <lambda>(const llvm::Use &, const llvm::Use &) >(llvm::Use * L, llvm::Use * R, llvm::Use * * Next, `anonymous-namespace'::BitcodeReader::ParseUseLists::__l26::bool <lambda>(const llvm::Use &, const llvm::Use &) Cmp) Line 616	C++
...
```

Unfortunately I don't know how I can find where is the problem actually.

Any tips how I can discover some trackable name (class/function name) what makes problem?

**Comment by kripken** [comment]
Can you share the code to reproduce the problem?

**Comment by asRIA** [comment]
Unfortunately I can't share specific use case. I will try to investigate it a little more to extract specific use case. 

As a additional info I've tried to compile with `-s DISABLE_EXCEPTION_CATCHING=1 -fno-exceptions` but still problem exists.

**Comment by kripken** [comment]
@juj is looking into an issue with similar symptoms to yours, might be the same thing. Seems like a windows-specific LLVM problem.

**Comment by juj** [comment]
@asRIA : I've posted a pull request to emscripten-fastcomp side, which should fix the crash issue you were seeing. That crash was not related to this big switch issue, but they are separate. See https://github.com/kripken/emscripten-fastcomp/pull/104 . After that lands, let me know if the issue still persists for you.

**Comment by asRIA** [comment]
@juj Thank you, it works.

**Pull request merged**
