### PR TITLE
Autogenerate gl.c, so that GetProcAddress supports all possibilities

### PR DESCRIPTION
**Pull request by kripken**
Also manually remove one entry that appeared twice.

### CODE REVIEW

**Comment by kjlubick** [comment]
FWIW: We noticed the size of our .wasm file increase by about 30k when upgrading from 1.38.6 to 1.38.16.  [bloaty](https://github.com/google/bloaty) showed that _emscripten_GetProcAddress went from about 8 kB to about 41 kB, so this PR might be one reason why.

**Comment by kripken** [comment]
@kjlubick yeah, that's a downside of using GetProcAddress and other things that decide which functions to use at runtime - the compiler can't eliminate dead code, so all GL functions will be kept alive (and improvements like this PR will increase that size).

To reduce code size, it's best to avoid GetProcAddress and access GL functions directly.

**Comment by kjlubick** [comment]
Can you clarify what it might look like to get rid of GetProcAddress?

I'm guessing it involves defining something like
extern const GLubyte* emscripten_glGetStringi( GLenum name, GLuint index);

in my code, but this fails at link-time
undefined symbol: _Z23emscripten_glGetStringijj

Do I need to add a flag to make the symbols from https://github.com/emscripten-core/emscripten/blob/1c983f06cb61372d3cf9aa22ba332e13de439d26/system/lib/gl.c available to the linker?  Am I simply using the wrong name for the symbols?

**Comment by kripken** [comment]
You can avoid all the indirection by just calling `glGetStringi` directly.

**Pull request merged**
