### PR TITLE
Multithreading 27/N: Store Wasm Module also in sync Wasm compilation

### PR DESCRIPTION
**Pull request by juj**
Pass Wasm Module to receiveInstance() also when doing sync Wasm compilation

### CODE REVIEW

**Comment by kripken** [comment]
Looks like this is approved and ready to land?

**Comment by juj** [comment]
The CI fails on test

```
======================================================================
ERROR: test_pthread_global_data_initialization (test_browser.browser)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/emscripten/tests/test_browser.py", line 3615, in test_pthread_global_data_initialization
    self.btest(path_from_root('tests', 'pthread', 'test_pthread_global_data_initialization.c'), expected='20', args=args + mem_init_mode + ['-s', 'USE_PTHREADS=1', '-s', 'PROXY_TO_PTHREAD=1', '-s', 'PTHREAD_POOL_SIZE=1'])
  File "/root/emscripten/tests/runner.py", line 1152, in btest
    self.run_browser(outfile + url_suffix, message, ['/report_result?' + e for e in expected], timeout=timeout)
  File "/root/emscripten/tests/runner.py", line 997, in run_browser
    self.assertIdentical(expectedResult, output)
  File "/root/emscripten/tests/runner.py", line 642, in assertIdentical
    limit_size(''.join([a.rstrip() + '\n' for a in difflib.unified_diff(x.split('\n'), y.split('\n'), fromfile='expected', tofile='actual')]))
Exception: Expected to have '/report_result?20' == '[no http server activity]', diff:

--- expected
+++ actual
@@ -1 +1 @@
-/report_result?20
+[no http server activity]
```

which was modified in this PR, but I am unable to reproduce the failure locally, it does pass for me. I wonder if the test is running for too long? (is there a timeout limit?)

```
C:\code\emsdk\emscripten\incoming>python tests\runner.py browser.test_pthread_global_data_initialization
WARNING:tests\runner.py:use EMTEST_ALL_ENGINES=1 in the env to run against all JS engines, which is slower but provides more coverage
WARNING: no 'numpy' module, HyBi protocol will be slower
WARNING: no 'resource' module, daemonizing is disabled
Test suites:
['test_browser']
Running test_browser: (1 tests)
(checking sanity from test runner)
INFO:root:(Emscripten: Running sanity checks)
Using Emscripten browser: ['C:/Program Files/Firefox Nightly/firefox.exe', '-P', 'test_nightly', '--no-remote']
[Browser harness server on process 13040]

Running the browser tests. Make sure the browser allows popups from localhost.

test_pthread_global_data_initialization (test_browser.browser) ... [browser launch: test.html ]
[server response: /report_result?20 ]
[browser launch: test.html ]
[server response: /report_result?20 ]
[browser launch: test.html ]
[server response: /report_result?20 ]
[browser launch: test.html ]
[server response: /report_result?20 ]
[browser launch: test.html ]
[server response: /report_result?20 ]
[browser launch: test.html ]
[server response: /report_result?20 ]
[browser launch: test.html ]
[server response: /report_result?20 ]
[browser launch: test.html ]
[server response: /report_result?20 ]
[browser launch: test.html ]
[server response: /report_result?20 ]
[browser launch: test.html ]
[server response: /report_result?20 ]
[browser launch: test.html ]
[server response: /report_result?20 ]
[browser launch: test.html ]
[server response: /report_result?20 ]
[browser launch: test.html ]
[server response: /report_result?20 ]
[browser launch: test.html ]
[server response: /report_result?20 ]
[browser launch: test.html ]
[server response: /report_result?20 ]
[browser launch: test.html ]
[server response: /report_result?20 ]
[browser launch: test.html ]
[server response: /report_result?20 ]
[browser launch: test.html ]
[server response: /report_result?20 ]
[browser launch: test.html ]
[server response: /report_result?20 ]
[browser launch: test.html ]
[server response: /report_result?20 ]
[browser launch: test.html ]
[server response: /report_result?20 ]
ok
[Browser harness server terminated]

----------------------------------------------------------------------
Ran 1 test in 69.584s

OK
```

**Comment by kripken** [comment]
@juj I think what's going on here is that this test fails on CI in chrome, but not firefox. Testing locally I can confirm the same. The issue is sync compilation, which chrome disallows. Please mark the test with `@requires_sync_compilation`, however, if this is an important test perhaps split it so the part with `BINARYEN_ASYNC_COMPILATION=0` does run in chrome.

**Comment by juj** [comment]
Oh, good catch, that makes sense. Updated PR, let's see what the CI thinks now.

**Pull request merged**
