### PR TITLE
Add binaryen tests

### PR DESCRIPTION
**Pull request by saschanaz**
And fix them. Sorry for breaking them 😱

### CODE REVIEW

**Comment by saschanaz** [comment]
The `argparse` documentation says:

>'store_true' and 'store_false' - These are special cases of 'store_const' used for storing the values True and False respectively. In addition, they create default values of False and True respectively.

`default=None` is now explicitly set to prevent this so that emscripten.py can correctly follow the configuration when no flags.

**Comment by kripken** [comment]
Thanks! Looks good, although `other.test_legalize_js_ffi` fails on CI, while it passes for me locally, which is odd.

**Comment by saschanaz** [comment]
It also fails on my Ubuntu environment and the first bad commit is 740284ec.

**Comment by kripken** [comment]
Ah, that makes sense, we need to update the binaryen tag. Opened #5761

**Comment by kripken** [comment]
This should now pass after that version_39 PR landed. I restarted the job. But I realize maybe that's not enough and we need to merge it into here? Not sure how github works...

**Comment by saschanaz** [comment]
Precompiled SDK explicitly sets BINARYEN_ROOT to `~/emsdk-portable/clang/e1.37.22_64bit/binaryen` which is statically provided, so I'm afraid that the PR still won't fix this.

**Comment by kripken** [comment]
Hmm. @juj, remind me how the sdk decides to get a new binaryen version? Do we need a new 1.37.23 tag in all 4 repos?

**Comment by kripken** [comment]
Alternatively, maybe we should not use the sdk's binaryen, and instead let emcc get it, so updates to the port will take effect immediately?

**Comment by saschanaz** [comment]
I'm trying to find a way but removing `BINARYEN_ROOT` from `.emscripten` just causes total failure instead of automatically getting VERSION_39.

**Comment by kripken** [comment]
That's odd, is that just on the bot? I've been testing locally with it removed and it works ok (except for the specific side module issue which #5763 addresses)

**Comment by saschanaz** [comment]
I'm testing on my Ubuntu and Windows environments and both fails to build binaryen automatically and uses `shared.BINARYEN_ROOT` as an empty 0-length string.

**Comment by saschanaz** [comment]
Filed #5764 while trying to understand the situation...

**Comment by kripken** [comment]
Landing, the last failure here is the one fixed by binaryen 39 which was updated to already on incoming.

**Comment by juj** [comment]
> Hmm. @juj, remind me how the sdk decides to get a new binaryen version? Do we need a new 1.37.23 tag in all 4 repos?

Yeah, there will need to be a matching tag in all 4 repos. When that is detected, then the tagbuilder tasks kick off a new build and deployment.

**Comment by kripken** [comment]
Got it, thanks @juj.

As mentioned elsewhere, I think we should disable these tests for now, unless we think this will be fixed later today or tomorrow - any objections?

**Pull request merged**
