### PR TITLE
Support various module loaders with MODULARIZE

### PR DESCRIPTION
**Pull request by dcodeIO**
As discussed in WebAssembly/binaryen#1341 this change adds support for AMD loaders to MODULARIZE-ed outputs.

### CODE REVIEW

**Comment by kripken** [comment]
Thanks!

So, I don't really understand these ecosystems myself. How important is it to support AMD? We haven't gotten a request for this support, but I'm not sure if that means anything... maybe not enough people are using MODULARIZE...

cc @yurydelendik

**Comment by dcodeIO** [comment]
Not sure how urgent this is for the vast amount of emscripten users, but when I create JavaScript modules, I always make sure that it is a proper [UMD](http://bob.yexley.net/umd-javascript-that-runs-anywhere) module so it "just works". The reason for proposing this here is that AMD-support is gone from binaryen.js after the switch to MODULARIZE, and I'd like to still provide an UMD module using the [binaryen.js buildbot](https://github.com/AssemblyScript/binaryen.js) that publishes to npm.

Ultimately, I'd guess that AMD will be gone for good at some point in time, with the new import/export syntax modern JavaScript has, but it's still somewhat too early to phase it out, imho.

Nonetheless, no matter how you decide, it's also easy to patch AMD support into the buildbot by simply concatenating one additional line of code.

**Comment by yurydelendik** [comment]
> ...  I always make sure that it is a proper UMD module so it "just works".

@dcodeIO Indeed, it will be nice to see standard UMD. What will it take to properly wrap emcc generated code with UMD? The proposed fix might have some unwanted effect when a packager will auto-detect the module format and/or replace `typeof require === "function"` with constants. (Let me play with the patch to see if it's a concern)

**Comment by dcodeIO** [comment]
Afaik there is already a check for CommonJS (just changed it to a more standard one in this PR) and there's always a global var. So the only missing thing basically is to check for the presence of the `define` function with a trueish `.amd` property and call it with a factory function returning the exports.

**Comment by yurydelendik** [comment]
I was playing UMD variant proposed here at https://github.com/yurydelendik/old-man-sandbox/tree/master/emcc-6006 . See [test.js](https://github.com/yurydelendik/old-man-sandbox/blob/master/emcc-6006/test.js) and [result produced by webpack](https://github.com/yurydelendik/old-man-sandbox/blob/master/emcc-6006/result.js) after its consuming the input. Notice that webpack was confused about this AMD format and added some polyfill to the output. I also added "test.old.js" to see old format output and "test.proposed.js" to wrap body in standard UMD format. The latter looks like a better choice.

**Comment by dcodeIO** [comment]
One issue I see with

```js
if (typeof module === "object" && module.exports)
```

is that `module` is also of type `object` when it's `null`, resulting in a `ReferenceError` in such a case. It's certainly unusual that there's a `var module = null` in the scope here, but possible.

Not sure about the polyfill code being added by webpack. Maybe it's safe enough when just doing:

```js
if (typeof module === "object" && module && module.exports)
```

**Comment by yurydelendik** [comment]
The webpack generates different UMD header, see https://github.com/webpack/webpack/issues/5826 . We can use something along these lines of:

```
(function(root, factory) {
    if(typeof exports === 'object' && typeof module === 'object')
        module.exports = factory();
    else if(typeof define === 'function' && define.amd)
        define([], factory);
    else if(typeof exports === 'object')
        exports["Test"] = factory();
    else
        root["Test"] = factory();
...
```

**Comment by dcodeIO** [comment]
I see. Though, this makes the `ReferenceError` occur when there is either a `module = null` with any object `exports`, or `exports = null` with any non-object `module` in scope. Not sure how important this is in practice, just mentioning.

**Comment by yurydelendik** [comment]
> Not sure how important this is in practice, just mentioning.

If somebody will produce such environment, they will have issues with almost all UMD modules. There is no point to protect us from such use case IMHO.

**Comment by dcodeIO** [comment]
> If somebody will produce such environment, they will have issues with almost all UMD modules.

I agree.

> There is no point to protect us from such use case IMHO

Personally I'd say that something that's so easy to mitigate should be mitigated (unless it still confuses webpack, ofc), but that's debatable and I'm fine with both.

**Comment by yurydelendik** [comment]
>  Personally I'd say that something that's so easy to mitigate should be mitigated (unless it still confuses webpack, ofc),

It's better to choose something standard (canonical UMD, webpack UMD, etc.), so packagers will not be confused that much and they could provide the best transformation for the generated module.

**Comment by dcodeIO** [comment]
Alright, let's just use webpack's version then.

**Comment by yurydelendik** [comment]
(Updated example at https://github.com/yurydelendik/old-man-sandbox/blob/master/emcc-6006/result.js)

The proposed patch looks good to me.

**Comment by kripken** [comment]
Looks good to me too. Can we add a test for the new functionality? We do test modularize and require in node already, so that should already be covered.

**Comment by dcodeIO** [comment]
Should be good now incl. a test, wdyt?

**Comment by kripken** [comment]
Thanks, looks good. Please just add yourself to AUTHORS before we merge (can make the commit message with `[ci skip]` to avoid running CI).

**Comment by dcodeIO** [comment]
Sorry, messed up the CI. Not, my, day.

**Comment by ncave** [comment]
This change unfortunately breaks the import from typescript:

if I change the exports from:
`module.exports = %(EXPORT_NAME)s;`
back to:
`module['exports'] = %(EXPORT_NAME)s;`
then it works again.

(emscripten v1.37.34, latest NodeJS, TypeScript, rollup).

**Comment by yurydelendik** [comment]
@ncave can you provide a little bit more information such as minimal test case to demonstrate the issue? or reason why it breaks?

**Comment by dcodeIO** [comment]
Did something change with closure externs? The code, as is, relies on externs for `module` with an `exports` property to be present.

**Comment by ncave** [comment]
@yurydelendik Here is what gets generated:
mywasm.js
```
  ...
  return ModuleFunc;
};
if (typeof exports === 'object' && typeof module === 'object')
  module.exports = ModuleFunc;
else if (typeof define === 'function' && define['amd'])
  define([], function() { return ModuleFunc; });
else if (typeof exports === 'object')
  exports["ModuleFunc"] = ModuleFunc;
export { ModuleFunc };
```

And how it's being consumed:
```
import { ModuleFunc } from "../js/wasm/mywasm";
```
works again, as already mentioned, if exports are changed to:
`module['exports'] = ModuleFunc;`

**Comment by yurydelendik** [comment]
@ncave why there is `export { ModuleFunc };` at the end?

**Comment by ncave** [comment]
@yurydelendik Doh, I was adding that before to make it work, I guess I need to find another way. Thanks a lot, sorry about that.

**Comment by yurydelendik** [comment]
Small working TS example:

main.ts:
```
import * as ModuleFunc from "./mywasm"; // CommonJS with "default" export
console.log(ModuleFunc()());
```

mywasm.js:
```
var ModuleFunc = function () {
  function ModuleFunc() {
    return "test";
  }

  return ModuleFunc;
};

if (typeof exports === 'object' && typeof module === 'object')
  module.exports = ModuleFunc;
else if (typeof define === 'function' && define['amd'])
  define([], function() { return ModuleFunc; });
else if (typeof exports === 'object')
  exports["ModuleFunc"] = ModuleFunc;
```

**Comment by ncave** [comment]
@yurydelendik Thanks, I really appreciate your help!

**Pull request merged**
