### PR TITLE
Use "X not in Y" rather then "not X in Y" in python scripts

### PR DESCRIPTION
**Pull request by sbc100**
This is the more idomatic way to do it in python and
less potentially abigous when combined with other terms.

### CODE REVIEW

**Comment by juj** [comment]
https://stackoverflow.com/questions/3481554/if-loop-x-not-in-vs-not-x-in and https://docs.python.org/3/library/stdtypes.html#dict.setdefault for reference.

lgtm, @sbc100 : is your contact info in `AUTHORS`?

**Comment by sbc100** [comment]
Added myself to AUTHORS!

**Comment by buu700** [comment]
@sbc100, looks like you were actually already in there a few lines up. (Also, the new one you added and Ondrej Stava's are both missing closing parens.)

**Comment by sbc100** [comment]
Oops, thanks.  Will fix

**Pull request merged**
