### PR TITLE
SDL2_IMAGE_FORMATS check string on Windows Platform

### PR DESCRIPTION
**Pull request by ssx71**
in referring this issue : https://github.com/kripken/emscripten/issues/5693
SDL2_IMAGE_FORMATS check string on Windows Platform

### CODE REVIEW

**Comment by SaschaNaz** [comment]
I'm really not sure whether this is a right thing to do... It's just that CMD does not process single quotes as quotes.

**Comment by ssx71** [comment]
better to prevent it from curing, however you do as you wish.

**Comment by curiousdannii** [comment]
If any such approach is used it should be applied to all parameters, not just SDL2_IMAGE_FORMATS .

**Comment by ssx71** [comment]
do you mean this way?
	
	import platform
	if ( platform.platform().find("Windows")!=-1 ):
		for i in range(0,len(sys.argv)):
			sys.argv[i]=sys.argv[i].replace("'[","['").replace("]'","']");

**Comment by SaschaNaz** [comment]
I think we cannot really fix this, as `-s OPTION='["ABC"]'` even becomes `OPTION='[ABC]'` on PowerShell. And PowerShell is now not a Windows specific shell.

**Comment by ssx71** [comment]
you are right . close this pull request.

**Pull request closed without merging**
