### PR TITLE
Embind: Only store one instance of each function signature static string

### PR DESCRIPTION
**Pull request by waywardmonkeys**
We (IMVU) have started experimenting with the new memory initializer code and doing so, it made it easier to see what strings were in memory. I found that the signature data from embind was actually fairly sizable in the codebase and clang was unable to merge the constants as they were not ``unnamed_addr``.

This patch from @jlee-imvu improves the embind code to coalesce these signatures and results in a substantial code size improvement for us.

This passes the embind tests in emscripten (``ALL.test_embind``, ``ALL.test_embind_2`` and ``other.test_embind``).

### CODE REVIEW

**Comment by chadaustin** [comment]
Very nice @waywardmonkeys and @jlee-imvu!  Looks good to me.

**Comment by kripken** [comment]
Nice!

In other news, #3561 will shrink memory inits further.

**Comment by jlee-imvu** [comment]
Ah, cool.  I was wondering why removing a relatively small number of short
strings was helping so much! :)

**Comment by waywardmonkeys** [comment]
@jlee-imvu I think there's something else at play, but I haven't tracked it down yet. The change in size of the actual memory initializer didn't seem to entirely correspond with the change in size of the whole JS file, so I think something else changed in the generated JS.

**Pull request merged**
