### PR TITLE
Add travis build on trusty

### PR DESCRIPTION
**Pull request by dschuff**

### CODE REVIEW

**Comment by dschuff** [comment]
@kripken just for fun I copied your travis file from #5078 and updated for trusty. but i forgot that travis is turned off on GH. Want to try to turn it back on?

**Comment by kripken** [comment]
Sure, trying now. But I think in that other PR we got stuck on an emsdk issue that we were waiting for @juj on.

**Comment by kripken** [comment]
Enabled. You may need to re-push or something.

**Comment by dschuff** [comment]
Looks like it's still failing with a libstdc++ that's too old (it wants a symbol with version GLIBCXX_3.4.21 and it looks like the libstdc++ on trusty only has GLIBCXX_3.4.19.

**Comment by dschuff** [comment]
I just tried emsdk on my trusty box and got the same result. Seems like we should fix this on the release builder, it's probably useful to support such systems, and it's not super difficult. If glibc is good and the problem is libstdc++, gcc has a flag `--static-libstdc++` that causes libstdc++ to be linked statically.

**Comment by kripken** [comment]
Oh nice, that sounds simple. @juj, what do you think?

**Comment by aidanhs** [comment]
If it's linking against a newer libstdc++ that presumably also means it's not being built on trusty? If that's the case I'd imagine it's better to move the release builder itself down to trusty, otherwise glibc compatibility is a problem waiting to happen.

**Comment by juj** [comment]
@dschuff : which executable is causing the link error? I.e. should we add `--static-libstdc++` to link of LLVM/Clang, to Emscripten's optimizer, or to Binaryen executables, or all of those?

**Comment by dschuff** [comment]
I imagine we'd need to add it to all of the C++ programs.
BTW, what kind of system are you building these binaries on? A more general solution would be to downgrade it, or to use a sysroot. PNaCl and Chrome are built in a sysroot built from Debian Jessie or Wheezy which makes for a very nice reproducible build.

**Pull request closed without merging**
