### PR TITLE
do not export getValue and setValue by default

### PR DESCRIPTION
**Pull request by kripken**
Also add a mechanism in ASSERTIONS that emits stubs that give an error message, so if a user depended on those being exported, in ASSERTIONS they get a clear error message.

### CODE REVIEW

**Comment by curiousdannii** [comment]
If I have a custom library file, will replacing `getValue` with `{{{ makeGetValue }}}` ensure it still works?

**Comment by kripken** [comment]
Better than that, actually, it will still work without you doing anything :) We do still initially emit `getValue`, this PR just makes us not export it, and the JSDCE optimization pass will only remove a function that is neither exported nor used.

(That's true for a custom js library file, or any other code that gets optimized with the other JS. But if you use it from outside, you should be using `Module.getValue` anyhow.)

I changed that one direct use of `getValue` to `{{{ makeGetValue .. }}}` in this PR because the macro will emit a direct heap access - so it no longer references `getValue` and will not keep it alive. But if you add a direct use of `getValue` in your code, it's fine, the function will not get removed.

**Comment by kripken** [comment]
Added some test fixes and improvements, and verified this passes all the tests locally, should be good to go.

**Comment by juj** [comment]
lgtm, I think this is exactly the direction we want to go, this will help developers explicitly make the choices what to include in.

**Comment by kripken** [comment]
Thanks @juj. Before merging I'll mention this on the mailing list too for feedback. And I added a Changelog update for this as suggested by @curiousdannii in https://github.com/kripken/emscripten/issues/5836#issuecomment-346912662

**Comment by kripken** [comment]
Just to be safe I waited for feedback an extra week after the lgtm here because this is the first of the breaking changes we've been discussing. Also discussion on the mailing list has been in support. Merging.

**Pull request merged**
