### PR TITLE
Implement readdir for WORKERFS

### PR DESCRIPTION
**Pull request by Deamon87**

### CODE REVIEW

**Comment by kripken** [comment]
Looks good. Yeah, same code as memfs should work (I wish we had a better way to share that code, but that's something for another PR).

This needs a test. See `test_fs_workerfs_*` in `test_browser.py`. Perhaps there's a natural way to add it to the `read` test, or if not, a new test.

**Comment by Deamon87** [comment]
Implemented check for `opendir`\`readdir` functions(they both map to `readdir` from FS object) into that test.
I'm just not sure how well it fit there. What do you think?

**Comment by kripken** [comment]
Looks ok to me, thanks. Please add yourself to AUTHORS if you aren't already there.

**Comment by Deamon87** [comment]
Done, thanks

**Comment by kripken** [comment]
Merged, thanks!

**Pull request merged**
