### PR TITLE
Link in objects when they provide commons we need, not just defs

### PR DESCRIPTION
**Pull request by kripken**
Needs more testing - not sure yet if we don't need to avoid linking in such files in some cases - and to add a test.

See #4763.

### CODE REVIEW

**Comment by juj** [comment]
What's the difference between a def and a common?

**Comment by kripken** [comment]
A "def" is a defined symbol, something with content (which could be text, or data, etc.). A "common" (C in nm output) is zero-initialized memory. Probably some historic reason for the terminology that I am not aware of...

**Comment by kripken** [comment]
I learned most of what I know about this from reading `man nm` ;)

**Comment by dschuff** [comment]
I think the historic reason refers to Fortran's COMMON blocks. Commons are also known as 'tentative definitions'. When writing code it's better to declare `extern int foo;` (an undefined ref) rather than `int foo;` (a common) in all but one file, and we actually defaulted PNaCl's frontend to use `-fno-common` which IIRC turns `int foo;` into a strong def instead. The downside of that is that use of commons where undefined refs were intended is fairly common, so that sometimes results in code that works on other platforms (that has `int foo;` in more than one file) getting multiple definition errors.

So, anyway. I think this is the right behavior for archives (IIUC this change means that a tentative/common definition of a symbol that currently has an undefined reference will cause a member to be included from an archive, right?). So assuming commons are properly handled elsewhere I think this should be ok.

**Comment by kripken** [comment]
Ok, sounds good. I also ran the test suite, no problems. And I added a test for this. Merging.

**Pull request merged**
