### PR TITLE
Crash fix for "for .. in + third party framework" bug

### PR DESCRIPTION
**Pull request by Jura-Z**
I replaced for..in only in library_gl but emscripten codebase is full of for..in's. Any idea how to handle this?

### CODE REVIEW

**Comment by kripken** [comment]
Why is this needed? What JS engine doesn't support for..in loops yet?

**Comment by Jura-Z** [comment]
Well, a lot of frameworks change Array.prototype (mootools, for instance) adding their custom functions there that are enumerable, unfortunately. So for..in will enumerate through that functions as well. Take a look at the modified test. With for..in this test would fail.

**Comment by juj** [comment]
Thanks! Was this enough to get the code running with mootools? Or are there other such locations?

**Comment by Jura-Z** [comment]
This was it. But looking at other 'for..in' appearance in emscripten js libraries I'd say it's theoretically possible to reproduce again. Do you know how to run all tests with Array.prototype modification as their prefix?

**Pull request merged**
