### PR TITLE
Update embind to work with the Closure Compiler

### PR DESCRIPTION
**Pull request by rharkeadsk**
We discovered that certain parts of embind do not work when the code is run through the Closure Compiler (`--closure 1`). Several names within the embind JavaScript itself need to be guarded from name
mangling in the Closure Compiler.

The existing tests would be sufficient to detect this case, except that they were never being run with the Closure Compiler enabled. This pull request also updates `other.test_embind` to run a pass with the Closure Compiler enabled.

Because the tests were never designed to themselves be Closure'd, I updated the test to manually append the tests and the test adapter to the output JavaScript, instead of using `--post-js`. We considered updating the tests themselves to be Closure'able, but that turned into a minor nightmare- I think this way is better, but if you feel otherwise please let me know. We would be happy to finish that work if it is the preferred road forward.

Small updates were also needed to the test adapter to make it work- it was relying on the `assert` function from Emscripten, and now needs to create its own object rather than appending to it.

### CODE REVIEW

**Comment by rharkeadsk** [comment]
Any update on this?

**Comment by chadaustin** [comment]
Sorry for the delay.  I think I meant to merge this but didn't.  Thanks again!

**Comment by kripken** [comment]
Wait, are we decided on all the issues here? In particular, look at the size of the diff on `embind.test.js` - is the new version there (with more quotes) how you expect embind to be used?

**Comment by chadaustin** [comment]
Good point.  I didn't see the embind.test.js changes because the github PR diff UI hid them for some reason.  Yes, those are not necessary - you don't need to run closure on your tests.  I can revert that single file.

**Comment by chadaustin** [comment]
I reverted the changes to embind.test.js in 36cd7a4c79b2af61951c64ddf4be71b476f2bcae

**Comment by kripken** [comment]
LLVM 3.5 has been merged to incoming. This has a known issue with embind which might mask breakage caused by that revert (see https://github.com/kripken/emscripten-fastcomp/issues/51 ). To test the revert, can use master branches + the revert commit.

**Comment by kripken** [comment]
Fix for that known issue has been pushed. The breakage from that revert is unmasked, i.e., can just run `tests/runner.py other.test_embind` to see it, on incoming.

**Comment by chadaustin** [comment]
My changes in 36cd7a4 broke tests, so I had to rework them in 36cd7a4c79b2af61951c64ddf4be71b476f2bcae.  Now the tests are appended after compilation so that closure compiler does not run on them.

**Pull request merged**
