### PR TITLE
Fix all DeprecationWarning: invalid escape sequence

### PR DESCRIPTION
**Pull request by BoboTiG**
Hello,

This is a sanitization patch for Python sources. Those `DeprecationWarnings` are already converted to `SyntaxWarning` in Python 3.8 and will become `SyntaxError` in Python 4.0.

Signed-off-by: Mickaël Schoentgen <contact@tiger-222.fr>

### CODE REVIEW

**Comment by kripken** [comment]
Thanks @BoboTiG!

First thing, please take a look at the CI errors (none of them look random/intermittent, they look real). Also please add yourself to AUTHORS.

**Comment by BoboTiG** [comment]
@kripken: it is now fixed :)

**Comment by kripken** [comment]
Thanks @BoboTiG!

@sbc100 , maybe you can take a look at these python changes, you know this stuff better than me?

**Comment by kripken** [comment]
Thanks @BoboTiG and @sbc100!

**Pull request merged**
