### PR TITLE
Simplify extract_archive_contents

### PR DESCRIPTION
**Pull request by sbc100**
ar files can only contain basenames so we don't need to
worry about the case where the stored files live in
sub-directory.

Remove the finally for setting cwd and replace with
`cwd=` argument to the run_process.

Remove the try/catch and simply have ar failures be
hard failures.

### CODE REVIEW

**Comment by sbc100** [comment]
I did an experiment trying add directory names to an ar file.. it seems it can't be done with GNU `ar` or `llvm-ar`.  If you add `foo/bar.o` , `bar.o` and `foo2/bar.o`.. both tools will create an archive that contains 3 files all called `foo.o`.

Maybe there is some variant that supports more than just basenames.. but I have not found it, and also that whole point of `emar` is to de-dup based on basename alone.

**Comment by juj** [comment]
The code to handle subdirectories was added at https://github.com/kripken/emscripten/commit/b7ce870dd4b1352e308e212e77cd6161c1ec904e a long time ago. It looks like code that was added for a reason after observing subdirectories occurring, not something that would have been added pre-emptively for a "perhaps this might happen". I feel cautious about this PR - it's great to clean up, although this might be a bit dangerous, and the gain might not be that big here? (systemic complexity is not going down much)

I wonder what Windows `llvm-ar`/`mingw32-ar` would do?

**Comment by sbc100** [comment]
I agree it seems strange that the code was added if its not possible create such archives... I'll sit on this PR for a while and do little more investigating. 

I could always re-add the sub-directory handling, but I like the part of this change that removes the `catch` and the `finally`.   It makes me happy to be able to remove a `catch all` block like this.

**Comment by kripken** [comment]
Looking in the history there, that set of commits was in response to llvm-ld being deprecated, and I wrote a bunch of linking code to replace it for what we needed. I do have a clear memory of needing to handle absolute paths, and not doing it for theoretical reasons (hence the handling of error conditions like missing directory names), but I'm afraid I can't remember any more details.

I wonder if llvm-ar changed it's behavior since 2012? Or as @juj said, perhaps this was on windows or some other less common case. Perhaps some build systems have their own `.a` handling code?

**Comment by sbc100** [comment]
In theory anyway, emscripten only supports .a files that have been made with in `emar`.   You might get away with using the system `ar` but system `ar` doesn't have the special handling for duplicate basenames that we have in `emar`. 

In fact the `emar` wrapper probably would not been needed at all if `ar` files could store directory names.

**Comment by kripken** [comment]
Good point, the emar wrapper does imply that.

Overall, I guess I'm not too worried about this landing, but we should watch for bug reports that indicate we missed something here, and we can revert if we need.

**Pull request merged**
