### PR TITLE
Also build bc files for .a libraries in embuilder

### PR DESCRIPTION
**Pull request by kripken**
They are needed when forcing a system lib (we want all the code to always be linked in that case). See #5638

### CODE REVIEW

**Comment by dschuff** [comment]
Would it make more sense to change the linker to just include all archive members in some cases (i.e. implement the `--whole-archive` linker flag) rather than to have libraries in 2 different kinds of formats?

**Comment by kripken** [comment]
That's another reasonable option, yeah. But the linker logic is already kind of complex right now, so I'd prefer to not modify it, and we already have logic to use .bc files as needed, the only piece missing was embuilder - so out of the reasonable options, this seems the simplest to me.

**Comment by kripken** [comment]
Any objections to landing this?

**Comment by dschuff** [comment]
I mean, I guess I object to the fact that we have both .bc files and .a files at all, but given that, I guess this PR is ok. The way forward is just to replace it all with lld anyway :D

**Comment by kripken** [comment]
Yeah, if we can use lld eventually for all of linking that would be better of course.

**Pull request merged**
