### PR TITLE
allowing embind and wasm to play nicely with each other.

### PR DESCRIPTION
**Pull request by walkingeyerobot**
As far as I can tell, when compiling to wasm, embind works just fine without dynamic execution.

### CODE REVIEW

**Comment by kripken** [comment]
I don't know enough about embind myself, but first thing I would check for this is to run `tests/runner.py ALL.test_embind*` and ``tests/runner.py other.test_embind*`. If embind uses dynamic execution, that should find where.

**Comment by kripken** [comment]
Good, thanks for the update.

@AlexPerrot, do you know if embind needs dynamic execution?

**Comment by AlexPerrot** [comment]
I'd say it doesn't.
The only mention of `eval` I could find is in a comment in emval.js.
I ran the embind tests with `-s NO_DYNAMIC_EXECUTION=1` and everything passes.

**Comment by kripken** [comment]
Thanks @AlexPerrot. Ok, then yeah, please remove that assertion @walkingeyerobot, looks like it's out of date. I suspect when we updated embind for asm.js we removed some dynamic execution (or maybe at some other time), and forgot that assert.

**Comment by kripken** [comment]
Thanks!

**Pull request merged**
