### PR TITLE
benchmark_matrix_multiply

### PR DESCRIPTION
**Pull request by juj**
Add benchmark for matrix multiplication.

Wrote this one to experiment with what the performance effects are for doing lots of work in single event tick, or when distributing the same work across multiple event ticks. Added as a benchmark to the benchmark suite.

### CODE REVIEW

**Comment by kripken** [comment]
Hmm, why would it matter how it is distributed across runs of the event loop? Or is the benchmark testing browser event loop timings, and not the pure computation itself?

**Comment by juj** [comment]
The benchmark is testing that exactly, i.e. does it matter how code is distributed across event loops? There was a hypothesis that processor power management API flags would affect performance depending on how much one does per iteration.

**Comment by kripken** [comment]
Got it, lgtm. Do we need it in the shell, though? Seems like it's only useful in the browser.

**Comment by juj** [comment]
We don't currently have an infrastructure to run benchmarks in the browser, and I wanted to somehow hook this to be run. Granted, in this mode it's not running through the test that I was benchmarking it for, but good to not have "disconnected" files lying around in the `tests/` directory.

**Pull request merged**
