### PR TITLE
async_wget2 and async_wget2_data additionalHeaders argument

### PR DESCRIPTION
**Pull request by jpx**
Update async_wget2 and async_wget2_data to allow passing additional headers to http requests.
Add support for range response status 206 to async_wget2_data.

The aim is primarily to support http ranges with 'GET' requests.

### CODE REVIEW

**Comment by warrenseine** [comment]
Raising the issue as we're still using the proposed patch in our Emscripten version and I'd love to have the HTTP request functions upgraded as proposed by @juj or @emmanuel-goldstein.

I think that would be even better if we could simply make a cURL library port that works in the browser. The cURL API is not really the most beautiful piece of engineering out there, but we can safely assume it's doing its job fine.

In our codebase, we have an HTTP loader that uses cURL or `emscripten_wget*` based on the EMSCRIPTEN macro. I suppose almost everyone does.

**Comment by warrenseine** [comment]
Should we turn this invalid PR into an issue?

**Comment by kripken** [comment]
Supporting the cURL API seems like a reasonable solution here. If it's straightforward, we could do that in a js library.

**Comment by warrenseine** [comment]
We haven't had time to implement `libcurl.js`, which, I agree, is the ideal solution here.

We're still using this patch to send headers when Emscripten HTTP requests and we'd like to have it in the standard API. What can we do to get this accepted? Is breaking the API tolerable? Or should we propose `emscripten_async_wget3_data`?

**Comment by kripken** [comment]
I'd rather not have 2,3,etc. versions of all APIs. Perhaps we can figure out a single API that is extensible? Although I can't think of how.

Btw, can you just use an `EM_ASM` block for this, and write arbitrary xhr-using code? Perhaps we could make `EM_ASM` easier to use for things like this, as another way to improve this.

**Comment by warrenseine** [comment]
In the end, I chose to go with `emscripten_async_wget3_data` custom function based on `emscripten_async_wget2_data` (code similar to the PR here) and link it with a `--js-library` parameter.

It works fine in our use case and doesn't need any maintenance or merge into Emscripten. Hopefully, #3270 will remove the need for this.

@jpx Should we close this?

**Comment by jpx** [comment]
Yes, great, we shall close the issue.

**Pull request closed without merging**
