### PR TITLE
Process ports even if not linking their contents

### PR DESCRIPTION
**Pull request by kripken**
As they also set up the settings (e.g., the bin dir of binaryen). This fixes building the port automatically when compiling a wasm side module.

### CODE REVIEW

**Comment by kripken** [comment]
Pushed another commit to lock over the download of ports too, as this PR may cause us to do that a little earlier, and we already had an annoyance with that, see #5111. This mostly resolves that issue, it makes us lock in order to both download and build, which really seems like the right behavior anyhow.

**Comment by dschuff** [comment]
This problem (bin dir of binaryen) is a good example of why Binaryen probably shouldn't be a port like the target libraries.

**Comment by kripken** [comment]
Yeah, maybe it shouldn't be a port...

Meanwhile I see this has some issues, it breaks `sanity.test_emcc_ports`. I'll need to find time to look at this more carefully.

**Comment by kripken** [comment]
I rewrote and simplified this after understanding the test failures. I think this is a better approach:

 * We process ports for side modules, and not all the time. This is a smaller change than suggested before, and it makes sense in that side modules are "final executables", they are not intermediate object files. So with this PR we process ports for final executable things, which includes js and html and side module outputs; but for side modules, we don't link in any libraries from ports. And the PR adds a test for side modules using ports.
 * Add a cache lock for fetching ports. This fixes #5111 and reduces the risk of the previous bullet point change causing regressions.

**Comment by kripken** [comment]
Actually there might be a better way to do this. Still a wip.

**Comment by kripken** [comment]
Ok, this should be the right approach,

 * Add a way to manually get a port.
 * Use that to get the binaryen port when compiling to wasm.
 * Lock on fetching ports (fixing #5111).

**Comment by kripken** [comment]
* also makes it possible to remove some old emcc.py code for getting binaryen set up (now that we get the port at the right time, it does all that)

**Comment by saschanaz** [comment]
I pushed a commit to always use latest binaryen bits.

One question BTW. I get libc and wasm-libc together when testing `test_legalize_js_ffi`, is this expected behavior?

```
INFO:root:generating system asset: is_vanilla.txt... (this will be cached in "/home/saschanaz/.emscripten_cache/is_vanilla.txt" for subsequent builds)
INFO:root: - ok
WARNING:root:use EM_ALL_ENGINES=1 in the env to run against all JS engines, which is slower but provides more coverage
Test suites:
['test_other']
Running test_other: (1 tests)
test_legalize_js_ffi (test_other.other) ... ['-s', 'LEGALIZE_JS_FFI=1', '-s', 'SIDE_MODULE=1', '-O2']
/usr/bin/python2 /mnt/c/Users/sasch/Documents/GitHub/emsdk/emscripten/incoming/emcc /mnt/c/Users/sasch/Documents/GitHub/emsdk/emscripten/incoming/tests/other/ffi.c -s WASM=1 -g -o a.out.js -s LEGALIZE_JS_FFI=1 -s SIDE_MODULE=1 -O2
WARNING:root:(Emscripten: settings file has changed, clearing cache)
INFO:root:(Emscripten: Running sanity checks)
WARNING:root:BINARYEN_ASYNC_COMPILATION disabled due to user options. This will reduce performance and compatibility (some browsers limit synchronous compilation), see https://github.com/kripken/emscripten/wiki/WebAssembly#codegen-effects
INFO:root:generating port: binaryen_tag_version_39.txt... (this will be cached in "/home/saschanaz/.emscripten_cache/asmjs/binaryen_tag_version_39.txt" for subsequent builds)
INFO:root:building port: binaryen
INFO:root: - ok
['-s', 'LEGALIZE_JS_FFI=0', '-s', 'SIDE_MODULE=1', '-O2']
/usr/bin/python2 /mnt/c/Users/sasch/Documents/GitHub/emsdk/emscripten/incoming/emcc /mnt/c/Users/sasch/Documents/GitHub/emsdk/emscripten/incoming/tests/other/ffi.c -s WASM=1 -g -o a.out.js -s LEGALIZE_JS_FFI=0 -s SIDE_MODULE=1 -O2
['-s', 'LEGALIZE_JS_FFI=0', '-s', 'SIDE_MODULE=1', '-O0']
/usr/bin/python2 /mnt/c/Users/sasch/Documents/GitHub/emsdk/emscripten/incoming/emcc /mnt/c/Users/sasch/Documents/GitHub/emsdk/emscripten/incoming/tests/other/ffi.c -s WASM=1 -g -o a.out.js -s LEGALIZE_JS_FFI=0 -s SIDE_MODULE=1 -O0
['-s', 'LEGALIZE_JS_FFI=0', '-s', 'SIDE_MODULE=0', '-O0']
/usr/bin/python2 /mnt/c/Users/sasch/Documents/GitHub/emsdk/emscripten/incoming/emcc /mnt/c/Users/sasch/Documents/GitHub/emsdk/emscripten/incoming/tests/other/ffi.c -s WASM=1 -g -o a.out.js -s LEGALIZE_JS_FFI=0 -s SIDE_MODULE=0 -O0
INFO:root:generating system library: dlmalloc_debug.bc... (this will be cached in "/home/saschanaz/.emscripten_cache/asmjs/dlmalloc_debug.bc" for subsequent builds)
INFO:root: - ok
INFO:root:generating system library: libc.bc... (this will be cached in "/home/saschanaz/.emscripten_cache/asmjs/libc.bc" for subsequent builds)
INFO:root: - ok
INFO:root:generating system library: wasm-libc.bc... (this will be cached in "/home/saschanaz/.emscripten_cache/asmjs/wasm-libc.bc" for subsequent builds)
INFO:root: - ok
warning: unresolved symbol: import_f
warning: unresolved symbol: import_ll
ok

----------------------------------------------------------------------
Ran 1 test in 945.159s

OK
```

**Comment by saschanaz** [comment]
`test_simd_sitofp` still fails but this anyway requires new fastcomp tag.

**Comment by kripken** [comment]
Yes, libc is the main musl libc, and wasm-libc is additional parts we use in wasm (but not asm.js).

**Comment by kripken** [comment]
Oh, and nice addition @saschanaz , with that we now have `other` tests passing, so we should probably merge this in soon. But waiting to see if anyone wants to review.

Btw, `other` does hit the travis time limit now and then. I wonder if we should split it up, or perhaps look for old/obsolete tests to remove.

**Comment by kripken** [comment]
Merging this in since more reports of hitting this bug are arriving. Comments still welcome later of course.

**Comment by saschanaz** [comment]
>Btw, other does hit the travis time limit now and then.

Building binaryen takes some time. We may split binaryen-required tests to save time.

**Comment by kripken** [comment]
> Building binaryen takes some time. We may split binaryen-requiring tests to save time.

Good idea.

**Pull request merged**
