### PR TITLE
Improve documentation for addFunction

### PR DESCRIPTION
**Pull request by aheejin**
Currently the bullet points do not show up correctly (one bullet per
line) and the test file is not hyperlinked. Fixed them.

### CODE REVIEW

**Comment by aheejin** [comment]
By the way I don't know how to preview what to appear in [here](https://kripken.github.io/emscripten-site/docs/porting/connecting_cpp_and_javascript/Interacting-with-code.html#calling-javascript-functions-as-function-pointers-from-c). Is there any way?

**Comment by jgravelle-google** [comment]
```
cd emscripten/site
make html
```
You need sphinx which I think you can apt-get install. The makefile in there I think looks reasonable.
Do we have doc-building docs? :grin:

**Comment by aheejin** [comment]
Thanks! Do you have any idea why the link to `tests/interop/test_add_function_post.js` does not work? Other links to files have the underscore attached to it so I did it to, but I don't know why this does not work...

**Comment by jgravelle-google** [comment]
No idea! I've only made one documentation change and that was basically copy neighboring syntax and tweak it till it seemed fine.

**Comment by aheejin** [comment]
The link is now working, PTAL.

**Comment by jgravelle-google** [comment]
Oh hey it works in GitHub's "rich diff" from the diff page, which makes me a lot more confident that yes that fixes it :D

**Comment by aheejin** [comment]
Thanks! I didn't know that. By the way the link was not actually working; I only specified the relative path with respect to the emscripten repo before and that doesn't work. I'll think this as still lgtm merge it.

---

More unimportant details:
```
`tools/system_lib.py`_
```
This relative link format works for *.py files in `tools/` directory, but not with the file I'm trying to link.
```
`tests/interop/test_add_function_post.js`_
```
So this didn't work.

So I googled the syntax and changed it that now the link is wrapped in `<>`
```
`<tests/interop/test_add_function_post.js>`_
```
But now link is considered as relative to this rst file, not the emscripten repo. Actually this is natural but I don't know why it worked ok relative to the repo for `tools/system_libs.py` in the same file.
Anyway so I changed it to the full address.

**Pull request merged**
