### PR TITLE
Update to libc++ 6.0

### PR DESCRIPTION
**Pull request by pweiskircher**
Trying to get C++17 working in our project and ran into the same problem of not finding `std::byte` as in #6580.

I basically just took the new libc++ sources, copied them in and modified a couple of places that were marked as `// XX EMSCRIPTEN` before.

`python test/runner.py` succeeded without failures.
`python test/runner.py other` had one failure:

```
======================================================================
FAIL: test_llvm_lit (test_other.other)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/Cellar/python@2/2.7.15/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/Users/pat/PSPDFKit-Core-WASM/emsdk/emscripten/incoming/tests/test_other.py", line 3552, in test_llvm_lit
    assert p.returncode == 0, 'LLVM tests must pass with exit code 0'
AssertionError: LLVM tests must pass with exit code 0

----------------------------------------------------------------------
```

Judging from #5415 this shouldn't actually be a problem!

### CODE REVIEW

**Comment by pweiskircher** [comment]
I also just ran our own test-suite (we have a pretty big code-base and test-suite here at PSPDFKit) and it all seems to work great so far!

**Comment by kripken** [comment]
Thanks for submitting this! :)

The `lit` error can be ignored, yeah. That means you don't have llvm-lit installed. But a PR like this can't influence those tests, so no need to bother.

About `wcsftime`, that is in musl's `time/` subdir, which we don't build (we have our own date/time impl in JS, for easier integration with JS data/time methods). If we want to add that, both routes are possible - either implementing in JS like the others if simple enough like them, or build it from musl otherwise.

**Comment by pweiskircher** [comment]
I’m not sure what to do about the `wcsftime` issue, to be honest. Seems like the emscripten tests and our own tests run just fine and I’m honestly not quite sure why that warning popped up now. 

From a quick glance at the old and new libc++ sources it doesn’t seem like any new usage of `wcsftime` were added. 

I guess I’ll defer to your judgement on this if you don’t mind :)

**Comment by pweiskircher** [comment]
I just checked our previous CI builds and wouldn’t you know, we had the `wcsftime` error before as well. Sorry for all my ramblings! It’s all good. 

Thanks for taking a look at this this quickly and being very helpful, I appreciate it!

**Comment by kripken** [comment]
Good to know about that warning, thanks for the update!

**Comment by pweiskircher** [comment]
Thanks for merging so quickly! Now we can move all our development to C++17 :)

**Pull request merged**
