### PR TITLE
update quotation docs, mention OS X needs outer quoting [ci skip]

### PR DESCRIPTION
**Pull request by kripken**
From the recent mailing list discussion.

### CODE REVIEW

**Comment by kripken** [comment]
Added a faq entry for the runtime change too.

**Comment by saschanaz** [comment]
OS X is [now named macOS](https://www.apple.com/macos/high-sierra/) so we probably should call it macOS.

BTW, is that because the behavior of bash is different in Linux and macOS (I don't know it is), or because the user was using another shell?

**Comment by kripken** [comment]
Updated to `macOS`, thanks.

Not sure about the quoting differences. It would be good to hear from more people on more systems, I guess.

**Comment by kripken** [comment]
Let's merge this in and update the docs with the other recent changes. We can improve this further as we go, but I think it's already an improvement.

**Pull request merged**
