### PR TITLE
GLFW2 Keycode Support

### PR DESCRIPTION
**Pull request by CliffyA**
The key codes for special characters seems to have changed between GLFW2 and GLFW3.
This change corrects the key codes so they work correctly in GLFW2 builds.

### CODE REVIEW

**Comment by kripken** [comment]
Thanks, looks good!

1. Please add yourself to AUTHORS
2. I'm not sure how much testing we have for this already, but let's add a little to verify at least one of the keys that differ. Can look in `tests/test_browser.py` if this might be easy to add to an existing test (perhaps `glfw3_events`).
3. In the future please make pulls to the incoming branch. Although I think in this area, there have been no recent changes so it should be fine.

**Comment by CliffyA** [comment]
1. I'm already in AUTHORS from a year or so ago.
2. I've converted glfw3_events into glfw_events to handle both versions, and added some random key press checks.
3. Sorry about commuting to the wrong branch. I'll remember that for next time.

Thanks,
Adam

**Comment by kripken** [comment]
Oh, sorry about AUTHORS, I forgot and I only searched for "CliffyA" ;)

**Comment by kripken** [comment]
Looks good on the testing. I believe you also need to update the existing tests looking for that `glfw3_` file, in `test_browser.py` and/or `test_interactive.py`?

**Comment by CliffyA** [comment]
Yep I wouldn't have expected you to remember a little commit I made a year ago.
Sorry about missing test_browser.py, I've not used Git much.

**Comment by kripken** [comment]
Thanks, merged to incoming.

**Pull request closed without merging**
