### PR TITLE
Fix inlining bug

### PR DESCRIPTION
**Pull request by aheejin**
Currently INLINING_LIMIT option does not do anything for clang. (And in
opt, emcc only checks whether it is 0 or not, so the limit number given
actually does not matter unless it is 0.)
So we give -O2, clang inlines short functions even if INLINING_LIMIT is
nonzero. This patch fixes this bug.

### CODE REVIEW

**Comment by aheejin** [comment]
@dschuff

**Comment by dschuff** [comment]
WRT the name of the option and the non-zeroness, I would guess that maybe the intention was to pass it through to LLVM's `-inline-threshold` flag, but we probably don't want to be exposing that directly to users since it's an internal flag that might go away. Interestingly, there are several tests that set the limit to 25 or 50, so maybe we should make those reflect the reality. Maybe @kripken knows more about the intention of those, but this change looks good; if the user wants to set the limit to 0, I think `-fno-inline-functions` has the right behavior in clang. We might want to add something to `test_core.py` though. Maybe a small program that we compile with `O2` but set INLINING_LIMIT to 0 and check that the output has a definition for the function?

Also was this causing some kind of bug or failure that you observed?

**Comment by kripken** [comment]
This looks like a good fix, thanks. I agree with @dschuff we should test it. Perhaps in `tests/test_other.py`. `test_emcc` has some related things, in fact, including using `INLINING_LIMIT`.

Please run the tests locally, at least `python tests/runner.py other`. I don't expect a problem, but this is a nontrivial change.

**Comment by aheejin** [comment]
@jpporto

**Comment by aheejin** [comment]
I found this bug while testing the wasm exception handling routine. test_exceptions_white_list_2 in test_core.py does not run because of this bug, when running with 'binaryen2' setting (which uses -O2).
 There are two functions, nocatch and main, and that test expects only main function to catch the exception and not nocatch. But nocatch is called from main and thus inlined to main function, and later removed by a dce pass.

So, do we need another test in test_other for this?

**Comment by kripken** [comment]
Yes, I think another test is warranted - this causes a noticeable change in frontend behavior, i.e., when compiling C++ to bitcode, it leads to different bitcode. We should test that directly (e.g. using `llvm-nm` to see if the method is in the bitcode).

**Comment by dschuff** [comment]
Oops, I typed the following but failed to click the green button:

I still think it would be useful to have a specifically-targeted test. More small targeted tests is usually better; e.g. the exception tests test a pretty nontrivial behavior and if it were to regress because of the inlining thing it might not be obvious why; but a test that specifically tests the inlining behavior would be clearer.  (so yeah, using llvm-dis or llvm-nm would be ideal if there's a good way to do that from the test driver)

**Comment by aheejin** [comment]
@kripken Is there a way to run an arbitrary tool (like llvm-nm) using runner.py? I can't find any. I can add a method to runner.py, like run_tool, though. Do you think it is a good idea?

**Comment by dschuff** [comment]
It looks like several tests use `Building.llvm_nm()`

**Comment by aheejin** [comment]
@kripken Many tests fail in test_other.py even without my changes. Is this expected?

**Comment by kripken** [comment]
@aheejin: yes, that's common, sorry about that. Stuff like crunch and java are depended on in some of the tests, for example. We also have one or two failures on incoming on temp files not being cleaned up (that @juj is fixing right now). Anything aside from those, however, might be suspicious - is there anything else?

**Comment by aheejin** [comment]
asm.js

ERROR: test_EMCC_BUILD_DIR (test_other.other)
ERROR: test_circular_libs (test_other.other)
ERROR: test_crunch (test_other.other)
ERROR: test_embind (test_other.other)
ERROR: test_identical_basenames (test_other.other)
ERROR: test_implicit_func (test_other.other)
ERROR: test_js_link (test_other.other)
ERROR: test_llvm_lit (test_other.other)
ERROR: test_no_dynamic_execution (test_other.other)
ERROR: test_prepost (test_other.other)
ERROR: test_prepost2 (test_other.other)
ERROR: test_realpath_nodefs (test_other.other)
ERROR: test_sixtyfour_bit_return_value (test_other.other)
ERROR: test_warn_undefined (test_other.other)
FAIL: test_emcc_multiprocess_cache_access (test_other.other)
FAIL: test_no_missing_symbols (test_other.other)
FAILED (failures=2, errors=14)


wasm

ERROR: test_EMCC_BUILD_DIR (test_other.other)
ERROR: test_EXPORTED_RUNTIME_METHODS (test_other.other)
ERROR: test_autovectorize_linpack (test_other.other)
ERROR: test_canonicalize_nan_warning (test_other.other)
ERROR: test_circular_libs (test_other.other)
ERROR: test_cmake (test_other.other)
ERROR: test_crunch (test_other.other)
ERROR: test_cyberdwarf_pointers (test_other.other)
ERROR: test_cyberdwarf_union (test_other.other)
ERROR: test_dangerous_func_cast (test_other.other)
ERROR: test_dash_g (test_other.other)
ERROR: test_debug_asmLastOpts (test_other.other)
ERROR: test_emcc (test_other.other)
ERROR: test_emterpreter_advise (test_other.other)
ERROR: test_emulated_function_pointers (test_other.other)
ERROR: test_emulated_function_pointers_2 (test_other.other)
ERROR: test_eval_ctors (test_other.other)
ERROR: test_export_in_a (test_other.other)
ERROR: test_failing_alloc (test_other.other)
ERROR: test_freetype (test_other.other)
ERROR: test_js_link (test_other.other)
ERROR: test_libpng (test_other.other)
ERROR: test_link_memcpy (test_other.other)
ERROR: test_link_s (test_other.other)
ERROR: test_llvm_lit (test_other.other)
ERROR: test_locale_wrong (test_other.other)
ERROR: test_meminit_crc (test_other.other)
ERROR: test_merge_pair (test_other.other)
ERROR: test_minimal_dynamic (test_other.other)
ERROR: test_no_missing_symbols (test_other.other)
ERROR: test_nosplit (test_other.other)
ERROR: test_only_force_stdlibs_2 (test_other.other)
ERROR: test_only_my_code (test_other.other)
ERROR: test_os_oz (test_other.other)
ERROR: test_prepost (test_other.other)
ERROR: test_prepost2 (test_other.other)
ERROR: test_realpath_nodefs (test_other.other)
ERROR: test_sixtyfour_bit_return_value (test_other.other)
ERROR: test_split_memory (test_other.other)
ERROR: test_split_memory_2 (test_other.other)
ERROR: test_split_memory_faking (test_other.other)
ERROR: test_split_memory_release (test_other.other)
ERROR: test_split_memory_sbrk (test_other.other)
ERROR: test_split_memory_use_existing (test_other.other)
ERROR: test_switch64phi (test_other.other)
ERROR: test_vorbis (test_other.other)
ERROR: test_warn_no_filesystem (test_other.other)
ERROR: test_warn_undefined (test_other.other)
ERROR: test_zeroinit (test_other.other)
FAIL: test_aliased_func_pointers (test_other.other)
FAIL: test_asm_minify (test_other.other)
FAIL: test_autovectorize_bullet (test_other.other)
FAIL: test_bad_function_pointer_cast (test_other.other)
FAIL: test_debuginfo (test_other.other)
FAIL: test_demangle (test_other.other)
FAIL: test_embind (test_other.other)
FAIL: test_emcc_c_multi (test_other.other)
FAIL: test_emcc_cache_flag (test_other.other)
FAIL: test_emcc_debug_files (test_other.other)
FAIL: test_emcc_multiprocess_cache_access (test_other.other)
FAIL: test_emterpreter_file_suggestion (test_other.other)
FAIL: test_exclude_file (test_other.other)
FAIL: test_export_all (test_other.other)
FAIL: test_f0 (test_other.other)
FAIL: test_global_inits (test_other.other)
FAIL: test_incorrect_static_call (test_other.other)
FAIL: test_libcxx_minimal (test_other.other)
FAIL: test_llvm_lto (test_other.other)
FAIL: test_module_exports_with_closure (test_other.other)
FAIL: test_native_optimizer (test_other.other)
FAIL: test_no_dynamic_execution (test_other.other)
FAIL: test_no_exit_runtime (test_other.other)
FAIL: test_no_filesystem (test_other.other)
FAIL: test_no_nuthin (test_other.other)
FAIL: test_only_force_stdlibs (test_other.other)
FAIL: test_outline (test_other.other)
FAIL: test_require (test_other.other)
FAIL: test_simplify_ifs (test_other.other)
FAIL: test_static_syscalls (test_other.other)
FAIL: test_symbol_map (test_other.other)
FAIL: test_toobig (test_other.other)
FAIL: test_warn_toomany_vars (test_other.other)
FAIL: test_warn_unaligned (test_other.other)
FAILED (failures=34, errors=49)


I haven't looked at the causes of errors, but these seem more than you said. I attached logs of running the tests. Tests are run without my change.

other_asm_out.txt: asm.js / stdout
other_asm_err.txt: asm.js / stderr
other_wasm_out.txt: wasm / stdout
other_wasm_err.txt: wasm / stderr

[other_asm_err.txt](https://github.com/kripken/emscripten/files/412004/other_asm_err.txt)
[other_asm_out.txt](https://github.com/kripken/emscripten/files/412005/other_asm_out.txt)
[other_wasm_err.txt](https://github.com/kripken/emscripten/files/412006/other_wasm_err.txt)
[other_wasm_out.txt](https://github.com/kripken/emscripten/files/412003/other_wasm_out.txt)

**Comment by kripken** [comment]
Are the `_asm` tests run normally, and the `_wasm` tests forced to use the wasm backend using the env var (or some other method)?

I would expect many failures when forcing to wasm, as some of the tests look in the asm.js output, for example. We'd need to disable or update those tests for wasm, I suppose.

But the asm failures look very surprising. What's the output from, say, `./tests/runner.py other.test_no_missing_symbols`, with and without `EMCC_DEBUG=1` in the env?

**Comment by aheejin** [comment]
Which JavaScript engine are these tests supposed to run with?
I was using d8, and I don't know how to print to stderr in d8. Several tests are checking stderr output, and d8 is not printing anything to stderr, and this looks like the cause of failure for many tests.

**Comment by kripken** [comment]
node.js is what is guaranteed to work. SpiderMonkey shell should also work (it supports stderr using `console.warn`, perhaps d8 does too?).

**Comment by aheejin** [comment]
With node/asm.js, as you said, only two of the tests fail. With spidermonkey/asm.js, like 7~8 tests fail (I don't remember the exact number). But with wasm, dozens of tests fail.
I added a test, and it does not break any more tests than it currently does.

p.s I merged this branch with the incoming one by mistake and I guess the notification got sent that dozens of files have been changed. I reset all those unrelated commits now, sorry.

**Comment by kripken** [comment]
Looks great, thanks.

I don't think you've added yourself to the AUTHORS file yet, can you please do that?

**Comment by kripken** [comment]
Thanks. Is this ready to merge? Or will the test not work yet because of the `nm` issue?

**Comment by aheejin** [comment]
The test will not work yet because of the nm issue.

**Pull request merged**
