### PR TITLE
Fixed conflict in window.id when handling events on window and compiling with --closure 1

### PR DESCRIPTION
**Pull request by SBRK**
With --closure 1 some Emscripten classes and functions would sometimes be renamed to window.id. When handling events on window (for example focus, blur, etc) with Emscripten, it would try to write event.target.id, expecting it to be a String, and would fail if window.id was assigned to something else.
Problem described in issue #4122

### CODE REVIEW

**Comment by kripken** [comment]
As @juj's said in the original issue, can we just quote the accesses? That is how we usually resolve these.

We should also add a test for this. We do have tests for most or all of the html5 apis, so perhaps we just need to add that we run them in closure as well.

**Comment by SBRK** [comment]
I don't see how it would help, it would still return an object instead of a string. The typeof test would still be needed.

**Comment by kripken** [comment]
I think I don't understand the problem, then. Can you please add a test to this pull (which we should have anyhow), of something that would fail without this fix? That would make it concrete and easy to understand.

**Comment by SBRK** [comment]
I see @juj pushed that a few weeks ago : 
https://github.com/emscripten-ports/SDL2/pull/7/files

This is the exact reason why we had to listen to the blur/focus events on window (preventing stuck keys/mouse down when leaving the tab or window) and that's the when the problem would happen.
Didn't you run in the problem I had @juj ?

I realise now I forgot to say we have this problem on Chrome (48), and I think it was not happening on Firefox.

**Comment by kripken** [comment]
I standalone testcase using just the HTML5 API (which is what this pull modifies) would be very helpful here, I'm not sure I understand the connection to SDL2.

**Comment by SBRK** [comment]
There is no connection to SDL per se, but the fix this guy did on SDL2 uses `emscripten_set_focus_callback` with `#window`, which is the case in which the error I fixed occurs.
I'll work on a test.

**Comment by SBRK** [comment]
I added a test, with which you'll clearly see the problem (I hope :D).
If you run the test browser.test_window_focus without the fix on Chrome, you'll see an exception (and the `a.charCodeAt is not defined` error). With the fix, no exception.

**Comment by kripken** [comment]
I still don't see the problem. I tried running that test on Chrome 46. Perhaps this is a Chrome regression between 46 and 48? We should check. (I can't run later versions of Chrome on this machine, it seems - no more 32-bit linux builds?)

It seems odd it would be a regression, though - I can't think what in the fix here would change on different Chrome versions?

**Comment by SBRK** [comment]
Regression or not, using "id" on window has no sense, since window can't have an id, and calling charCodeAt on a function or an object should rightfully fail.

**Comment by kripken** [comment]
I guess I'm not sure what these ids are. @juj, are they ids that the HTML5 library adds to elements? Or are they part of the web?

**Comment by SBRK** [comment]
They're the DOM elements id. `window` isn't supposed to have an id, but compiling with closure creates objects and function in `window`, starting with a, b, c, ... aa, ab, ac, ... id

**Comment by kripken** [comment]
Sorry, I'm still confused here. We never seem to write to `.id`, so how are we creating anything in `window`? Or did I misunderstand what you meant?

We don't read the `.id` field from window, either, but just from event objects?

Sorry if I'm missing something obvious here. @juj wrote the code here, and maybe I don't understand it yet.

**Comment by SBRK** [comment]
The closure does the .id, by rewriting the class names of the app.

**Comment by kripken** [comment]
Ok, I see now.

I think the best solution here is to not use `.id` ourselves as a property (on the global object where closure can collide with it). That way we won't hit closure collisions. Perhaps `ident` would be a reasonable name? @juj, this is your code, maybe there's an even better name?

**Comment by SBRK** [comment]
`id` is just the result of a naming pattern starting with a, b, c, d... aa, ab, ac, ... ia, ib, ic, id. So `ident` doesn't really make sense there.

And I don't think it should be renamed, since `window.id` is not a thing in javascript, because it is not a DOM element. It's just a matter of changing how the events are handled in the case they're on `window`

**Comment by kripken** [comment]
`ident` is long enough though that there is practically no chance of a collision. Two-letter names are risky in the global scope due to closure, and perhaps 3, but almost certainly not 4 or above.

I thought we can rename this since it's an internal thing we use, that we happen to write to `window`? But perhaps I am not understanding @juj's code?

**Comment by SBRK** [comment]
It's not an emscripten specific thing ! it's `id` as in DOM element `id`

**Comment by promethe42** [comment]
Guys, could we fix this? All of our builds now have tons of errors because of this `window["id"]` thing created when compiling with `--closure 1`. 

Closure creates object/functions in `window`. The name of those fields are generated, starting at `a`, then `b`.... `ab`, `bb`, etc... up to `id` in some cases (and presumably up to `zz` or more if needed). The problem is some emscripten code relies on the existence of the `id` field on DOM elements. So because of closure, windows.id exists despite it's not a DOM id.

@SBRK 's first commit check that the `id` field emscripten uses is actually a `string` (and not a closure generated object/function).

Maybe he should do a proper PR without the SDL stuff.

**Comment by kripken** [comment]
Closure might currently rename an object or a function to `id`, but it might also rename a number to it (since we do have number globals). So that wouldn't be a fully safe approach.

There should be a way to tell closure to not rename things to `id`. We can add that as a parameter when we call closure. I think that would be the safe solution here.

**Comment by promethe42** [comment]
> Closure might currently rename an object or a function to id, but it might also rename a number to it (since we do have number globals). So that wouldn't be a fully safe approach.

Emscripten expects `id` to be a string and the fix checks the `id` field is a string.
So I don't understand why Closure refactoring Number or any other type into the `id` field is an issue since the fix is about Emscripten expectation to find a String.

I guess we could also check that target is `window` to make the fix "stronger":

`var id = (e.target != window && e.target.id && (typeof e.target.id) == 'string') ? e.target.id : '';`

This way Emscripten will definitely never read the value set by Closure in `window.id`.

What do you think?

**Comment by kripken** [comment]
I meant to say that closure might rename a string global to `id`, so just checking for the type isn't enough. Checking for the `window` object can help, though, so I'm ok with that approach.

Sadly it does indeed look like closure can't be told not to rename object properties, only functions.

A more complete solution for a specific codebase though, would be to use `MODULARIZE` or otherwise not generate global variables in closure compiler mode 2.

**Comment by kripken** [comment]
Perhaps we should warn about this in closure mode 2, in fact.

**Comment by kripken** [comment]
This PR is quite old, closing. The testcase here no longer shows a problem, but I'm not sure if that means the issue was fixed. We can reopen this or open a new issue for discussion if necessary.

**Comment by ecotarobles** [comment]
This is still occuring.  Recently I had to fix my minified code with a post-processing step 

sed -i 's/id(/getPath(/g' <myfile.js> because of this generated code line in the minified file:

function id(a){for(var b;;){if(a===a.parent)return a=a.vf.bh,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function jd(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%dd.length}function Zc(a,b){var c;if(c=(c=kd(a,"x"))?c:a.$e.lookup?0:2)throw new M(c,a);for(c=dd[jd(a.id,b)];c;c=c.Ch){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.$e.lookup(a,b)}

The "function id(...)" collides with the id property of elements (https://developer.mozilla.org/en-US/docs/Web/API/Element/id) in the generated event handler, specifically the "#window" element.  Thanks.

**Pull request closed without merging**
