### PR TITLE
Fix for issue 4926

### PR DESCRIPTION
**Pull request by ImplOfAnImpl**
The originally suggested fix (replace the initial value of tempDouble) broke a lot of tests in "other.*binaryen*" (since asm2wasm expects those values to be zero), so I fixed the issue differently.

I ran the main and the 'other' test suites. The test 'other.test_crunch' failed because I don't have crunch; 'test_mmap' and 'test_unistd_sysconf' failed both with and without my changes. The rest of tests passed.

### CODE REVIEW

**Comment by kripken** [comment]
This looks ok to me, thanks.

cc @achoudhury85 who wrote the code - thoughts?

**Comment by achoudhury85** [comment]
Looks good to me too.

**Comment by kripken** [comment]
Great, thanks @ImplOfAnImpl! And thanks @achoudhury85 for the quick response too.

**Comment by achoudhury85** [comment]
👍

**Pull request merged**
