### PR TITLE
Skip current failures on travis, which require an emsdk rebuild 

### PR DESCRIPTION
**Pull request by kripken**
It's been a few days now, and it's making things difficult. PR includes a TODO to restore the tests.

### CODE REVIEW

**Comment by saschanaz** [comment]
Is there any blocker for a new tag?

**Comment by kripken** [comment]
About the next tag, I believe @juj is still working on fixing something on his bots.

One of the `other` pushes here timed out, and I can't seem to restart it. Perhaps we should merge this regardless. Anyhow, `other` might be the next thing we should figure out on travis, probably splitting it up

**Comment by saschanaz** [comment]
The job is restarted. But based on the logs I think we may have to split the whole port-related tests.

**Comment by kripken** [comment]
Hmm, maybe it just took a long time for the restart to actually start...

Meanwhile I tried splitting them by name, let's see how that works...

**Comment by saschanaz** [comment]
Hmm, it seems `other` test module does not support parallelism, which seems the reason why it was so slow even on CircleCI.

https://github.com/kripken/emscripten/blob/e812f72/tests/runner.py#L1277-L1283

**Comment by kripken** [comment]
Yes, currently `other` is not parallel because it does some things that could collide (`EMCC_DEBUG` writing to the canonical temp dir). It's a small amount of tests, though, so in theory we could make it just careful about running those tests not in parallel somehow.

**Comment by kripken** [comment]
Ok, that seems to have worked - all green, and the two `other` jobs are about even in time.

**Comment by saschanaz** [comment]
>It's a small amount of tests, though

Not sure, both have 7000+ LOC...

**Pull request merged**
