### PR TITLE
fix_vector_h_inlining

### LINKED ISSUE #5676: 'emscripten_float64x2_add': symbol multiply defined!
I try to build a project with `emcmake`. It compiles well, but then it returns `error: Linking globals named 'emscripten_float64x2_add': symbol multiply defined!`. Because of name of the symbol I guess it's emscipten problem, not the project I try to build. 

I have emscripten installed on OSX via `brew install emscripten`. 

Here is last lines of `make -j4` command:

```
[100%] Linking CXX executable ../../bin/REGoth.html
WARNING:root:forcing separate asm output (--separate-asm), because -s PRECISE_F32=2 or -s USE_PTHREADS=2 was passed.
error: Linking globals named 'emscripten_float64x2_add': symbol multiply defined!
ERROR:root:Failed to run llvm optimizations: 
WARNING:root:Note: Input file "@/tmp/tmpb8rIJd.response" did not exist.
make[2]: *** [bin/REGoth.html] Error 1
make[1]: *** [src/target/CMakeFiles/REGoth.dir/all] Error 2
make: *** [all] Error 2
```

Here is output of `emcc -v`

```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 1.37.22
clang version 4.0.0  (emscripten 1.37.22 : 1.37.22)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /usr/local/opt/emscripten/libexec/llvm/bin
INFO:root:(Emscripten: Running sanity checks)
```

`CMakeList.txt` is located here: https://github.com/REGoth-project/REGoth/blob/web-fixes-2/CMakeLists.txt. 

The project is huge, and consists of bunch of subprojects, so the surface is huge. 
I guess it's not enough information to locate the problem, but I'd happy to provide me, I just don't know what matters.

Thanks

### PR DESCRIPTION
**Pull request by juj**
Fix inlining of SIMD vector header and add a test. Fixes #5676.

### CODE REVIEW

**Comment by kripken** [comment]
lgtm. Perhaps we should add a TODO about creating a library for this, so in C we don't duplicate code?

**Comment by juj** [comment]
These are functions that should always get inlined and never generate functions, not even in `-O0` or `-Og`, because they just would hurt performance and conflict with "step into" calls in debuggers, as they're expected to be individual instructions anyways. If there was a library, that'd then require relying on LTO to inline I think, so probably not desirable to do. Though once Wasm SIMD comes, that'll be a good time to revisit if it makes sense.

**Comment by kripken** [comment]
If they are always inlined, we wouldn't get that error, though, so wasn't the `always_inline` part sufficient? Is the rest just to be safe?

**Comment by juj** [comment]
> If they are always inlined, we wouldn't get that error, though, so wasn't the always_inline part sufficient? Is the rest just to be safe?

I presume the semantics of Clang's `__attribute__(inline)` or `__attribute__(always_inline)` is to only inline somewhere in the final codegen layer, but not in the frontend Clang parsing layer, so for the purposes of C rules, those attributes would not be the same thing as `inline`, but they are just applied during compilation. Though that's just a guess..

**Comment by saschanaz** [comment]
`test_simd3` fails on this PR and also on incoming build, thoughts?

**Comment by juj** [comment]
Very interesting. This regression was caused by LLVM changing its codegen slightly, which resulted in uncovering a misimplementation in the `SIToFP` instruction. Fix in https://github.com/kripken/emscripten-fastcomp/pull/207 and see also https://github.com/kripken/emscripten/pull/5766.

**Pull request merged**
