### PR TITLE
update binaryen to version_39

### PR DESCRIPTION
**Pull request by kripken**
Fixes some breakage, see https://github.com/kripken/emscripten/pull/5750#issuecomment-343055321

### CODE REVIEW

**Comment by kripken** [comment]
So `test_simd3` started to fail, which can't be because of this PR (the test doesn't even use wasm). Should we merge this and investigate that later?

**Comment by dschuff** [comment]
Yeah, makes sense.

**Comment by saschanaz** [comment]
The first bad commit is c3c9b6e4.

**Comment by kripken** [comment]
Thanks, I noted in that commit.

**Pull request merged**
