### PR TITLE
Mangle wasm exports like asm.js exports

### PR DESCRIPTION
**Pull request by dschuff**
but keep them in strings.

### CODE REVIEW

**Comment by kripken** [comment]
This is at risk of name collisions. Perhaps we should do it earlier in the pipeline, where we can easily check such collisions, like in the backend?

**Comment by dschuff** [comment]
We can check for collisions in `emscript_wasm_backend` right when we collect all of the declares and exports. We could even avoid them completely by picking a mangling that would result in a valid JS identifier but not a valid asm identifier (unicode?).

Backing up though, I'd like to try to understand the context a little more. E.g. why are these particular things vars in addition to being properties hanging off of the `asm` object? (for that matter, what's the relationship between the `asm` object and the `Module` object?)

**Comment by kripken** [comment]
The asm object is the instance of the asm.js or wasm module.

The Module object is the main public face of the entire compiled program. Exported things are on it.

We store those things in vars as well so that they can be called by `x()` instead of `asm.x()` or `Module.x()`.

I suppose we could check for collisions here. But I'm not sure why this would be the right place for it, as opposed to elsewhere. I'm not saying this is wrong, I'm saying it seems arbitrary?

**Comment by dschuff** [comment]
Maybe it would make sense just not to give the constructors global vars at all, If having things in vars is for the convenience of users? I can't think of any reason why a user would want to call a constructor directly.

**Comment by kripken** [comment]
Well, this isn't just for constructors. It happens that we need to export constructors. But this would be an issue for all exports. Basically, wasm names allow symbols not possible in JS, and we need to fix that... somewhere.

**Comment by dschuff** [comment]
Right, but exports that are C functions won't have dots. It's only names that are generated by the compiler that are the problem.

**Comment by dschuff** [comment]
(correct me if my JS knowledge is wrong here...)

Or, if we want to treat the problem fully generally, I took a look at http://llvm.org/docs/LangRef.html#identifiers which seems to say that LLVM identifiers can contain any ASCII character. So if someone wanted to drop their own frontend into emscripten and were not using C/C++ they could have functions with any ASCII characters.  None of that is a problem when calling via string properties as `Module["x"]()`, but it's a problem for `Module.x()` or just `x()`, right?

So one option is to mangle the name somehow. If we do that, we have the following problems:
* Do we just mangle the `var` and not the property name? 
  * If so, then it's weird that it doesn't match the property name, and you still can't use `Module.x()`
  * If not, then you have to apply the mangling yourself everywhere you want to call your functions, i.e. you have to use `Module["mangled_x"]()` which is a weird experience.
* How do we mangle? Any ASCII substitution we choose could collide with another legal name in LLVM. We could apply an escaping-style substitution (e.g. "." -> "$" and "$" -> "$$"), or pick some non-ASCII character but either way it gets awkward fast and certainly isn't the convenience feature it's intended to be.

The other option would be to never mangle the name, but just not create a `var` for cases where it would be an illegal JS identifier. Then you would know that `Module["x"]` would always work, regardless of what your function is named, but `var` and `Module.x()` wouldn't work if the identifier has a dot. That's not convenient either, but at least it's simple.

**Comment by kripken** [comment]
Yes, but non-C languages might use the wasm backend.

If we fix this in the wasm backend, it would help any language using it. If we fix it in asm2wasm, it would help any toolchain using that. And if we fix it in emscripten, it'll help anything using that. So I guess the question is, where would this do the most good?

**Comment by kripken** [comment]
Yes, this is a limitation of emscripten - the js backend mangles names for JS, and it works fine for C and C++, but in theory might not for others.

Maybe we can say we don't care about non-C/C++ languages for now.

**Comment by dschuff** [comment]
So, the reason I'm hesitant to fix it in the wasm backend is that it wasm backend could be used in non-JS embeddings where this isn't a problem. (I see asm2wasm as sort of an extension of the wasm backend).

**Comment by kripken** [comment]
True, but the same logic holds for the other pieces: the wasm backend, and s2wasm, and emscripten might all be used in non-JS embeddings, eventually.

**Comment by dschuff** [comment]
What kind of mangling does the JS backend use? we could apply that in emscripten when using the wasm backend, so at least it would be consistent?

**Comment by dschuff** [comment]
If emscripten were used in a non JS setting it wouldn't look much like emscripten today, right? I mean there would be a compiler driver but it would have to have completely different module glue for another embedding.

**Comment by kripken** [comment]
Emscripten's current mangling is done [here](https://github.com/kripken/emscripten-fastcomp/blob/master/lib/Target/JSBackend/JSBackend.cpp#L734).

Yes, emscripten for non-JS would be without all the js library stuff and shell code. However, all the toolchain and non-js libraries could be the same. But yes, that might be more of a change, so that's a valid argument for doing this in emscripten.

**Comment by dschuff** [comment]
Actually the mangling for globals is [here](https://github.com/kripken/emscripten-fastcomp/blob/master/lib/Target/JSBackend/JSBackend.cpp#L717) where it just replaces the invalid characters with "_" and also has
`// TODO: in debug mode, check for such collisions.` :)

So, how about, in `emscript_wasm_backend` where we process the global names (at least exports and initializers), we apply this transformation and also check for collisions. This would also subsume the existing [place](https://github.com/kripken/emscripten/blob/incoming/emscripten.py#L1356) where we apply the "_" prefix.

**Comment by dschuff** [comment]
OK, here's something I think will work for now.
1. The wasm export names are returned from `Module['asm']()` (just as before).
2. In `emscript_wasm_backend`, the 'exports' list in the metadata object does not get '_' prepended when read from the wast.
3. The properties on the `asm` object get the wasm names instead of the mangled names.
4. The properties on the `Module` object and the global function names get mangled in an asm.js-compatible way.
5. An assert checks for collisions when reading the exports from the wast.

It's not perfect, but it does have the advantages that it's simple and the interface is compatible with the way emscripten does things for asm.js.

**Comment by kripken** [comment]
This does look pretty good, thanks. Very reasonable solution.

Please verify it works, `tests/runner.py ALL.test_binaryen`, should cover things.

**Comment by kripken** [comment]
Oh wait, that test doesn't check the wasm backend. We'll see this when we next update the emscripten submodule in binaryen.

**Comment by kripken** [comment]
Merged, thanks!

**Pull request merged**
