### PR TITLE
Add test case to illustrate error with dynamic linking of static member variable

### PR DESCRIPTION
**Pull request by awtcode**
@kripken , this PR adds a test case to illustrate the issue with global static imports that we were previously discussing. Can you take a look at this? Thanks.

### CODE REVIEW

**Comment by awtcode** [comment]
This is the link error that I see:

LinkError: WebAssembly Instantiation: Import #25 module="env" function="g$__ZN4Base6memberE" error: function import requires a callable
    at loadWebAssemblyModule (C:\Users\xxx\AppData\Local\Temp\1\emscripten_test_binaryen0_g12bs0\src.cpp.o.js:479:20)
    at loadDynamicLibrary (C:\Users\xxx\AppData\Local\Temp\1\emscripten_test_binaryen0_g12bs0\src.cpp.o.js:336:15)
    at C:\Users\xxx\AppData\Local\Temp\1\emscripten_test_binaryen0_g12bs0\src.cpp.o.js:1673:9
    at Array.forEach (<anonymous>)
    at loadDynamicLibraries (C:\Users\xxx\AppData\Local\Temp\1\emscripten_test_binaryen0_g12bs0\src.cpp.o.js:1672:12)
    at C:\Users\xxx\AppData\Local\Temp\1\emscripten_test_binaryen0_g12bs0\src.cpp.o.js:1703:3
    at callRuntimeCallbacks (C:\Users\xxx\AppData\Local\Temp\1\emscripten_test_binaryen0_g12bs0\src.cpp.o.js:1417:7)
    at preRun (C:\Users\xxx\AppData\Local\Temp\1\emscripten_test_binaryen0_g12bs0\src.cpp.o.js:1451:3)
    at run (C:\Users\xxx\AppData\Local\Temp\1\emscripten_test_binaryen0_g12bs0\src.cpp.o.js:60939:3)
    at Object.<anonymous> (C:\Users\xxx\AppData\Local\Temp\1\emscripten_test_binaryen0_g12bs0\src.cpp.o.js:61095:1)
', diff:

**Comment by awtcode** [comment]
@kripken , after more investigation, it turns out that the import couldn't be found because SIDE_MODULE=2 removed the static initialization of the object variable. The test case passes when we use EMSCRIPTEN_KEEPALIVE.

Should global variables survive DCE when using SIDE_MODULE=2 or do we expect the clients to annotate the needed global variables with EMSCRIPTEN_KEEPALIVE? The native platforms e.g. Windows don't seem to require the explicit annotation though.

**Comment by kripken** [comment]
Interesting, thanks for filing and investigating this @awtcode!

Overall, mode 2 is already unlike all native platforms, I think, and our behavior there is consistent across functions and globals - anything (function or global) that is not kept alive will be dce'd. It sounds like you were expecting that behavior for functions, but were surprised with globals? Does windows handle functions and globals differently?

**Comment by awtcode** [comment]
Thanks @kripken , I finally managed to come up with a test case that illustrates what I'm using in production. Unfortunately, I need a main and 2 side modules so I can't easily integrate this into the existing test suite. I have created a public github repo here:

https://github.com/awtcode/dylink_static_member

Apparently, what's happening is that the getValue function is inlined but side2.wasm is trying to import the global::value member variable as a function?

**Comment by kripken** [comment]
For integrating into the test suite, sounds like you need to more manually do the various operations. See e.g. `test_dlopen_rtld_global` in `test_other.py` which creates two side modules.

I think the issue here is that if we import a global before the module that provides it is linked in, we need a layer of indirection to be able to access it after it is actually linked in. We use a `g$` function for that. (In the future, mutable globals in wasm might help here.) If that's the case, it should also be possible to show the bug with 2 modules, in a specific order (that's why we do the 'flip' operation in the dylink tests), but if that's hard, 3 modules is good enough as a testcase.

**Comment by awtcode** [comment]
Thanks @kripken . Just to clarify, when you say that we need a layer of indirection when we import a global before the module is linked in, are you referring to side.wasm or side2.wasm in this case? Isn't global::value imported with side2.wasm concurrently?

I can try to come up with a test case tomorrow but due to the timezone difference, it will be another 24 hours before you get to see it. Would it be possible for you to debug on the github repo in the meantime? Sorry for the inconvenience caused.

**Comment by awtcode** [comment]
Thanks @kripken , you are absolutely right :) I got your changes in #6963 and was able to import a global that was provided by a side module that loads later. 

Yes, the proxy-to-worker is actually not needed. I used it because I debugged using the browser and I wasn't able to compile the Wasm binary synchronously in the main thread.

Do you typically use the browser or node for debugging?

**Comment by kripken** [comment]
Debugging in the shell is usually easier I think - in particular because automatic testing is easier there (and 99% of our tests run that way for that reason - everything but what absolutely must run in the browser).

Btw, I realized that there might be a similar issue with functions, not just globals. Working on a patch for that.

**Comment by kripken** [comment]
That PR should fix function pointers too now, so hopefully it fixes all the issues you saw here.

**Comment by kripken** [comment]
Personally I don't use breakpoints or debuggers anywhere, just printf debugging for me ;)

#6963 hasn't landed yet, so a new release wouldn't help yet. If you have time, you can help speed that along by reviewing that PR - reading it carefully to see if anything seems odd or improveable - and/or testing the PR and commenting if it fixes your issues or not (you commented here about the global issue, but does the PR fix the rest too? hopefully it does).

**Comment by awtcode** [comment]
@kripken , sure, I will comment in #6963 then.

**Pull request closed without merging**
