### PR TITLE
Adds a few operators to val

### PR DESCRIPTION
**Pull request by robfors**
operators added:
`instanceof`, `in`, `==`, `!=`, `<`, `>`, `<=`, `>=`

### CODE REVIEW

**Comment by brion** [comment]
Looks good to me. Might be a good idea to add a test case .cpp file in `tests/embind`, like the test_unsigned.cpp, just to exercise the API.

I _think_ the CI test errors reported before are weird spurious errors, but I don't know how to re-run the tests.

**Comment by kripken** [comment]
I agree we should add tests here before merging.

Also, the CI error on `other.test_cmake_with_embind_cpp11_mode` looks like it may not be a random failure?

**Comment by robfors** [comment]
would a `test_val.cpp` make sense?

**Comment by brion** [comment]
@robfors yeah that's probably what I would recommend. A small self-contained bit that can exercise some of the constructors, operators, and accessors via C and verify them on the JS side with an EM_ASM block, maybe?

**Comment by robfors** [comment]
The tests passing with `python tests/runner.py test_embind_val`.
I don't know what is going on with CI though.

**Comment by kripken** [comment]
I suspect the CI failures were just a recent temporary problem we had. Merging incoming and pushing that should trigger a new build, which hopefully will pass.

**Comment by kripken** [comment]
However, on travis I still see `other.test_cmake_with_embind_cpp11_mode` fail, so that looks non-random. Does `python tests/runner.py other.test_cmake_with_embind_cpp11_mode` pass for you?

**Comment by robfors** [comment]
I see my mistake. `python tests/runner.py other.test_cmake_with_embind_cpp11_mode` passes now.

**Comment by kripken** [comment]
I think that CI error is an emscripten SDK mismatch. If you merge in very latest incoming and push that here, it should work.

**Comment by robfors** [comment]
Looks like it is ready now.

**Pull request merged**
