### PR TITLE
Improve performance of invoke calls

### PR DESCRIPTION
**Pull request by Mintyboi**
The idea is to improve the performance of the invoke calls by directly accessing the wasm table instead of going through the hoops of dyncalls and ftcalls.
Seeing that dyncall_ and ftcall_ functions are no longer referenced, I also attempted to clean those up.

### CODE REVIEW

**Comment by Mintyboi** [comment]
Letting it run through CI to see if there are any failures

**Comment by Mintyboi** [comment]
There are a lot of failures in the CI, maybe I shouldn't have removed the dyn and ft calls

**Comment by kripken** [comment]
We should implement dynCalls using a table call, when an option is set - I think `EMULATED_FUNCTION_POINTERS`. So that would be equivalent to your approach, if the content of dynCall were inlined by the JS VM.

It might be interesting to get that option enabled by default. However, there are some issues with legalization - things like i64 and f32 that you can't send from JS directly, so a wrapper is necessary,  see the discussion in https://github.com/kripken/emscripten-fastcomp/pull/243

**Comment by Mintyboi** [comment]
Thanks for your reply!
I see, ok, I did not try out non legalized type, but I understand the concern there.

**Comment by Mintyboi** [comment]
But to improve the performance of invoke calls when assertion is turned on, do you think caching the value of module['wasmtable'].length makes sense?
The cache will be updated whenever a new wasm module is being loaded.

**Comment by kripken** [comment]
I think the VM might cache that well enough. But if you have a benchmark showing otherwise perhaps it indicates something VMs need to improve on.

**Pull request closed without merging**
