### PR TITLE
Add FORCE_TEXTDECODER option which means we assume it must exist

### PR DESCRIPTION
**Pull request by kripken**
This avoids emitting the fallback code, as suggested in #7802 . This shrinks hello world by around 5%.

However,  we can't do this by default, nor even when not `LEGACY_VM_SUPPORT`, since TextDecoder is not present in neither Edge (even the last version from a month or so ago) nor Node.js (at least not in 8.12). :anguished:

### CODE REVIEW

**Comment by chicoxyzzy** [comment]
TextDecoder is presented since node 8.3.0
https://nodejs.org/api/util.html#util_class_util_textdecoder

**Comment by kripken** [comment]
Thanks @chicoxyzzy! Good, but it looks like it's on `util`, so not present in the global scope like on the web. We'd need to do something like `require('util').TextDecoder` if on node, which means more detection code...

**Comment by surma** [comment]
I am not sure if you wanna punch me for this suggestion, but you could treat Node8 and Node10 as separate `ENVIRONMENT`s that generate different code. Just a thought.

Either way, thanks for the amazingly quick turnaround on these small optimizations!

**Comment by chicoxyzzy** [comment]
> but you could treat Node8 and Node10 as separate ENVIRONMENTs that generate different code

Yes, I too have had the same thought. Doesn't sound like something hard to implement comparing to FS for example. I may be wrong though =).

@kripken could you please point me to files where this should be implemented. I'm not very familiar with Emscripten codebase, but will be happy to explore it and maybe contribute. Importing Encoding APIs based on environment seems like a good first feature for newbies like me. [This part](https://github.com/kripken/emscripten/blob/master/src/modules.js#L96 ) seems relevant.

**Comment by juj** [comment]
Instead of `FORCE_TEXTDECODER=1`, could this be enabled as `-s TEXTDECODER=2` option, i.e. (0 - disabled, 1- enabled if present, 2 - required)? That would be simpler than two separate flags?

**Comment by kripken** [comment]
About treating node 8 vs 10 differently, I think I'd prefer not to. It adds complexity that is only necessary temporarily, since node 10 is actually the current LTS version, so I don't think we need to wait a long time, so we can probably just make anything for node 8 be behind `LEGACY_VM_SUPPORT`.

**Comment by kripken** [comment]
Oh good, thanks @chicoxyzzy - if node 11 has it in the global scope, I think we can probably just avoid special-casing node.

**Comment by kripken** [comment]
Changed to `TEXTDECODER=2` as suggested.

**Comment by juj** [comment]
lgtm

**Pull request merged**
