### PR TITLE
fix missing dependency of recv, send on htons

### PR DESCRIPTION
**Pull request by ahixon**
Similar to #4761.

### CODE REVIEW

**Comment by kripken** [comment]
Looks good, thanks, please just add yourself to AUTHORS.

**Comment by juj** [comment]
Looks great, these deps are so easy to overlook. :/

There seems to be a merge commit in this PR, any chance you could rebase to itself and skip the merge? That would make the history a bit more readable.

**Comment by ahixon** [comment]
Haha, sorry yeah I accidentally pushed the wrong thing just before you wrote that. Fixed!

**Comment by juj** [comment]
Oh wait, how are `recv()` and `send()` command like that expected to behave? Those were added in just to test that their deps get linked in correctly. Do they expect to generate an errno error during the execution of the test? They both access fd=0 which is the standard input stream - is that intentional?

**Comment by ahixon** [comment]
Yeah, the test was originally added in dafadb2f4f210426c841c0f1a605fafd43a97a3d just to ensure it links correctly. I just added those two in the same place since they had the same linking problem.

Both calls may either return -1 (and set errno to `EBADF`), or return 0 and be a no-op, since the size provided is zero. I don't know if socket descriptor 0 is stdin; although yeah file descriptor 0 is on Unix, it probably depends whether the OS treats the socket and file descriptor tables as one in the same. If we wanted to be "correct", we could call `socket()` to create a valid socket first.

In that test, we don't bother checking the return value since we don't actually care about the implementation of recv/send in that case -- just that they link OK.

**Comment by juj** [comment]
In Emscripten fd 0 is stdin as well (fd 1 is stdout and fd 2 is stderr). I suppose for the purposes of the test, it's ok, I just wonder if natively `recv` on stdin descriptor would mean the application would block until the user presses a key.

**Pull request merged**
