### PR TITLE
Fix warning from test_embind_2.

### PR DESCRIPTION
**Pull request by waywardmonkeys**

### CODE REVIEW

**Comment by kripken** [comment]
This broke that test in all modes.

**Comment by waywardmonkeys** [comment]
In what JS engine? I ran it here before submitting ... and it looks to me like it is passing on current incoming:

````
batavia:emscripten bruce (incoming) $ python ./tests/runner.py ALL.test_embind_2
Running all test modes on test "test_embind_2"
test_embind_2 (test_core.default) ... (checking sanity from test runner)
INFO     root: (Emscripten: Running sanity checks)
ok
test_embind_2 (test_core.asm1) ... ok
test_embind_2 (test_core.asm2) ... ok
test_embind_2 (test_core.asm3) ... ok
test_embind_2 (test_core.asm2f) ... ok
test_embind_2 (test_core.asm2g) ... ok
test_embind_2 (test_core.asm1i) ... WARNING  root: enabling js opts for EMTERPRETIFY
WARNING  root: enabling --memory-init-file for EMTERPRETIFY
ok
test_embind_2 (test_core.asm3i) ... ok
test_embind_2 (test_core.asm2nn) ... ok

----------------------------------------------------------------------
Ran 9 tests in 27.049s

OK
````

**Comment by kripken** [comment]
On spidermonkey.

**Comment by kripken** [comment]
Looks like the js shell `quit` method is run before stdout is written to, somehow. But why just in this test?

**Comment by kripken** [comment]
Oh i see, the test is invalid - it runs main now, then has output in a post-js. Will fix.

**Pull request merged**
