### PR TITLE
avoid compiler warnings in webidl test

### PR DESCRIPTION
**Pull request by andreasplesch**
addresses #3994.

### CODE REVIEW

**Comment by kripken** [comment]
Looks good, please just add yourself to AUTHORS.

In general pulls should go to the `incoming` branch, although here, this change can probably be merged by us into incoming without problems.

**Comment by andreasplesch** [comment]
Ok. I added myself to AUTHORS. Let me know if I should push the commits to incoming. It would be easy enough.

**Comment by kripken** [comment]
Looks like this breaks the browser test - I think it does need main()?

**Comment by andreasplesch** [comment]
Yes, it does. And it says so in text.cpp .. Apologies.

**Comment by kripken** [comment]
Ok, looks good, please just squash those commits (so bisecting is not broken).

**Comment by andreasplesch** [comment]
closed and replaced by #4014 to streamline commits and direct to incoming branch,.

**Pull request closed without merging**
