### PR TITLE
Fixed doc issue about smart pointers in Embind

### PR DESCRIPTION
**Pull request by andrnag**
Without these parameters I get binding errors.
Embind tests have these parameters.

### CODE REVIEW

**Comment by kripken** [comment]
cc @chadaustin @brion

**Comment by brion** [comment]
Yep, the doc is wrong; fix looks correct.

**Comment by chadaustin** [comment]
I don't recall exactly but I think you want the name passed to `smart_ptr_constructor` to generally be different than the class itself. But perhaps it's harmless?

**Comment by andrnag** [comment]
@chadaustin I don't really understand that impact has theese names. It seems it is only labels. So programmer can set it freely. I choose same names because it is so in other parts of documentation. I agree it is a bit awkward and may confuse users. I think problem is in naming class as "C", maybe something about "MyClass" will be better for understanding.

**Comment by kripken** [comment]
Great, thanks!

**Pull request merged**
