### PR TITLE
Pass BINARYEN_ROOT in gen_struct_info.py as a setting

### PR DESCRIPTION
**Pull request by jgravelle-google**

### CODE REVIEW

**Comment by kripken** [comment]
In the other issue you said this works because the port has already been fetched at this point. Why would it be, though - I think what I was seeing is that we need to build binaryen from inside gen_struct_info?

**Comment by kripken** [comment]
I see this work with binaryen set or not set in the config file - did you see it break somehow?

As to the general point, we use ports for the retrieval mechanism, and maybe "bootstrapping struct info means no ports" should mean "no ports that invoke emcc" (which binaryen's build system does not). In theory we could make binaryen not a port, but what instead? ...a git submodule..? :(

**Comment by kripken** [comment]
Manually fetching binaryen with the emsdk is an option I guess, as you mention, but it means no automatic fetching of it without the emsdk. So if you just get the source code without the sdk, you'd need to do the same for binaryen, and set up the config file. Maybe that's not so bad...

**Comment by jgravelle-google** [comment]
It'd basically be treating binaryen as though it were LLVM (fastcomp), which it's closer in nature to. So an end user either gets LLVM on their own and configures their emscripten config file, or they use emsdk and let it handle it. That sounds reasonable to me, but I don't have a good sense of what most users do here.

**Comment by kripken** [comment]
Yeah, the more I think about it, the more I agree with you :)

But it does mean we need to package it in the emsdk, which I am not sure we do.

**Comment by jgravelle-google** [comment]
Or, as an even better idea (credit to @dschuff):
We can just start using `shared.BINARYEN_ROOT` directly for the wasm backend path. This requires that we set `BINARYEN_ROOT` in `.emscripten`, but only when using wasm backend, which is currently something kinda weird a user has to opt in to manually.

**Pull request closed without merging**
