### PR TITLE
Add an option to ignore closure compiler errors

### PR DESCRIPTION
**Pull request by kripken**
Sometimes figuring out the right suppressions is not that easy, in the newer closure which checks a lot more things.

### CODE REVIEW

**Comment by kripken** [comment]
No concerns about this?

I need it for ammo.js (which after the latest closure update, his a closure error that's hard to work around - a Bullet class has a name which overlaps with a browser API, `Node`).

**Comment by dschuff** [comment]
No objections.

**Comment by juj** [comment]
When there are Closure errors, does that not produce a failed minification, and it's the same as not running Closure in the first place? Or are some of the Closure errors only linting style, and the result is still good? I'm wondering if there's an advantage over to just disabling Closure if it errors out?

**Comment by kripken** [comment]
It's linting, yeah. Closure has gotten more strict by default, the new version doesn't like Bullet creating `function Node` (because it is defined on the web). Disabling that warning makes it still work.

**Pull request merged**
