### PR TITLE
Pass '--mvp-features' to wasm-opt (temp solution)

### PR DESCRIPTION
**Pull request by tlively**

### CODE REVIEW

**Comment by tlively** [comment]
cc @kripken @sbc100

**Comment by tlively** [comment]
The flag is in binaryen since Dec 3.

**Comment by kripken** [comment]
Sounds good. Yeah, tests so far are passing I see, which confirms this is good.

**Comment by kripken** [comment]
Merging quickly since it fixes waterfall breakage.

**Pull request merged**
