### PR TITLE
Emterpreter-async state fix

### PR DESCRIPTION
**Pull request by kripken**
See #6820 for background. This implements the first option suggested there, which is to relax the assertion: we know that state 1 means saving the stack or sleeping, and 3 means definitely sleeping, but we don't have a way to know when saving the stack is complete in the general case, so don't assert on that.

### CODE REVIEW

**Comment by kripken** [comment]
Ok, this should be in good shape now. Here's a full explanation of what this PR does:

 * Allow running code while sleeping: We had some arbitrary restrictions on this which we started to improve in #6749, and this PR should finish that up. After this PR, it is ok to run emterpreted or non-emterpreted code during a sleep, it is up to the user to do that only when it is valid.
 * Clarify the emterpreter-async states: 0 is normal execution. 1 is set when we start to save the stack and continues as we sleep. We don't have a way to know when the stack has finished unwinding, since we don't have the machinery to do that. But if we start to run a function in state 1, that means we are running code during the sleep (as we cannot reach a function entry while saving the stack - when saving we are just exiting, going up the stack), so we switch to mode 3, which means definitely asleep (i.e., after saving the stack). The distinction is important, because if we see state 1 in the middle of a function - not the entry - then something is wrong (for example, a non-emterpreted function on the stack while saving). Finally, mode 2 is resuming execution, and is set from JS at the proper time.
 * Add an assertion in EM_ASMs: we cannot start an async operation in the middle of them, as the JS is not emterpreted, so we can't jump into the middle to resume. That is, we'd end up running the entire EM_ASM from the start.
 * Add a bunch of tests and improve existing ones.

It would be good to test this PR on real-world code too - cc @TrevorSundberg @Beuc @curiousdannii please let me know if you see any issues.

**Comment by TrevorSundberg** [comment]
Sounds good, I'll pull this on Monday and test it out 👍

**Comment by Beuc** [comment]
This seems to be working better.

I was coincidentally investigating some assert(-12) issues from `incoming` that I got while experimenting with `EMTERPRETIFY_WHITELIST` (the stack trace showed non-emterpreter functions while I had whitelisted them, possible because they were called by a `byn$fpcast-emu_*` one).

These errors went away :)

**Comment by hostilefork** [comment]
This resolves the issue for my purposes...thanks for the quick turnaround!

**Comment by kripken** [comment]
Ok, multiple confirmations this is good, thanks! Merging.

**Pull request merged**
