### PR TITLE
Refactor emcc py

### PR DESCRIPTION
**Pull request by jgravelle-google**
In the same line as emscripten.py cleanups, start taking the same approach to emcc.py.

Main points:
* extract a bunch of methods from inline code to standalone methods
* promote nested classes and functions to top-level helper functions
* make global variables non-global
  * except for `final`, which will be much harder to untangle. Which makes it twice as worth doing. Eventually.
* bundle most command line args into `EmccOptions` class, for ease of passing around

Will test with asm0-3,binaryen0-3,browser,other , posting for review concurrently

### CODE REVIEW

**Comment by kripken** [comment]
lgtm, nice work.

I see some emscripten.py changes too, are they related to the emcc.py ones? or logically separate?

**Comment by jgravelle-google** [comment]
Wholly logically separate. I was basically iterating through "find thing to refactor, refactor it, repeat," and then realized I was in the wrong file.
I figured it was inoffensive and thematically similar though, so I didn't think to split it into a separate PR.

**Comment by kripken** [comment]
Cool, no concerns from me, was just curious if there was a link I was missing.

**Comment by jgravelle-google** [comment]
Ran all tests, one issue that was fixed in https://github.com/kripken/emscripten/pull/5236/commits/1ac5e6ce830584bccd72f6a60edc03d172d262ca, merging

**Pull request merged**
