### PR TITLE
Fix emscripten_get_mouse_status

### PR DESCRIPTION
**Pull request by Thinkofname**
Fixes two issues:
* `subarray`'s last argument is the [end index not the length](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray/subarray).
* Used HEAP32 without shifting the pointer, changed to HEAP8 to simplify as well.

### CODE REVIEW

**Comment by kripken** [comment]
Thanks, this looks right to me. Can you please add a test for it? Looks like we don't have one yet, which is why this was not noticed as broken. Maybe can add to `test_html5_mouse`.

**Comment by Thinkofname** [comment]
@kripken Done

**Comment by kripken** [comment]
Thanks, looks good. I don't think you're in AUTHORS yet? Please add yourself before we merge.

**Comment by Thinkofname** [comment]
Whoops, thought I was. Added

**Comment by kripken** [comment]
Great!

**Pull request merged**
