### PR TITLE
Allow the browser test runner to use arbitrary ports

### PR DESCRIPTION
**Pull request by dschuff**
Get them from the environment and set them on the instance rather than hardcoding them.
This allows browser tests to be run in parallel when driven by an external script (e.g.
to test firefox and chrome simultaneously), and is a step on the way toward making the
browser tests truly parallel like the core tests.

### CODE REVIEW

**Comment by dschuff** [comment]
Tested locally; going to go ahead and merge since none of the CIs actually cover this.

**Comment by kripken** [comment]
Oddly, this caused breakage on CI, https://circleci.com/gh/kripken/emscripten/496?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link I don't see it locally either, it might be specific to the compile-only mode?

**Comment by kripken** [comment]
Seems so. Possible fix in 637d6b3781f8665fa0e742fa508ddb4c69504d71

**Comment by kripken** [comment]
(Also, do we still need the branch here, or can we delete it?)

**Comment by kripken** [comment]
(Fix looks good, pushed to incoming.)

**Comment by dschuff** [comment]
Oh oops, I had that exact fix in my branch locally but forgot to push it before I merged, sorry :-/

**Pull request merged**
