### PR TITLE
Remove duplicate SAFE_HEAP_[STORE|LOAD] functions

### PR DESCRIPTION
**Pull request by franc0is**
They are already implemented in `preamble.js` and thus end up being defined twice in the compiled code.

### CODE REVIEW

**Comment by kripken** [comment]
I'm not sure, but I believe the copy in `preamble.js` is outside of the asm module (function scope with `"use asm"`), and the one in `emscripten.py` is inside the asm module. We need the former for library code in normal JS, and the latter inside asm.js (since calls to the outside are slower).

**Comment by franc0is** [comment]
You are right. I wonder why this works at all locally...

**Comment by kripken** [comment]
My guess is that it breaks asm.js validation (look in firefox console to see), but still runs correctly since it uses the functions from outside the asm module.

**Comment by franc0is** [comment]
What I'm trying to do is extend SAFE_HEAP_LOAD/_STORE to allow unaligned accesses (based on an option). I modified the SAFE_HEAP_LOAD in preamble.js as such
```
  if (dest % bytes !== 0) {
    for (i = 0; i < bytes; i++) {
      HEAPU8[dest + i >> 0] = (dest >> (8 * i)) & 0xff;
    }
  } else {
    setValue(dest, value, getSafeHeapType(bytes, isFloat), 1);
  }
```

and similarly for SAFE_HEAP_LOAD. I was hoping to avoid modifying two versions of each especially as I am not very familiar with asm.js

**Comment by franc0is** [comment]
(for my use case performance isn't a big concern)

**Comment by kripken** [comment]
I see. Yes, if speed isn't a concern, you can just remove the asm versions and use the ones outside, that seems best for your situation.

**Pull request closed without merging**
