### PR TITLE
Add test for tabs in EM_ASM strings.

### PR DESCRIPTION
**Pull request by juj**
Fixes https://github.com/kripken/emscripten/issues/5593

### CODE REVIEW

**Comment by kripken** [comment]
lgtm, but this depends on a backend change, so the test may start to fail in wasm-backend mode.

**Comment by juj** [comment]
CC @jgravelle-google.

**Comment by juj** [comment]
This was merged along with https://github.com/kripken/emscripten-fastcomp/pull/198

**Comment by jgravelle-google** [comment]
This seems to work according to the wasm waterfall, but I'm not entirely sure why? In s2wasm, in `AsmConstWalker::escape`, it looks like we basically have a copy of the relevant escaping code from Fastcomp's `getAsmConstId`, so it's not immediately obvious how that just works as-is.

**Pull request merged**
