### PR TITLE
cleanup_site_build

### PR DESCRIPTION
**Pull request by juj**
Remove site/build/ directory, since those are build artifacts that are built during the docs build process.

### CODE REVIEW

**Comment by kripken** [comment]
It's actually intentionally there, so the txt doc files are present without need to building them. I.e. we ship txt docs with the repo.

I can see an argument for removing it, though, but it's not that these are just forgotten artificacts.

**Comment by kripken** [comment]
In fact `emcc.py` will read the `emcc.txt` one and print it for `emcc --help`.

**Comment by juj** [comment]
Oh, gotcha on the `emcc.py` reading `emcc.txt` part, didn't remember that one.

Though we do only ship four files from the text documentation build:

	emscripten/site/build/text/docs/api_reference/emscripten.h.txt
	emscripten/site/build/text/docs/api_reference/html5.h.txt
	emscripten/site/build/text/docs/api_reference/preamble.js.txt
	emscripten/site/build/text/docs/tools_reference/emcc.txt

whereas if one does a text doc build, then it has much more files in it:

	emscripten/site/build/text/index.txt
	emscripten/site/build/text/docs/api_reference/advanced-apis.txt
	emscripten/site/build/text/docs/api_reference/bind.h.txt
	emscripten/site/build/text/docs/api_reference/emscripten.h.txt
	emscripten/site/build/text/docs/api_reference/Filesystem-API.txt
	emscripten/site/build/text/docs/api_reference/html5.h.txt
	emscripten/site/build/text/docs/api_reference/index.txt
	emscripten/site/build/text/docs/api_reference/module.txt
	emscripten/site/build/text/docs/api_reference/preamble.js.txt
	emscripten/site/build/text/docs/api_reference/trace.h.txt
	emscripten/site/build/text/docs/api_reference/val.h.txt
	emscripten/site/build/text/docs/building_from_source/building_emscripten_from_source_on_linux.txt
	emscripten/site/build/text/docs/building_from_source/building_emscripten_from_source_on_mac_os_x.txt
	emscripten/site/build/text/docs/building_from_source/building_emscripten_from_source_on_windows.txt
	emscripten/site/build/text/docs/building_from_source/building_emscripten_from_source_using_the_sdk.txt
	emscripten/site/build/text/docs/building_from_source/building_fastcomp_manually_from_source.txt
	emscripten/site/build/text/docs/building_from_source/configuring_emscripten_settings.txt
	emscripten/site/build/text/docs/building_from_source/index.txt
	emscripten/site/build/text/docs/building_from_source/LLVM-Backend.txt
	emscripten/site/build/text/docs/building_from_source/manually_integrating_emscripten_with_vs2010.txt
	emscripten/site/build/text/docs/building_from_source/toolchain_what_is_needed.txt
	emscripten/site/build/text/docs/building_from_source/verify_emscripten_environment.txt
	emscripten/site/build/text/docs/compiling/Building-Projects.txt
	emscripten/site/build/text/docs/compiling/index.txt
	emscripten/site/build/text/docs/compiling/Running-html-files-with-emrun.txt
	emscripten/site/build/text/docs/contributing/AUTHORS.txt
	emscripten/site/build/text/docs/contributing/contributing.txt
	emscripten/site/build/text/docs/contributing/developers_guide.txt
	emscripten/site/build/text/docs/contributing/index.txt
	emscripten/site/build/text/docs/debugging/CyberDWARF.txt
	emscripten/site/build/text/docs/getting_started/bug_reports.txt
	emscripten/site/build/text/docs/getting_started/downloads.txt
	emscripten/site/build/text/docs/getting_started/FAQ.txt
	emscripten/site/build/text/docs/getting_started/getting_started_with_emscripten_and_vs2010.txt
	emscripten/site/build/text/docs/getting_started/index.txt
	emscripten/site/build/text/docs/getting_started/test-suite.txt
	emscripten/site/build/text/docs/getting_started/Tutorial.txt
	emscripten/site/build/text/docs/introducing_emscripten/about_emscripten.txt
	emscripten/site/build/text/docs/introducing_emscripten/community.txt
	emscripten/site/build/text/docs/introducing_emscripten/emscripten_license.txt
	emscripten/site/build/text/docs/introducing_emscripten/index.txt
	emscripten/site/build/text/docs/introducing_emscripten/release_notes.txt
	emscripten/site/build/text/docs/introducing_emscripten/Talks-and-Publications.txt
	emscripten/site/build/text/docs/optimizing/Optimizing-Code.txt
	emscripten/site/build/text/docs/porting/asyncify.txt
	emscripten/site/build/text/docs/porting/Debugging.txt
	emscripten/site/build/text/docs/porting/emscripten-runtime-environment.txt
	emscripten/site/build/text/docs/porting/emterpreter.txt
	emscripten/site/build/text/docs/porting/index.txt
	emscripten/site/build/text/docs/porting/pthreads.txt
	emscripten/site/build/text/docs/porting/simd.txt
	emscripten/site/build/text/docs/porting/connecting_cpp_and_javascript/embind.txt
	emscripten/site/build/text/docs/porting/connecting_cpp_and_javascript/index.txt
	emscripten/site/build/text/docs/porting/connecting_cpp_and_javascript/Interacting-with-code.txt
	emscripten/site/build/text/docs/porting/connecting_cpp_and_javascript/WebIDL-Binder.txt
	emscripten/site/build/text/docs/porting/files/file_systems_overview.txt
	emscripten/site/build/text/docs/porting/files/index.txt
	emscripten/site/build/text/docs/porting/files/packaging_files.txt
	emscripten/site/build/text/docs/porting/files/Synchronous-Virtual-XHR-Backed-File-System-Usage.txt
	emscripten/site/build/text/docs/porting/guidelines/api_limitations.txt
	emscripten/site/build/text/docs/porting/guidelines/browser_limitations.txt
	emscripten/site/build/text/docs/porting/guidelines/function_pointer_issues.txt
	emscripten/site/build/text/docs/porting/guidelines/index.txt
	emscripten/site/build/text/docs/porting/guidelines/portability_guidelines.txt
	emscripten/site/build/text/docs/porting/multimedia_and_graphics/EGL-Support-in-Emscripten.txt
	emscripten/site/build/text/docs/porting/multimedia_and_graphics/index.txt
	emscripten/site/build/text/docs/porting/multimedia_and_graphics/OpenGL-support.txt
	emscripten/site/build/text/docs/site/about.txt
	emscripten/site/build/text/docs/site/glossary.txt
	emscripten/site/build/text/docs/site/index.txt
	emscripten/site/build/text/docs/tools_reference/emcc.txt
	emscripten/site/build/text/docs/tools_reference/emcmdprompt.txt
	emscripten/site/build/text/docs/tools_reference/emsdk.txt
	emscripten/site/build/text/docs/tools_reference/index.txt

If one adds new doc files and does a rebuild, the new built .txt files are currently not going to the repo, since the whole doc build directory is in .gitignore here: https://github.com/kripken/emscripten/blob/master/site/.gitignore#L8

Is emcc.txt the only file we need to reference externally in this manner? If so, then I think we could commit that only for that reason, and take the stance to leave all other doc files out?

**Comment by juj** [comment]
Force-pushed the PR to leave emcc.txt intact, but remove the other three text doc files. How does that look to you?

(we could also think to have the full text doc builds be part of the repository, but I think that would call for a push hook that automatically would ensure the docs are up to date in each commit, or otherwise it might be a bit annoying to have possibly stale files in the repo(?))

**Comment by kripken** [comment]
I think `emcc.txt` is the only one we need.

I guess the question is whether there is value in shipping the other 3 for users to have local docs. I suppose not. So lgtm.

**Comment by juj** [comment]
Ok, merging. Thanks again to @rfeneon for pointing this out in the first place.

**Pull request merged**
