### PR TITLE
emdump

### PR DESCRIPTION
**Pull request by juj**
Add new tool 'emdump' to allow analyzing compiled code sizes

### CODE REVIEW

**Comment by juj** [comment]
Example output of dumping function sizes:

```bash
clbs-MacBook-Pro:build_release clb$ emdump --file tiny_chess.js tiny_chess.asm.js --filter-size=100
     1 lines   28577 (22.44%) :      var JSEvents
     1 lines   17131 (13.45%) :      var Browser
     1 lines   11623 ( 9.13%) :    asmjs _malloc(a) ; nb(a)
   180 lines    8602 ( 6.76%) :   [UNKN] $unaccounted_content_in("tiny_chess.js")
     1 lines    6654 ( 5.23%) :      var GL
     1 lines    3219 ( 2.53%) :    asmjs _free(a) ; ob(a)
     1 lines    2733 ( 2.15%) :    asmjs Board::find_king(int, int*, int*) ; Va(a,b,e,f)
     1 lines    2507 ( 1.97%) :       js _emscripten_set_main_loop(func,fps,simulateInfiniteLoop,arg,noSetTiming)
   133 lines    2371 ( 1.86%) :   [UNKN] $unaccounted_content_in("tiny_chess.asm.js")
     1 lines    2263 ( 1.78%) :    asmjs Board::mark_controlled_squares(int, int (*) [8]) ; Ua(b,d,e)
     1 lines    2036 ( 1.60%) :    asmjs draw_board() ; lb()
     1 lines    1462 ( 1.15%) :       js _emscripten_set_main_loop_timing(mode,value)
     1 lines    1454 ( 1.14%) :       js _emscripten_webgl_create_context(target,attributes)
     1 lines    1260 ( 0.99%) :    asmjs Board::generate_king_moves(int, int, int, int*) ; $a(b,e,f,g,h)
     1 lines    1244 ( 0.98%) :       js stringToUTF8Array(str,outU8Array,outIdx,maxBytesToWrite)
     1 lines    1064 ( 0.84%) :       js emscriptenWebGLGetTexPixelData(type,format,width,height,pixels,internalFormat)
     1 lines    1011 ( 0.79%) :    asmjs Board::generate_bishop_moves(int, int, int, int*) ; Za(b,d,e,f,g)
     1 lines     887 ( 0.70%) :       js _glUniformMatrix4fv(location,count,transpose,value)
     1 lines     840 ( 0.66%) :    asmjs _memcpy(b,d,e) ; rb(b,d,e)
     1 lines     833 ( 0.65%) :    asmjs Board::make_move(int, int, int, int) ; Sa(b,c,d,e,f)
     1 lines     823 ( 0.65%) :       js _upload_unicode_char_to_texture(unicodeChar,charSize,applyShadow)
     1 lines     823 ( 0.65%) :       js UTF8ArrayToString(u8Array,idx)
     1 lines     802 ( 0.63%) :    asmjs Board::generate_knight_moves(int, int, int, int*) ; Xa(a,b,e,f,g)
     1 lines     775 ( 0.61%) :    asmjs draw_background() ; ib()
     1 lines     769 ( 0.60%) :    asmjs Board::mark_bishop_controlled_squares(int, int, int (*) [8]) ; _a(b,d,e,f)
     1 lines     712 ( 0.56%) :    asmjs Board::generate_rook_moves(int, int, int, int*) ; Ya(b,d,e,f,g)
     1 lines     674 ( 0.53%) :       js setValue(ptr,value,type,noSafe)
     1 lines     669 ( 0.53%) :    asmjs Board::generate_pawn_moves(int, int, int, int*) ; Wa(b,d,e,f,g)
     1 lines     634 ( 0.50%) :    asmjs Board::new_game() ; Ra(b)
     1 lines     613 ( 0.48%) :    asmjs mouse_callback(int, EmscriptenMouseEvent const*, void*) ; kb(b,d,e)
     1 lines     592 ( 0.46%) :       js callMain(args)
     1 lines     559 ( 0.44%) :       js run(args)
     1 lines     558 ( 0.44%) :    asmjs draw_piece(float, float, int) ; hb(a,b,d)
     1 lines     531 ( 0.42%) :    asmjs Board::generate_moves(int, int, int*) ; bb(b,d,e,f)
     1 lines     518 ( 0.41%) :       js ccall(ident,returnType,argTypes,args,opts)
     1 lines     510 ( 0.40%) :       js _glGetUniformLocation(program,name)
     1 lines     508 ( 0.40%) :    asmjs load_assets() ; gb()
     1 lines     493 ( 0.39%) :    asmjs draw_pieces() ; jb()
     1 lines     475 ( 0.37%) :    asmjs _memset(b,d,e) ; sb(b,d,e)
     1 lines     469 ( 0.37%) :       js abortOnCannotGrowMemory()
     1 lines     459 ( 0.36%) :       js Pointer_stringify(ptr,length)
     1 lines     422 ( 0.33%) :       js updateGlobalBufferViews()
     1 lines     382 ( 0.30%) :       js _emscripten_webgl_init_context_attributes(attributes)
     1 lines     358 ( 0.28%) :    asmjs Board::generate_moves_without_king_safety(int, int, int, int*) ; ab(b,c,d,e,f)
     1 lines     357 ( 0.28%) :       js callRuntimeCallbacks(callbacks)
     1 lines     356 ( 0.28%) :       js removeRunDependency(id)
     1 lines     356 ( 0.28%) :      var JSfuncs
     1 lines     343 ( 0.27%) :       js useRequest()
     1 lines     328 ( 0.26%) :       js getNativeTypeSize(type)
     1 lines     312 ( 0.25%) :    asmjs init_gl() ; fb()
     1 lines     309 ( 0.24%) :       js lengthBytesUTF8(str)
     1 lines     308 ( 0.24%) :       js emscriptenWebGLComputeImageSize(width,height,sizePerPixel,alignment)
     1 lines     297 ( 0.23%) :       js _glTexImage2D(target,level,internalFormat,width,height,border,format,type,pixels)
     1 lines     281 ( 0.22%) :       js exit(status,implicit)
     1 lines     279 ( 0.22%) :       js Module_requestFullScreen(lockPointer,resizeCanvas,vrDevice)
     1 lines     278 ( 0.22%) :       js readAsync(url,onload,onerror)
     1 lines     270 ( 0.21%) :       js _glGenTextures(n,textures)
     1 lines     259 ( 0.20%) :       js _glGenBuffers(n,buffers)
     1 lines     256 ( 0.20%) :    asmjs Board::is_valid_move(int, int, int, int) ; cb(a,b,d,e,f)
     1 lines     249 ( 0.20%) :      var applyMemoryInitializer
     1 lines     237 ( 0.19%) :       js abort(what)
     1 lines     230 ( 0.18%) :       js dynamicAlloc(size)
     1 lines     228 ( 0.18%) :       js postRun()
     1 lines     219 ( 0.17%) :       js preRun()
     1 lines     203 ( 0.16%) :       js invoke_iiii(index,a1,a2,a3)
     1 lines     185 ( 0.15%) :    asmjs _sbrk(a) ; tb(a)
     1 lines     185 ( 0.15%) :       js _emscripten_set_mousedown_callback(target,userData,useCapture,callbackfunc)
     1 lines     185 ( 0.15%) :       js _emscripten_set_mousemove_callback(target,userData,useCapture,callbackfunc)
     1 lines     183 ( 0.14%) :    asmjs Board::is_king_in_check(int) ; Ta(a,b)
     1 lines     174 ( 0.14%) :       js jsStackTrace()
     1 lines     172 ( 0.14%) :       js invoke_v(index)
     1 lines     165 ( 0.13%) :       js dynCall(sig,ptr,args)
     1 lines     163 ( 0.13%) :       js Module_createContext(canvas,useWebGL,setInModule,webGLContextAttributes)
     1 lines     162 ( 0.13%) :       js _glBufferData(target,size,data,usage)
     1 lines     161 ( 0.13%) :       js doBrowserLoad()
     1 lines     160 ( 0.13%) :       js readBinary(url)
     1 lines     154 ( 0.12%) :       js writeAsciiToMemory(str,buffer,dontAddNull)
     1 lines     151 ( 0.12%) :       js _glShaderSource(shader,count,string,length)
     1 lines     144 ( 0.11%) :       js _glCreateProgram()
     1 lines     144 ( 0.11%) :       js getCFunc(ident)
     1 lines     140 ( 0.11%) :       js allocateUTF8OnStack(str)
     1 lines     140 ( 0.11%) :       js demangleAll(text)
     1 lines     138 ( 0.11%) :       js _glVertexAttribPointer(index,size,type,normalized,stride,ptr)
     1 lines     138 ( 0.11%) :       js _glBindAttribLocation(program,index,name)
     1 lines     136 ( 0.11%) :       js _glLinkProgram(program)
     1 lines     136 ( 0.11%) :       js addRunDependency(id)
     1 lines     135 ( 0.11%) :       js locateFile(path)
     1 lines     135 ( 0.11%) :       js isDataURI(filename)
     1 lines     132 ( 0.10%) :       js _emscripten_webgl_make_context_current(contextHandle)
     1 lines     130 ( 0.10%) :       js Module_requestFullscreen(lockPointer,resizeCanvas,vrDevice)
     1 lines     126 ( 0.10%) :       js ExitStatus(status)
     1 lines     124 ( 0.10%) :       js _glCreateShader(shaderType)
     1 lines     121 ( 0.10%) :       js warnOnce(text)
     1 lines     119 ( 0.09%) :       js ___setErrNo(value)
     1 lines     118 ( 0.09%) :       js _glBindBuffer(target,buffer)
     1 lines     118 ( 0.09%) :       js alignMemory(size,factor)
     1 lines     117 ( 0.09%) :       js shell_read(url)
     1 lines     115 ( 0.09%) :       js ensureInitRuntime()
     1 lines     110 ( 0.09%) :       js stringToUTF8(str,outPtr,maxBytesToWrite)
     1 lines     107 ( 0.08%) :       js runCaller()
     1 lines     107 ( 0.08%) :    asmjs Board::has_valid_moves(int, int) ; db(a,b,c)
     1 lines     104 ( 0.08%) :       js _emscripten_memcpy_big(dest,src,num)
     1 lines     101 ( 0.08%) :       js _glAttachShader(program,shader)
     1 lines     100 ( 0.08%) :       js Module_setCanvasSize(width,height,noUpdates)
     1 lines     100 ( 0.08%) :       js _glBindTexture(target,texture)
Total size of printed functions: 123389 bytes. (96.90% of all symbols)
```

**Comment by kripken** [comment]
Interesting! I think there's definitely a big need for a tool like this.

Looks like this is asm.js-only? My initial thoughts are that an `em*` tool in the topmost dir should be more general, as well as highly-tested, so something like this might make more sense under `tools/`, I think.

Longer-term, another direction that might be interesting here is to look at [bloaty](https://github.com/google/bloaty), which recently added wasm support. It has pretty nice size usage analysis options. They might be interested to add asm.js support there if we provided a patch, and then a single tool could do both asm.js and wasm (and native binaries too).

cc @floooh, this might interest you.

**Comment by juj** [comment]
Moved to under `tools/`

**Comment by kripken** [comment]
lgtm, thanks.

Travis errors look like some temporary CI issue, can ignore.

**Comment by kripken** [comment]
Looks like this may have been forgotten to merge, merging.

**Pull request merged**
