### PR TITLE
Fix for issue 5226

### PR DESCRIPTION
**Pull request by ImplOfAnImpl**
Here a zero value is added to the list `values` inside `aggressiveVariableEliminationInternal.evaluate` for each variable that was defined but not assigned afterwards (why zero - as I understand, Emscripten never produces local variables, whose initial value is not zero, at least I noticed this assumption in other places in the code).

This change also affected older test data - the line `$1;`, which would produce an empty line previously, now produces `0;`. But, as I understand, aggressiveVariableElimination wasn't intended for the elimination of such expressions, and it's done by other optimization passes anyway.

Test suites run: main, other (got failures in test_legalize_js_ffi and test_crunch, but they were failing without my changes too)

### CODE REVIEW

**Comment by kripken** [comment]
Thanks, this looks correct.

The reason this wasn't an issue until you noticed is that LLVM output is guaranteed to have a value assigned to each variable, before the variable is used. (The `=0` in the `var` statements doesn't count as that, it's just a "type declaration".) So in practice we didn't ever encounter such a variable. But your fix is correct, it's good that the pass handles more general code, not just LLVM.

**Comment by ImplOfAnImpl** [comment]
I see. However, I encountered this problem when compiling C++ code. Perhaps, there is another bug either in the initial JS generation or in an earlier optimization pass.

**Comment by kripken** [comment]
Interesting, then it does sound like another bug then. Perhaps you can find a small C++ testcase showing it?

**Comment by ImplOfAnImpl** [comment]
Ok, I'll try to find it later.

**Comment by ImplOfAnImpl** [comment]
It appeared that the original cause of the problem was this issue - https://github.com/kripken/emscripten-fastcomp/issues/183 (an assignment to `temp` and its actual usage were performed in different chunks of `runPostSets`)

**Comment by kripken** [comment]
Interesting, thanks. Ok good, looks like this is all fixed then.

**Pull request merged**
