### PR TITLE
Remove deprecated ASYNCIFY option (emterpreter-async replaced it)

### PR DESCRIPTION
**Pull request by kripken**

### CODE REVIEW

**Comment by curiousdannii** [comment]
Don't forget the docs. :)

**Comment by kripken** [comment]
Oops, thanks :) Docs updated.

**Comment by curiousdannii** [comment]
Was this officially called deprecated before? The docs just say "experimental" and "not currently worked on". I'd expect that a small number of people are still using it in production. Should it go through an official deprecation stage first, perhaps with a warning when you try to use it?

Removing it probably needs a bigger version bump. I don't know if you're trying to follow semver or not, but it definitely should be at least a minor bump. And a change like this should be announced in the mailing list etc.

**Comment by kripken** [comment]
Maybe you're right, I'll ask on the mailing list.

But the [docs page](https://github.com/kripken/emscripten/wiki/Asyncify) has said this for 2 years:

> This feature is experimental, and not recommended. See the Emterpreter for a more recent option with similar functionality, that is currently supported.

And I've seen no issues filed on it for a very long time.

**Comment by curiousdannii** [comment]
There aren't a lot of projects, at least publicly visible on Github, which currently build with ASYNCIFY: https://github.com/search?l=Makefile&o=desc&q=asyncify&s=indexed&type=Code&utf8=%E2%9C%93

I think you'd be fine to remove it, but for the handful of people still using it, it would probably be nice to them if it's not completely hidden. An idea: would it be possible to make emcc put up a message saying it's been removed if you try to use it? That would be better than it suddenly just disappearing.

**Comment by kripken** [comment]
Good idea, added an error message when the removed option is specified.

**Comment by janjongboom** [comment]
Adding a note here as well, as per #5862. Right now ASYNCIFY is the only way to have both async operations and source maps, which is why I'm using it.

**Comment by kripken** [comment]
I see, thanks. Well, I guess we shouldn't remove it, for now. Eventually we can remove it if someone implements source maps for the emterpreter, or when thread support arrives and we can do async stuff using that.

**Pull request closed without merging**
