### PR TITLE
[proposal] New build system option "EXECUTE_PROCESS"

### PR DESCRIPTION
**Pull request by caiiiycuk**
New build system option "EXECUTE_PROCESS" that allows to execute custom commands after specific build steps. 

I want use this option to run custom llvm passes over emitted bc. This is replacement for previous PR #6421. I think this way is much flexible, because we not limited only with llvm passes and much much easier to test.

In future new steps can be added. For example after producing js I usually run SFE optimizer, it can be added as new AFTER_JS step.

### CODE REVIEW

**Comment by kripken** [comment]
This seems fairly complicated, and I'm not sure I understand the benefit. Can't you instead link to a single `.bc`, then do stuff on that, and afterwards call emcc to compile it?

**Comment by caiiiycuk** [comment]
I agree with you, this look cumbersome and not very useful. This solution came from #6379 I have implementation of llvm pass to remove functions from list, it's very simple and I use it. But, I can't find good way to integrate it into emscripten build system. I already tried cmake and it works fine, btw I want to share this llvm pass in some way. Maybe it's better to create PR into emscripten-fastcomp and integrate this step into linker step?

**Comment by kripken** [comment]
To run your custom pass could a build system do something like this?
```
# Link all the bitcode files and libraries
emcc a.bc b.bc c.bc lib1.so lib2.a -o combined.bc
# Run a special LLVM pass on that
opt -my-special-pass combined.bc -o modded.bc
# Compile to JS
emcc modded.bc -o a.js
```

**Comment by caiiiycuk** [comment]
Yes I use it in this way.

**Comment by kripken** [comment]
Ok, in that case then I think we don't need to add this to emscripten? Unless there's a place on the docs it would make sense to mention it.

**Pull request closed without merging**
