### PR TITLE
Small fix, quotes not needed

### PR DESCRIPTION
**Pull request by nazar-pc**
Not sure how I got those quotes in https://github.com/kripken/emscripten/pull/5371 initially, but with them in place it doesn't actually work as intended, doesn't influence anything

### CODE REVIEW

**Comment by juj** [comment]
Looks good to me. @kripken: do we want to merge this in like this, or add `'` and `"` swallowing to `#if` preprocessor support instead?

**Comment by kripken** [comment]
Strange, that doesn't actually work? I thought that we verified it did in the PR that added those...

I think we should fix `#if` processing, as this is very surprising. We don't seem to have other places with this now, but it seems like we might hit this bug later in the future if we don't fix it.

**Comment by nazar-pc** [comment]
With quotes it doesn't actually work. I found that quotes shouldn't be used initially, but somehow managed to get them into PR.

**Comment by kripken** [comment]
I see, thanks. Ok, I confirmed this was indeed broken. Proposed fix in #5459.

**Comment by nazar-pc** [comment]
Closing this in favor of #5459

**Pull request closed without merging**
