### PR TITLE
Added an implementation of glVertex4f

### PR DESCRIPTION
**Pull request by gabrielcuvillier**
Here is an implementation of glVertex4f, missing from current legacy gl implementation. I needed it for one of my projects.

In theory glVertex3f could be reworked to use that one (like glVertex2f is using glVertex3f), but this add an additional indirection...

### CODE REVIEW

**Comment by kripken** [comment]
Thanks!

For consistency, I think we should either reuse one function for 2,3,4 or have a separate one for each, or explain why 4 is different than the others (if there is a reason). I'd lean towards a separate function for each?

We should add some simple testing to keep this working. Can grep for `glVertex3f` in the test suite and perhaps add to the existing test there. Or a new test may make sense too.

**Comment by gabrielcuvillier** [comment]
I separated the implementations of glVertex* in 3 groups: 2f/2i/2fv, 3f/3i/3fv, and 4f/4i/4fv. The "i" and "fv" versions are using the "f" one of the group.

However, I am not sure about something in the 4fv implementation: while I call glVertex4f, does the **pos: '12'** I use in the fourth argument looks correct?

**Comment by kripken** [comment]
Looks good, thanks! Yeah, the 12 looks correct too.

Still need a test here, and to add yourself to AUTHORS.

**Comment by gabrielcuvillier** [comment]
I added a test for glVertex4f, in browser.test_sdl_ogl test
Do I need to update the reference file (the screenshot), and if so, how do you get an image file from the canvas ?

**Comment by kripken** [comment]
For updating the reference file, you can build it to html outside of the test suite, run it in a browser, and rightclick on the image -> save as. You may need to do `Module.canvas.oncontextmenu = false` in the console.

**Comment by kripken** [comment]
The test failures look like they are caused by this patch. For example when I run `./tests/runner.py browser.test_aniso` locally I see it fail on
```
Assertion failed: `numVertexes` must be an integer.
```

**Comment by gabrielcuvillier** [comment]
Ok, I'll check

**Comment by gabrielcuvillier** [comment]
I fixed the regression. This is because initially glVertex2f called the glVertex3f version, which sets the 3 components (x,y,z, with z=0 if not specified) and not only 2 (x,y) like I did in my first commit.

The crash happens in test_aniso because there is a mix of calls to glVertex2i and glVertex3i within a glBegin/glEnd. As so, there is some alignement error in the final VBO due to mismatched number of components. 

However, I am not sure it is valid to mix glVertex2/3/4 calls within a glBegin/glEnd. Does someone have an idea of what OpenGL spec says ? If it is really the case, then in fact, I should update the code to set 4 components (x,y,z,w) in each glVertex* functions, otherwise the bug will appear again if someone tries to mix glVertex4 with the others...

**Comment by kripken** [comment]
I think it is valid, I see this in the docs:

> When only x and y are specified, z defaults to 0 and w defaults to 1. When x, y, and z are specified, w defaults to 1.

https://www.khronos.org/registry/OpenGL-Refpages/gl2.1/xhtml/glVertex.xml

**Comment by gabrielcuvillier** [comment]
Ah, ok. I have to do some additional fix then

**Comment by gabrielcuvillier** [comment]
Yes it's a mistake, I messed up things in the previous commit - deleted some sdl2 files due to some local tweaks I am working on, restored the files back but with wrong mode. Oops, sorry :)

**Comment by kripken** [comment]
Thanks!

**Pull request merged**
