### PR TITLE
Fix SDL2_Mixer documentation and add a unit test for SDL2_Mixer playing WAV files.

### PR DESCRIPTION
**Pull request by bsurmanski**
The correct flag is "-s USE_SDL_MIXER=2", not "-s SDL_MIXER=2".

USE_SDL_MIXER is consistent with the other emscripten port flags, and is also consistent with the code in the SDL2_Mixer PR. (here: https://github.com/kripken/emscripten/pull/7599)

### CODE REVIEW

**Comment by bsurmanski** [comment]
The test was tested in chrome 71 on macos 10.13. Like the other sdl2_mixer test, I needed to interact with the page before the test started or the audio device would not correctly open.

I tried to follow the pattern in other unit tests. Not sure if you'd rather rename sdl2_mixer.c to sdl2_mixer_ogg.c or something else. Let me know if there is a way that better follows the conventions of the project.

**Comment by kripken** [comment]
Thanks @bsurmanski! Looks good, please just add yourself to AUTHORS before we merge.

**Comment by bsurmanski** [comment]
Done!

**Comment by bsurmanski** [comment]
I realized there might be an issue with SDL2_mixer if the audio context starts before page interaction. We get this message:
**The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page.**

Trying out SDL_mixer (SDL1), it seems that we'll get this same message, but the audio seems to fix itself after interaction. I think that will require a bugfix.

**Comment by kripken** [comment]
Thanks, I believe this is because of recent Chrome changes to autoplay etc. settings. Probably a good idea to open a new issue for investigation.

**Pull request merged**
