### PR TITLE
Fix loading from file in SDL_mixer

### PR DESCRIPTION
**Pull request by MurphyMc**
This resolves a regression in Mix_LoadWAV_RW() which was introduced in
commit 789657c5ed8f.

### CODE REVIEW

**Comment by kripken** [comment]
Thank you, this looks good. Can you please add a test for it, so it never regresses again? Might be simplest to add to an existing SDL mixer test, one of `test_sdl*` in `tests/test_browser.py` (or maybe `test_interactive.py`).

**Comment by MurphyMc** [comment]
How about this?  It tweaks test_interactive's sdl_audio test in a way that should be functionally equivalent, but when the test is performed using SDL2, it hits the bug.

**Comment by kripken** [comment]
Thanks, test looks good too. Last thing, please add yourself to AUTHORS.

**Comment by MurphyMc** [comment]
Looks like AUTHORS went stale.  Let me know if you want me to rebase and update the PR.

**Comment by kripken** [comment]
No need to rebase, this gave me a chance to try github's online merge conflict fixing tool :) Works pretty well.

**Pull request merged**
