### PR TITLE
Update docs about current installation issues

### PR DESCRIPTION
**Pull request by kripken**
* #6275 - github changes with SSL force a newer python version. Update docs to mention that and the proper version number, based on discussion in that issue.
 * #6288 - just mention getting he emsdk script itself from github, not the binary releases which we don't have a working solution for atm. These are basically the instructions that the wasm website uses anyhow, http://webassembly.org/getting-started/developers-guide/

### CODE REVIEW

**Comment by kripken** [comment]
Please give feedback on these docs. To see the difference, the new version with the changes is up at

http://kripken.github.io/emscripten-site/docs/getting_started/temp-downloads.html

(the old one, for comparison, is still at http://kripken.github.io/emscripten-site/docs/getting_started/downloads.html )

**Comment by eska014** [comment]
Some suggestions:
- Mention that emsdk can be downloaded from Github without git using the *Clone or download* button. Since it's a build tool, there's bound to be non-developers downloading Emscripten
- It seems there's binaries available for Linux, but instructions say

**Comment by kripken** [comment]
@eska014 Thanks, good suggestions! Updated the PR with those.

**Comment by dcodeIO** [comment]
Just gave it a try:

- Downloaded from GitHub without Git as mentioned in the comment above
- `emsdk update`, `emsdk update-tags`, `emsdk install latest`
- Downloads sdk-1.37.35 (said 1.37.36 is latest? windows builds again?), in this order: clang (e1.37.35), node (8.9.1), python (2.7.13.1), WinPython (2.7.13.1Zero), java (8.152), emscripten (1.37.35)
- `emsdk activate latest`
- Tried building Binaryen, **works**

Nits:

- When running `emsdk activate XY` the first time, it appears redundant to also run `emsdk_env.bat`. BUT: Might be better to have it this way so users know that it exists, when not running activate the second time.

**Comment by Kuranes** [comment]
Note Tried on WSL (windows subsystem for linux) on windows 10, 
thus had to follow the linux platform guidelines and it worked without any problem. 
Might be worth noting it somewhere (in windows section)

**Comment by kripken** [comment]
@dcodeIO thanks! yeah, hopefully that warning would go away with 1.37.36. Odd it didn't get it for you - maybe it wasn't built yet, though. It should be now, if not, there's a problem on the bot.

@Kuranes good idea, thanks, added a mention of windows subsystem for linux. Not sure how much to encourage people to use it (not familiar with it myself), but it's a definitely good option to have.

**Comment by dcodeIO** [comment]
Still looking like this after another `emsdk update`:

```
The following precompiled SDKs are available for download: (Run "./emsdk update" to pull in the latest list)
         sdk-nightly-1.37.34-2018_02_17_19_38-64bit
         sdk-nightly-1.37.34-2018_02_17_21_02-64bit
         sdk-1.30.0-64bit
         sdk-1.34.1-64bit
         sdk-1.35.0-64bit
         sdk-1.37.1-64bit
         sdk-1.37.34-64bit
    *    sdk-1.37.35-64bit              INSTALLED
```

**Comment by kripken** [comment]
@dcodeIO what OS is that on?

**Comment by dcodeIO** [comment]
Windows 10 64-bit

**Comment by kripken** [comment]
@dcodeIO thanks, might be windows bot problems then. I restarted the process there and it says it uploaded the build, does it work for you?

**Comment by dcodeIO** [comment]
Yes, thanks, it shows up now!

**Comment by kripken** [comment]
Great!

Ok, looks like the updates in this PR make sense to do, merging.

**Pull request merged**
