### PR TITLE
Add llvm cos and sin intrinsic functions

### PR DESCRIPTION
**Pull request by ashleysommer**
Was getting errors stating that llvm_cos_f32 and llvm_sin_f32 are unimplemented.
This commit fixes that.
Added llvm cos and sin intrinsic functions to library.js

### CODE REVIEW

**Comment by kripken** [comment]
Looks good, thanks. Please just add a little test in `test_llvm_intrinsics` in `tests/test_core.py` (which uses `tests/core/test_llvm_intrinsics.*`).

**Comment by kripken** [comment]
Meanwhile `sin` was added in another PR, f1ab53a869c44440f0c58a2d10d1ed252448fa1d. Looking at how the test was added there might help here for `cos`.

**Comment by codewiz** [comment]
FWIW, I got undefined symbol error on llvm_cos_f32 while building a rust project for the asmjs-unknown-emscripten target with emscripten 1.36.14. I applied this patch and it fixed the issue.

**Comment by kripken** [comment]
This is on incoming (1.37.9), looks like we added it meanwhile in another PR.

**Pull request closed without merging**
