### PR TITLE
Add support for llvm.sin.f(32|64) intrinsics

### PR DESCRIPTION
**Pull request by Maher4Ever**
This adds support for the llvm.sin.f(32|64) intrinsic to Emscripten. More details can be found in the issue kripken/emscripten#4338. The accompanying change to fastcomp is in pull request kripken/emscripten-fastcomp#143

### CODE REVIEW

**Comment by kripken** [comment]
Looks good, thanks.

Please rebase (and then `push -f` to this branch) to get rid of the merge commit.

Also please add a test. Can grep for the similar functions next to it, in `tests/`, to find the relevant test that I think you can just add a few lines in, if I remember correctly.

**Comment by Maher4Ever** [comment]
Thanks about the rebase tip. It makes the history so much cleaner! 

I greped for each of the following strings inside `tests/` but found nothing:

- `llvm_log` and `llvm.log`
- `llvm_sqrt` and `llvm.sqrt`
- `llvm_pow` and `llvm.pow`
- `llvm_exp` and `llvm,exp`

Are you aware of a more specific folder or file where I should find the tests?

**Comment by kripken** [comment]
Looks like the relevant tests are in `tests/core/test_llvm_intrinsics.in` and `.out`.

**Comment by Maher4Ever** [comment]
Done :)

**Comment by kripken** [comment]
Thanks!

**Pull request merged**
