### PR TITLE
SDL2_mixer (see #5995)

### PR DESCRIPTION
**Pull request by superzazu**
This PR is based on #5995, with a few minor changes:

- rebased on "incoming" and resolved conflicts
- updated SDL2_mixer repo to [emscripten-ports/SDL2_mixer](https://github.com/emscripten-ports/SDL2_mixer)
- changed SDL2_mixer version tag from 2.0.0 to 2.0.1
- added a browser test

Let me know if anything's not OK, I'm still new to Emscripten.

### CODE REVIEW

**Comment by superzazu** [comment]
I notice the "test-browser-firefox" test failed. I tested the two failed tests (test_sdl2_mixer and test_sdl2_timer) and they both work on my machine (Mac) with the following browsers:

- Firefox 63.0.3
- Chrome 70.0.3538.110
- Safari 12.0.1 (14606.2.104.1.1)

I even launched the two tests with Firefox 62.0.2 (which the test suite uses) with success.

**Comment by kripken** [comment]
Thanks @superzazu! Everything looks good, just 2 last things:

 * Please add a line to `test_embuilder` (in `tests/test_sanity.py`).
 * Please add yourself to `AUTHORS`

The two browser test failures look like they could be random, but failing in the mixer test is suspicious, let's see if the next run passes.

**Comment by kripken** [comment]
Perfect, thanks @superzazu!

**Comment by bsurmanski** [comment]
I ran the SDL2_Mixer test (by running `./runner.py interactive.test_sdl2_mixer`) using a commit from December 27th (https://github.com/kripken/emscripten/commit/3ab8bc234111dcea18f3f03bdca14ceb397103ba).

I ran on MacOS 10.13.6 in both Chrome 71.0.3578.98 and Safari 12.0.2 (13606.3.4.1.4) with the same result:

It doesn't seem to work for me. It looks like the sound loads (using Mix_LoadWAV) without an error (changing to a garbage file path errors out), but playing it with Mix_PlayChannel produces no sound and causes Mix_Playing(-1) to get stuck at true. (causing the test to timeout after ~70 seconds. Note the sound being played is about 3 seconds).

Am I missing something? My understanding is that merging into incoming means the feature (presumably) works?

**Comment by bsurmanski** [comment]
Ahhh, I figured out the problem. In the javascript console I got the following error:
"""
The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://goo.gl/7K7WLu
(anonymous) @ page.js:1101
"""

After running the test and clicking on the page before the test launched the test ran successfully (with the expected sound played). Perhaps SDL_Init(SDL_INIT_AUDIO) or Mix_OpenAudio(...) should return an error in this case?

**Pull request merged**
