### PR TITLE
Use async XHR + iframe for browser tests

### PR DESCRIPTION
**Pull request by saschanaz**
Async XHR will prevent blocking browser process so long, especially when building libc. Iframe will remove any need to disable popup blocker.

### CODE REVIEW

**Comment by kripken** [comment]
Oh, nice! This works better than I expected already. I tested this out, some notes:

 * It would be nice if the iframe were large enough to see the test running. Useful for debugging. Also that the other prints don't keep pushing it down the page until it's hidden.
 * We should maybe not do this for the interactive tests, like `interactive.test_sdl_mousewheel` - although maybe they could work, if the iframe were big enough?
 * Some tests open their own window, like the emrun ones (which have to). They don't close it, which means the focus is lost from the main test tab. Perhaps we could just put those at the end by renaming them ;) `test_zzz_emrun` etc.
 * When tests fail or hang, they may leave their window open. We should make sure that doesn't make all the tests afterwards fail (normally there would just be some open windows, but after this change, I'm not sure). I tested this and I didn't see a problem, though.
 * Some tests might not work in an iframe. I was worried about tests with input, but those seem mostly ok. But e.g. `browser.test_sdl_quit` fails for me, maybe because it's trying to close the window?

**Comment by saschanaz** [comment]
Tried some styling on the harness page, should be better for debugging and interactive testing.

**Comment by saschanaz** [comment]
>Some tests open their own window, like the emrun ones (which have to). They don't close it, which means the focus is lost from the main test tab. Perhaps we could just put those at the end by renaming them ;) test_zzz_emrun etc.

Hmm yes, it can be annoying (while it's not a new behavior).

>When tests fail or hang, they may leave their window open. We should make sure that doesn't make all the tests afterwards fail (normally there would just be some open windows, but after this change, I'm not sure). I tested this and I didn't see a problem, though.

The iframe forces those tests to leave their window open because of iframe limits, so it should be okay.

>browser.test_sdl_quit fails for me, maybe because it's trying to close the window?

Probably, but I will investigate more.

**Comment by saschanaz** [comment]
I modified sdl_quit.c to use `unload` event instead of actual `window.close()` and the test now succeeds.

**Comment by kripken** [comment]
Nice!

I am still worried about tests like `interactive.test_sdl_mousewheel` - the lower third or so is hidden, which is where the instructions are. Perhaps we can

 * Remove the lines where we print `opened test frame X`? I'm not sure they are that useful. Then almost all the space goes to the test.
 * Also, if we add a border around the iframe, it would be clearer what is the test and what is the test runner.
 * Perhaps the first line ("Running tests...") could be in a normal size font, to not use more vertical space. Also, maybe it could say `Running test X / Y` and update X as the tests run? If that's not easy to do (I'm not sure there's a good way to get Y, the number of tests), no big deal.

**Comment by saschanaz** [comment]
Removed `opened test frame X` part.

>If that's not easy to do (I'm not sure there's a good way to get Y, the number of tests)

We cannot know Y value as we don't know how many `run_browser` calls are in a given test. (There can be multiple, e.g. `test_preload_file`)

**Comment by kripken** [comment]
Looks great. Do all the tests pass? This looks almost ready to me if so. Last things:

 * Please rename the emrun tests to `test_zzz_emrun`, so they run at the end, unless we have a better solution for them leaving the window open?
 * How about doing
````
-<span>Running test <span id="count"></span>...</span>
+<span style="background-color: #79f">Running test <span id="count"></span>...</span>
````
? That makes the test runner noticeably different from the test in the iframe. I also tried to add a border around it, but it wastes space, so I'm thinking a color difference is better.

**Comment by saschanaz** [comment]
Tried your diff, and looks good :+1:

**Comment by kripken** [comment]
Great, thanks! Looks good when I run the tests locally too.

**Pull request merged**
