### PR TITLE
functions for complex division, multiplication

### PR DESCRIPTION
**Pull request by brian-armstrong**
recreated PR for https://github.com/kripken/emscripten/pull/3937 against `incoming` branch

i realized i needed division after all, so i went ahead and added those, too :)

modifying `create_libc` seems to be the way to go. this will give us these symbols in the normal and pthread cases, and the `libc.symbols` provided with emscripten already references `_muldc3' et al, so nothing more is needed to tell system_libs about these symbols

### CODE REVIEW

**Comment by brian-armstrong** [comment]
re fastLong.js, i decided to pick what seems to be the lesser of two evils. i have profiled my project and haven't seen any of these functions taking much time. i'm not very confident that i could handroll these correctly, and it turned out to be pretty easy to add them to system_libs.py

**Comment by brian-armstrong** [comment]
@kripken @juj How do you feel about this approach? As far as I can tell, this resolves the missing symbols and supplies the correct functions.

**Comment by kripken** [comment]
1. The libc symbols file has `U` though, for undefined, so we can't just add to libc without modifying that. But I think it would be cleaner to create a separate `compiler_rt` library, as these methods are not actually part of libc, which could be confusing.
2. Need the license/copyright file from compiler-rt in the same dir as the new files.

**Comment by kripken** [comment]
Sorry for the delay here, btw, I was on a trip.

**Comment by juj** [comment]
Looks good to have a specific directory `system/lib/compiler-rt` with all the code from that project. Agree that would be good to create a custom library target `compiler-rt` as well to contain only these, and not piggyback on the `libc` build. You can use `llvm-nm` tool to generate the symbol file to avoid having to write it by hand.

**Comment by brian-armstrong** [comment]
looks like this branch is completely hosed. it sat around long enough that i forgot what was going on, and now i'm not really sure how to unrot it. take 3!

**Pull request closed without merging**
