### PR TITLE
Emscripten toolchain profiler, part 2/2

### PR DESCRIPTION
**Pull request by juj**
Add profiling blocks to toolchain operation to track the time spent in different parts of the toolchain.

### CODE REVIEW

**Comment by aidanhs** [comment]
Just a drive-by suggestion, but might it be worth doing this with function annotations where possible, rather than context managers?

Regardless, any review will probably want to use https://github.com/kripken/emscripten/pull/4566/files?w=1 to ignore whitespace changes.

**Comment by aidanhs** [comment]
The examples in the previous PR look pretty cool. Could you add "To zoom in, grab with mouse from either the far left or right ends of the blue/purple background rectangle, and drag the selection area smaller." (from the the previous PR) to the top of the results page so users know what to do?

**Comment by kripken** [comment]
1. We already have the `log_time` stuff in emcc.py, which this seems to parallel (using the same names). Are those coordinated? Do we need both?
2. Is there any runtime overhead to this PR? 
3. Why are there some `ToolchainProfiler.record_process_exit` calls, but not all over? And why in an except block (in `js_profiler.py`) and not a finally block?

**Comment by juj** [comment]
Hey, sorry for the delay, had trouble managing time to context switch back to finishing this.

Thanks @aidanhs for the suggestions. Added that help text, definitely needs that. I'm not quite sure about function annotations and how they would improve in this case.

> We already have the log_time stuff in emcc.py, which this seems to parallel (using the same names). Are those coordinated? Do we need both?

They are almost the same, except that the `log_time` stuff does not follow a hierarchical pattern, which the toolchain profiler does. I did not want to remove the `log_time` code in favor of this, thinking if you care about keeping the `log_time` structure in their exact spots. The toolchain profiler does not print times in stdout. It could, but there could be a much larger volume of prints if all locations did that, so decided to keep them separate.

> Is there any runtime overhead to this PR? 

If profiling is not active, there isn't. The profiling blocks call to `__enter__` and `__exit__` blocks that are no-ops ([not even a single `if()` check](https://github.com/kripken/emscripten/blob/incoming/tools/toolchain_profiler.py#L204)).

> Why are there some ToolchainProfiler.record_process_exit calls, but not all over? And why in an except block (in js_profiler.py) and not a finally block?

I presume this meant `js_optimizer.py` - the code wants to exit to an uncaught exception in error case, instead of a `sys.exit`, so didn't want to change that semantics. If I used a finally block, I'd have to have a temp variable that stores the returncode, and then passes that through, which would look clumsy. Changed the code site to look symmetric with its call to `record_process_exit`. Wrote up documentation about the profiler and added to this PR, that highlights how the semantics of exiting a Python script works: https://github.com/kripken/emscripten/pull/4566/files#diff-dfb9897077e0be484e3a0702e245032bR57.

**Comment by aidanhs** [comment]
> I'm not quite sure about function annotations and how they would improve in this case.

Urgh, I meant decorators. They'd reduce diff size/code rightwards drift when you want to treat whole functions as a block. E.g. consider `calculate_reachable_functions`, where every line of code has been put within the context manager. Instead you could define a function decorator like

```
import functools
def toolchainprofiled_func(name):
    def decorator(func):
        @functools.wraps(func)
        def wrapper(*args, **kwargs):
            with ToolchainProfiler.profile_block(name):
                func(*args, **kwargs)
        return wrapper
    return decorator
```

(the functools.wraps is optional) and then you can easily apply it to any function with

```
@toolchainprofiled_func('calculate_reachable_functions')
def calculate_reachable_functions(infile, initial_list, can_reach=True):
    [...]
```

and it should do the right thing (though I've just written the code out without testing). One could imagine making this decorator a static method on `ToolchainProfiler` so it'd be `@ToolchainProfiler.profile_func('blah')` (with the contents of the method being the same). If you wanted to be fancy you could also automatically pluck the function name from the passed in function.

**Comment by juj** [comment]
Ah, I see. That sounds like a good idea, though I'll look at that later if we start to accumulate more custom blocks, there's not too many of them right now.

**Comment by kripken** [comment]
lgtm, but please do some benchmarking to be sure that the cost, which should be 0 when not profiling, is actually 0 when not profiling.

**Comment by juj** [comment]
Ok, rebuilt my 3D engine without this PR, and with this PR (but with profiling disabled), the timings come out as

    without: 5m37.456s
    with, but profiling disabled: 5m38.972s
    with and profiling enabled: 5m41.264s

**Pull request merged**
