### PR TITLE
Added possibility to inject canvas container for fullscreen

### PR DESCRIPTION
**Pull request by zobertke**

### CODE REVIEW

**Comment by kripken** [comment]
First thing, we need prs to be to incoming, and this code changed recently, so it might need rebasing.

**Comment by kripken** [comment]
But maybe @juj wants to take a look before you do that work, for general feedback.

**Comment by juj** [comment]
I think I'd actually favor killing the library_browser code for entering and exiting fullscreen mode, and always using the HTML5 API to manage fullscreen, since that does not add/remove elements to the DOM, but only uses CSS styles to unify the per-browser differences that exist in fullscreen mode handling. Commented in #4370 about this, does the HTML5 API solve the issue for you?

The only trouble is that the HTML5 API is bloated due to not currently having efficient dead code elimination (PR #3298 attempts to address that, but I don't have a good solution to finish that yet), and that the HTML5 API is not exported to handwritten JS by default. Though I believe we'd like users to export the identifiers manually anyways.

**Comment by zobertke** [comment]
Yes, actually that was the way to go. See https://github.com/kripken/emscripten/issues/4370#issuecomment-223328801
Thanks for the suggestion.

**Pull request closed without merging**
