### PR TITLE
Bool convenience macros (forgot to update docs)

### PR DESCRIPTION
**Pull request by haraldreingruber**
Updated docs as well.
(Extends #4243)

### CODE REVIEW

**Comment by kripken** [comment]
Looks good, thanks. Can you please rebase on incoming and push -f to this branch, to get rid of the merge commit?

Also looks like you might be in AUTHORS yet?

**Comment by haraldreingruber** [comment]
Done. Shall I create another PR for adding myself to the AUTHORS list?

**Comment by kripken** [comment]
No need for another PR, here is fine.

**Comment by haraldreingruber** [comment]
Done.

**Comment by kripken** [comment]
Thanks!

**Pull request merged**
