### PR TITLE
Clarifications on switch elimination and optimization assumptions

### PR DESCRIPTION
**Pull request by aidanhs**
This PR contains only *two* commits - please merge after #3732.

In #2003 @kripken stated that "The issue was we let variables be eliminated between switch cases, which is fine unless they have a dependency on a non-safe variable".

I'm not convinced this is true. In the testcase I came up with,
```
function testfn($in) {
 $in = $in | 0;
 var a = 0;
 switch ($in | 0) {
  case 0:
   a = 6;
   break;
  case 1:
   print(a);
   break;
 }
}
```
when optimised with `asm eliminate` is optimised to
```
function testfn($in) {
 $in = $in | 0;
 switch ($in | 0) {
 case 0:
  break;
 case 1:
  print(6);
  break;
 }
}
```

This may be valid when compiling from C (where the initial vars are likely UB) but someone handwriting asm.js may well be a little surprised.

### CODE REVIEW

**Comment by kripken** [comment]
Your analysis is correct - the optimizer does **not** treat `var a = 0;` as an assignment. It's an asm.js *declaration*. It's a fact that the way asm.js does a declaration also does an actual assignment, but only because we didn't find a better way...

So yes, this is related to UB in C and LLVM. We assume the value must be written to, by an assignment that is not the declaration, before use.

I understand this might be confusing to people hand-writing asm.js, but hopefully once the point that an asm.js declaration is not an assignment is absorbed, it should be clear.

Note that this isn't the only place this happens. We use this assumption in other places as well, although I can't think offhand of one.

In general I'd be fine to change this just for clarity, but it does affect performance. There are large switches in sqlite, lua, etc. where we need this optimization to happen to get good performance. it might be interesting to run the benchmark suite with and without this, but last I measured it it was noticeable.

**Comment by aidanhs** [comment]
That's interesting - if I understand correctly, this means that the optimizer can perform some optimizations that browsers cannot, because browsers need to do the same thing in and out of asm.js mode whereas the optimiser can take advantage of asm.js-UB.

If this is correct, I'll have a think about the best way to express this in a comment somewhere.

**Comment by kripken** [comment]
Yes, that's true - we know the output was from LLVM, and should not have any use before stores, so we can assume a store occurs (aside from the declaration `=0`) before any read, and browsers can't make that assumption.

**Comment by aidanhs** [comment]
Ok, I've updated this to just be a doc fix with warnings about the assumptions the optimizer makes. While it's a little cryptic (and I would welcome improvements) I figure it's better than having a comment verging on incorrect - "We cannot track from one switch case into another" is a lie if not qualified!

**Comment by kripken** [comment]
Looks good aside from that comment.

**Comment by aidanhs** [comment]
Removed reference to closure compiler.

**Pull request merged**
