### PR TITLE
Add sdl2 timer test

### PR DESCRIPTION
**Pull request by aidanhs**
Requires https://github.com/emscripten-ports/SDL2/pull/30

### CODE REVIEW

**Comment by kripken** [comment]
The dependent PR was merged, and I tagged `version_11` on ports, so updating the port to that version should make this work.

**Comment by aidanhs** [comment]
Bumped sdl2 version

**Comment by kripken** [comment]
Thanks. Did you verify that the test passes?

**Comment by aidanhs** [comment]
Yup, seems good to me.

**Comment by kripken** [comment]
Great, thanks!

**Pull request merged**
