### PR TITLE
Fix tar.bz2 logic for checking if a port needs recompile

### PR DESCRIPTION
**Pull request by ebraminio**

### CODE REVIEW

**Comment by kripken** [comment]
Can you please merge current incoming into this branch? It now includes the sanity tests on CI, which will check the code being modified here.

**Comment by ebraminio** [comment]
Done, lets see

**Comment by kripken** [comment]
Looks good on tests, thanks!

**Comment by ebraminio** [comment]
Thank you @kripken! Updated the other PRs to see if they have any chance for merge.

**Pull request merged**
