### PR TITLE
Remove <?xml before the SVG in shell.html

### PR DESCRIPTION
**Pull request by Grahack**
This makes it valid HTML.

### CODE REVIEW

**Comment by kripken** [comment]
Looks good, thank you. Can you please just add yourself to AUTHORS?

**Comment by Grahack** [comment]
I don't think that such a change makes me an author!
But if you insist and if this is the way you work then I'd be glad to proceed.
Since I don't have all my tools handy would you allow me to do this in a separate PR?

**Comment by Grahack** [comment]
I don't think that such a change makes me an author!
But if you insist and if this is the way you work then I'd be glad to proceed.
Since I don't have all my tools handy would you allow me to do this in a separate PR?

**Comment by Grahack** [comment]
Done.

**Comment by kripken** [comment]
Great, thanks.

Yes, this is a fairly minor change, but still, it's good to have everyone that contributes to `src/` in the list of AUTHORS.

This is ready to merge to incoming, but should wait a little due to  the process of merging incoming to master which is ongoing this week. I'll probably merge it in a week.

**Comment by kripken** [comment]
Merged to incoming, thanks again!

**Pull request closed without merging**
