### PR TITLE
Support python 2 and 3 in emcc

### PR DESCRIPTION
**Pull request by kripken**
Implements https://github.com/kripken/emscripten/issues/3872#issuecomment-151115726

### CODE REVIEW

**Comment by kripken** [comment]
Viewing the diff in `-w` is much easier, as there is an indentation change here...

**Comment by kripken** [comment]
Well, also the file moved from `emcc` to `emcc.py`, so must `diff -w` between the old and the new...

**Comment by juj** [comment]
Thanks for working on this!

The change looks good to me. Perhaps to be idiomatic, it would be best to route return codes through, so line 9 in `emcc` would be `sys.exit(emcc.run(sys.argv))` instead of just `emcc.run(sys.argv)`? Also, line 1829 of `emcc.py` would be `sys.exit(run(sys.argv))`? And line 1827 of `emcc.py` would be  `  return 0`?

**Comment by kripken** [comment]
I don't think those are needed. If `emcc.py` hits an error, it calls `exit` with the code, in which case `emcc` would exit with that code - they are in the same process, there is no spawning on line 9. And, `run` has no return value for the same reason. And 0 is the default return value, if we return nothing, it gets emitted.

**Comment by kripken** [comment]
review ping

**Comment by juj** [comment]
Oh sorry for the delay. That sounds ok, given that we don't do any returns anywhere in `emcc.run()` anywhere else either.

**Comment by kripken** [comment]
Re-did this as it no longer applies, and I found slightly better ways to do some things. Pushed to incoming.

@juj, any chance you can take a look at why 2 of the 3 bots are down? Would be good to see this tested cross-platform.

**Comment by juj** [comment]
Ops, sorry, Linux had hung and Windows had auto-restarted on updates(?). Restarted the client slaves on both.

**Pull request closed without merging**
