### PR TITLE
Run the opt with llvm_opts with wasm backend too

### PR DESCRIPTION
**Pull request by sbc100**
Also, path opt level to llc.

I'm not sure why this was not done before but
it looks like there is some optimization we
have been missing out on here.

### CODE REVIEW

**Comment by kripken** [comment]
Ah, I think that workaround was because in fastcomp we need to tell the optimizer not to autovectorize, and couldn't find a way to tell it through clang. (I suspect in the wasm backend that's all off anyhow, or properly defined in the arch definition or such.)

**Comment by sbc100** [comment]
As far as I can tell the current code for wasm backend doesn't passs any -O flags to llc or to opt.

Should I split this change and at least pass the -O flag to llc correctly?

**Comment by sbc100** [comment]
OK closing if favor of #6770 for now

**Comment by kripken** [comment]
Yeah, not to opt, but the `-Ox` is passed to clang, which does it there. I verified we do that in the llvm backend path:
```
EMCC_DEBUG=1 EMCC_WASM_BACKEND=1 LLVM=/home/alon/Dev/llvm/build/bin ./emcc tests/hello_world_em_asm.c  -O3
DEBUG:root:PYTHON not defined in /home/alon/.emscripten, using "/usr/bin/python"
DEBUG:root:EMCC_WASM_BACKEND tells us to use wasm backend
WARNING:root:invocation: ./emcc tests/hello_world_em_asm.c -O3  (in /home/alon/Dev/emscripten)
WARNING:root:LLVM version appears incorrect (seeing "5.0", expected "7.0")
DEBUG:root:Checking JS engine ['/home/alon/Downloads/node-v8.9.3-linux-x64/bin/node']
INFO:root:(Emscripten: Running sanity checks)
DEBUG:root:compiling to bitcode
DEBUG:root:emcc step "parse arguments and setup" took 0.52 seconds
DEBUG:root:compiling source file: tests/hello_world_em_asm.c
DEBUG:root:running: /home/alon/Dev/llvm/build/bin/clang -target wasm32-unknown-unknown-wasm -D__EMSCRIPTEN_major__=1 -D__EMSCRIPTEN_minor__=38 -D__EMSCRIPTEN_tiny__=6 -D_LIBCPP_ABI_VERSION=2 -D__EMSCRIPTEN__ -Dunix -D__unix -D__unix__ -Werror=implicit-function-declaration -nostdinc -Xclang -nobuiltininc -Xclang -nostdsysteminc -Xclang -isystem/home/alon/Dev/emscripten/system/include/libcxx -Xclang -isystem/home/alon/Dev/emscripten/system/lib/libcxxabi/include -Xclang -isystem/home/alon/Dev/emscripten/system/include/compat -Xclang -isystem/home/alon/Dev/emscripten/system/include -Xclang -isystem/home/alon/Dev/emscripten/system/include/SSE -Xclang -isystem/home/alon/Dev/emscripten/system/include/libc -Xclang -isystem/home/alon/Dev/emscripten/system/lib/libc/musl/arch/emscripten -Xclang -isystem/home/alon/Dev/emscripten/system/local/include **-O3** tests/hello_world_em_asm.c -Xclang -isystem/home/alon/Dev/emscripten/system/include/SDL -emit-llvm -c -o /tmp/tmp_M0ShZ/hello_world_em_asm_0.o
```

**Pull request closed without merging**
