### PR TITLE
Fix Runtime.stackSave etc. in wasm async compilation mode

### PR DESCRIPTION
**Pull request by kripken**
We had an old hack there, which broke as it didn't have the extra wrapper stuff we need for the exports in async mode. This removes the hack and adds proper testing.

### CODE REVIEW

**Comment by gouletr** [comment]
Verified this works in Firefox Nightly latest update.

Not sure if its related or anything, but it is crashing in Chrome Canary latest update. Might be a bug on their side.

**Comment by kripken** [comment]
@gouletr would be good to file a testcase with them, if you haven't already. cc @dschuff 

Meanwhile I see that enabling sync test mode hits a bunch of tests written in a non-sync manner. I am adding a `@sync` generator to tag those tests. Eventually perhaps we should rewrite them.

**Comment by gouletr** [comment]
@kripken yes I can file a test case to them, I haven't done it before, do you know where's the right place for this?

**Comment by kripken** [comment]
Not sure for that type of content, I'll connect you to @dschuff on email.

**Comment by asRIA** [comment]
Hi @kripken, we found this issue crucial for us to go with Wasm demo, testing witho our samples has prove it works. Is there any chance to pull this in soon?

**Comment by kripken** [comment]
@asRIA: sure, I think it's ok to merge it in now. Looks like no one had any concerns, and with you we now have two confirmations it works.

**Pull request merged**
