### PR TITLE
Update WebVR support to the latest API version

### PR DESCRIPTION
**Pull request by line0**
This PR implements the semi-recent changes to the [WebVR specification](http://mozvr.github.io/webvr-spec/webvr.html):
 * a [new](https://github.com/MozVR/webvr-spec/commit/b5c0863464b85bad8954b9285eca344b0f34fea2) _[VREyeParameters](http://mozvr.github.io/webvr-spec/webvr.html#vreyeparameters)_ interface now bundles the FOVs, RenderRect and EyeTranslation parameters required for stereoscopic rendering
 * `PositionSensorVRDevice:zeroSensor()` is now `PositionSensorVRDevice:resetSensor()`
 * `PositionsSensorVRDevice:getState()` [no longer accepts](https://github.com/MozVR/webvr-spec/commit/8b71ecece26a82b7ee8ebc1193b2123082ebe11c) a _timeOffset_ argument. In its place, a `PositionSensorVRDevice:getImmediateState()` method [has been added](http://mozvr.github.io/webvr-spec/webvr.html#positionsensorvrdevicemethods)

Additional changes:
* a method to query the name of a VR device has been added to the emscripten WebVR API
* some additional debug output has been added to the WebVR test

The updated _interactive.test_vr_ test was run to verify the changes work.

### CODE REVIEW

**Comment by kripken** [comment]
Emscripten bits look fine to me, but I don't know much about WebVR - @vvuk ?

Please add yourself to AUTHORS.

**Comment by line0** [comment]
> Please add yourself to AUTHORS.
Done. 

I also added some more debug output to the test to check whether or not the `hasPosition` and `hasOrientation` flags are set for position sensor data. The chrome build i tested this with didn't set these properties at all when using an oculus rift. On Firefox everything works as expected, though.

**Comment by kripken** [comment]
@vvuk, ping?

**Comment by vvuk** [comment]
Sorry, missed this!  This looks good, thanks for doing the update @line0!

**Comment by kripken** [comment]
Great, merged. Thanks @line0!

**Pull request merged**
