### PR TITLE
fix parse header files from cmdline error (#5495)

### LINKED ISSUE #5495: Difficulties with tools/gen_struct_info.py
I've tried to use this script for defines, but got some issues.
The first one was following:
```
Traceback (most recent call last):
  File "/media/Data/emsdk-portable/emscripten/1.37.19/tools/gen_struct_info.py", line 524, in <module>
    main(sys.argv[1:])
  File "/media/Data/emsdk-portable/emscripten/1.37.19/tools/gen_struct_info.py", line 517, in main
    defines.extend(data['defines'])
AttributeError: 'dict' object has no attribute 'extend'
```
When I've changed `dict` to `list` I've got following:
```
Traceback (most recent call last):
  File "/media/Data/emsdk-portable/emscripten/1.37.19/tools/gen_struct_info.py", line 525, in <module>
    main(sys.argv[1:])
  File "/media/Data/emsdk-portable/emscripten/1.37.19/tools/gen_struct_info.py", line 521, in main
    struct_info = inspect_code(header_files, cpp_opts, structs, defines)
  File "/media/Data/emsdk-portable/emscripten/1.37.19/tools/gen_struct_info.py", line 346, in inspect_code
    for name, type_ in defines.items():
AttributeError: 'list' object has no attribute 'items'
```

As Python is not the language I know, can't fix it myself.
@ngld, maybe you can help with this as the author of original PR that introduced this script?

The source files I'm trying to extract defines from: https://github.com/rweather/noise-c/blob/6243290cf66b6b518ed0c0ca91b54a1ec68f6b78/include/noise/protocol/constants.h

### PR DESCRIPTION
**Pull request by muzuiget**
This PR fix #5495

### CODE REVIEW

**Comment by kripken** [comment]
Hmm, I'm not sure what this does, and the relevant issue seems to have been closed. What concrete problem does this fix?

**Comment by muzuiget** [comment]
#5495 didn't fix the issue. from this script help, you can pass two type of format, .json file or r.h file. If your pass .h file like this

```
./gen_struct_info.py example.h
```

It will throw an error

```
AttributeError: 'dict' object has no attribute 'extend'
```

That is because the variable `defines` is a `dict` type. 

```
   defines = {}
   
   for header in args.headers:
     if header[-5:] == '.json':
       # This is a JSON file, parse it.
       parse_json(header, header_files, structs, defines)
     else:
       # If the passed file isn't a JSON file, assume it's a header.
       header_files.append(header)
       data = parse_header(header, cpp_opts)
       structs.update(data['structs'])
       defines.extend(data['defines']) // defines is a dict this branch always fail.
```

**Comment by muzuiget** [comment]
I was finding a way to map C struct to JS object, and found this [issue comment](https://github.com/kripken/emscripten/issues/1554#issuecomment-24553086),

The script usage help says I can pass the .h files to command line to generate the JSON file.

```
$ python gen_struct_info.py --help
usage: gen_struct_info.py [-h] [-q] [-f] [-p] [-o path] [-I dir] [-D define]
                          [-U undefine]
                          headers [headers ...]

Generate JSON infos for structs.

positional arguments:
  headers      A header (.h) file or a JSON file with a list of structs and
               their fields
```

**Comment by kripken** [comment]
Sorry for forgetting this @muzuiget - I do agree it could be nice to get this tool working for more general things.

If you're still interested to work on this, I'd suggest adding a test (in `tests/test_other.py`, let me know if you need help). We'll need tests to track the functionality we fix and ensure it doesn't regress.

**Comment by muzuiget** [comment]
@kripken Oh, I almost forgot ths issue. But sorry, I have been not playing emscripten for a long time.

**Pull request closed without merging**
