### PR TITLE
Skip timer resolution test in browser.test_emscripten_get_now

### PR DESCRIPTION
**Pull request by kripken**
Browsers have reduced that resolution due to spectre :(

### CODE REVIEW

**Comment by juj** [comment]
Nooo!

Super crazy if timer resolution is back to +1 msec land. What are the `smallest_delta`s you are getting? This was probably retroactively applied to current Firefox stable in a point release. I think instead of unconditionally passing the resolution test, perhaps bump the 0.75msec limit from earlier to something like 2msec or 4msec, or 2x-5x of the `smallest_delta` that you're getting, so that it still measures coarse granularities?

**Comment by kripken** [comment]
Sadly it never finds a delta at all. The test calls `performance.now()` one time after the other. Firefox always returns the exact same time in both calls. The same thing happens if some amount of work is done in between the calls too.

**Comment by kripken** [comment]
Rewriting the test, I think it was mismeasuring before. Looping until get_now() increases, the resolution is 2ms in firefox and 0.1ms in chrome.

**Comment by kripken** [comment]
Still seeing random failures on this test. I made it a lot more robust (check for up to 5 seconds to find a small interval, so it's less at the mercy of a brief slowdown like a cycle collection).

**Pull request merged**
