### PR TITLE
wasm input to emcc

### PR DESCRIPTION
**Pull request by kripken**
This is the beginning of emcc support for wasm input. The idea is that a compiler can generate wasm in whatever way it wants, then call emcc just to do the web glue stuff: add the code to create and link up the wasm module, link in JS library code as needed, and so forth. emcc will emit a JS file that can be run, and it loads the wasm etc.

Specifically this might eventually be useful for mir2wasm, which generates wasm using binaryen. cc @brson @lqd @eholk

PR details: the emcc.py diff is mostly whitespace, a whitespace-ignoring diff is very small.

Limitations:
- For anything complex, the input wasm will need to define metadata. Simple imports/exports work, though, as in the testcase. Otherwise, metadata as emitted by s2wasm in binaryen can work too.
- The biggest limitation is C system libs. When a wasm input is received, we do JS linking, but can't link in C libraries that emscripten has; they are in LLVM bitcode format. That means no libc, etc. Quite a lot could still works, though, like emscripten_\* and html5_\* browser integration APIs, as they are pure JS. But no libc means a lot won't. This could be solved eventually with wasm object file linking, perhaps. (Of course, some languages won't need/want libc anyhow.)
- Some system integration is untested, like user stack support. I'm not sure how much we want to work here. Maybe related to the libc issue as well. E.g. if a language doesn't want libc and doesn't want a C-style user stack, but instead does its own thing, and just wants emcc to link in JS code to glue to the web, then what we have now is basically that.
- This still emits normal emscripten JS support code. Probably most is not needed in the case of a language just wanting JS glue and nothing else; perhaps we should have an option for that?

### CODE REVIEW

**Comment by vadimcn** [comment]
Hi!
What's the status of this feature?   Is it still planned for emcc to take .wasm inputs?

**Comment by kripken** [comment]
I still think it would be useful, but I haven't had time for it myself yet. If someone else wants to pick it up that would be good.

Do you have a specific use case that needs this?

**Comment by vadimcn** [comment]
I'm looking into moving Rust over to LLVM's native wasm backend.   Of course, once .wasm modules are emitted, they'd need to be linked to emscripten runtime, so I was wondering if emcc could do that.

**Comment by kripken** [comment]
Yeah, this would be needed for that. The wasm backend isn't stable yet, so it hasn't been a priority to get this working.

**Comment by kripken** [comment]
Closing, this is no longer relevant as in the LLVM wasm backend path with `WASM_OBJECT_FILES` this will just work anyhow.

**Pull request closed without merging**
