### PR TITLE
[Embind] Fix getTypeName not defined

### LINKED ISSUE #3487: "getTypeName is not defined" when calling C function
I recently tried to update my emscripten build of game-music-emu to latest with the help of _embind_ and when calling the function like this:

```
var payload = new Uint8Array(this.response);
var ref = Module.allocate(1, "i32", Module.ALLOC_STACK);
var samplerate = 44100;
if (Module.gme_open_data(payload, payload.length, ref, samplerate) != 0)
    console.error("could not load data", payload);
```

I get the following error:

```
Uncaught ReferenceError: getTypeName is not defined
```

Which happens during construction of the error message passed to a _UnboundTypeError_. So even if the original problem would disappear, there would still be an exception thrown.

For reference, I used to call this function in my old (~2 years ago maybe) emscripten build via:

```
Module.ccall("gme_open_data", "number",
             ["array", "number", "number", "number"],
             [payload, payload.length, ref, samplerate]) 
```

The _embind_ C++ code looks like this:

```
#include <emscripten/bind.h>
#include "gme.h"

using namespace emscripten;

EMSCRIPTEN_BINDINGS(Gme) {
    function("gme_open_data", &gme_open_data, emscripten::allow_raw_pointers());
    ....
}
```

And the _gme_open_data_ prototype looks like this:

```
gme_err_t gme_open_data( void const* data, long size, Music_Emu** out, int sample_rate );
```

Where _Music_Emu_ is an opaque type (actually a C++ class, but the API is C), and _gme_err_t_ is a _const char *_.

I built this (https://bitbucket.org/mpyne/game-music-emu) with:

```
~/bin/emsdk_portable/emscripten/master/em++ -O0 --bind -std=c++11 -o out.js *.cpp
```

In the _gme_ sub-directory of the git-repo, where I added my _Emscripten.cpp_ file with the _EMSCRIPTEN_BINDINGS_ declaration.

emscripten version is:

```
emcc (Emscripten GCC-like replacement) 1.32.0
    (commit b3efd9328f940034e1cab45af23bf29541e0d8ff
        (HEAD -> master, tag: 1.32.0, origin/master, origin/HEAD))
```

### LINKED ISSUE #3489: Embind Reference Error: "getTypeName is not defined"
Hi,
I have an Issue when trying to call a embinded function.
It seems to be related with the issue below, but unfortunately the thread didn't really help me.

I exported a class with Embind. In this class I have a function. It is to process some samples from audio input, so it takes a constant pointer to the float data and a unsigned int value for the sample size. 
So it looks something like this 

void processing(const float\* data, unsigned int size);

I exported it using allow_raw_pointers(), and everything compiled fine. 
In Javascript I can construct the object without problems.

But how exactly do I use the exported function now?
As an example I created a sample block as an array, which contains just a basic sine wave. 
I tried calling the function like

object.processing(sineWavaData, blockSize);

But this gives me the error, that I wrote in the title.

For your information, I know the basic concept of pointers, but I am quite inexperienced with advanced pointer usage, so it would be really great, if you could help me with that :)

### PR DESCRIPTION
**Pull request by Minishlink**
Initial PR #3807
Thanks @waywardmonkeys
Close #3489, close #3487

### CODE REVIEW

**Comment by kripken** [comment]
Looks good, but let's add a test. Can add it after `test_embind_2` in `tests/test_core.py`.

**Comment by Minishlink** [comment]
Please let me know if the test is correct as I don't know if it is a good way to test this fix.

**Comment by kripken** [comment]
Looks good. Did you verify that `./tests/runner.py ALL.test_embind_3` passes with the fix, and fails before it?

**Comment by Minishlink** [comment]
I can't really test the fix because I don't have the same environment setup between the source and my SDK.

Here's a glimpse of the output with what I have installed:
```
Running all test modes on test "test_embind_3"
test_embind_3 (test_core.default) ... (checking sanity from test runner)
ERROR:root:Emscripten, llvm and clang versions do not match, this is dangerous (1.34.9, 1.34.1, 1.34
.1)
ERROR:root:Make sure to use the same branch in each repo, and to be up-to-date on each. See http://k
ripken.github.io/emscripten-site/docs/building_from_source/LLVM-Backend.html
INFO:root:(Emscripten: Running sanity checks)
opt: Too many positional arguments specified!
Can specify at most 1 positional arguments: See: C:/Program Files/Emscripten/clang/e1.34.1_64bit\opt
 -help
Traceback (most recent call last):
  File "D:\Louis\Programmation\GitHub\emscripten\emcc", line 1270, in <module>
    final = shared.Building.llvm_opt(final, link_opts, DEFAULT_FINAL)
  File "D:\Louis\Programmation\GitHub\emscripten\tools\shared.py", line 1426, in llvm_opt
    assert os.path.exists(target), 'Failed to run llvm optimizations: ' + output
AssertionError: Failed to run llvm optimizations:
ERROR
test_embind_3 (test_core.asm1) ... opt: Too many positional arguments specified!
Can specify at most 1 positional arguments: See: C:/Program Files/Emscripten/clang/e1.34.1_64bit\opt
 -help
Traceback (most recent call last):
  File "D:\Louis\Programmation\GitHub\emscripten\emcc", line 1270, in <module>
    final = shared.Building.llvm_opt(final, link_opts, DEFAULT_FINAL)
  File "D:\Louis\Programmation\GitHub\emscripten\tools\shared.py", line 1426, in llvm_opt
    assert os.path.exists(target), 'Failed to run llvm optimizations: ' + output
AssertionError: Failed to run llvm optimizations:
ERROR
```

It is the same version against master though, and there the test fails normally.

**Comment by kripken** [comment]
Ok, I verified locally. Merged, thanks!

**Comment by Minishlink** [comment]
Thank you !

**Pull request merged**
