### PR TITLE
fix_simd_right_shift

### PR DESCRIPTION
**Pull request by juj**
Add test for shifting signed and unsigned LLVM vector types right.

### CODE REVIEW

**Comment by kripken** [comment]
lgtm. Does this depend on https://github.com/kripken/emscripten-fastcomp/pull/222 and so can be merged only after that one (+ a tagged build)?

**Comment by juj** [comment]
Rebased this to latest. This does require the fastcomp update to be in to work, so can only be merged after a new tagged build.

**Comment by kripken** [comment]
Cool, I tagged 1.38.9 now, which includes that fastcomp update. Should be able to merge incoming to here in a day or so and see the tests pass.

**Comment by kripken** [comment]
I verified this passed in a side branch, merging.

**Pull request merged**
