### PR TITLE
Fixing tests

### PR DESCRIPTION
**Pull request by Sevenops**
It adds Utf-8  to tests and fixing length code in test.
using with `var lengthBytes = jsString.length+1;` will return `こん` not `こんにちは`

### CODE REVIEW

**Comment by Sevenops** [comment]
#7323

**Comment by Becavalier** [comment]
@Sevenops I think it's better to re-create a new test script rather than modifying the exist one.

**Comment by Sevenops** [comment]
okay how about #7379 ?

**Comment by kripken** [comment]
Thanks @Sevenops!

I agree with @Becavalier that we should add new tests, instead of replacing current ones. However, you can add more code in an existing test, which is usually simpler. So I would just add a line or two there.

Please add this testing in the PR that adds the fix, though - that way we can see if the tests pass with it there.

**Pull request closed without merging**
