### PR TITLE
llvm custom passes draft

### PR DESCRIPTION
**Pull request by caiiiycuk**
Hi. Related to https://github.com/kripken/emscripten/issues/6379. I've tried to improve build system to allow using of custom llvm passes. Not very sure about correctness, feel free to give proposal. 

`LLVM_LTO_PASSES` needed just because we need way to run passes on link step.On other side we can reuse --llvm-lto, but we need fix it because now it's accept only number and not passes name. Another disadvantage of llvm-lto it is run only when optimizations are enabled.

### CODE REVIEW

**Comment by caiiiycuk** [comment]
Changed

**Comment by caiiiycuk** [comment]
```
======================================================================
ERROR: test_llvm_custom_pass_src (test_other.other)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.5/unittest/case.py", line 58, in testPartExecutor
    yield
  File "/usr/lib/python3.5/unittest/case.py", line 600, in run
    testMethod()
  File "/root/emscripten/tests/test_other.py", line 6483, in test_llvm_custom_pass_src
    check_execute(cmd)
  File "/root/emscripten/tools/shared.py", line 147, in check_execute
    subprocess.check_output(cmd, *args, **kw)
  File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
Exception: Command '['/root/emsdk-master/clang/e1.37.36_64bit/clang++', '-I/root/emsdk-master/clang/include', '-fPIC', '-fvisibility-inlines-hidden', '-Werror=date-time', '-std=c++11', '-Wall', '-W', '-Wno-unused-parameter', '-Wwrite-strings', '-Wcast-qual', '-Wno-missing-field-initializers', '-pedantic', '-Wno-long-long', '-Wno-maybe-uninitialized', '-Wdelete-non-virtual-dtor', '-Wno-comment', '-ffunction-sections', '-fdata-sections', '-O3', '-DNDEBUG', '-fno-exceptions', '-fno-rtti', '-DLLVM_BUILD_GLOBAL_ISEL', '-D_GNU_SOURCE', '-D__STDC_CONSTANT_MACROS', '-D__STDC_FORMAT_MACROS', '-D__STDC_LIMIT_MACROS', '-D_GLIBCXX_USE_CXX11_ABI=0', '-shared', '/root/emscripten/tests/llvm_pass_print_function_names.cpp', '-o', '/tmp/emsripten_temp_rrbrx5ky/llvm_pass_print_function_names.so']' returned non-zero exit status 1
```

Is it possible to get error output of this command at build server?

**Comment by kripken** [comment]
Do you mean this? https://circleci.com/gh/kripken/emscripten/14690?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

If you sign up for circleCI, there is also a button "rerun with ssh" which I've never tried. In general I just add more debug logging in the test itself.

**Comment by caiiiycuk** [comment]
Thanks! Is it possible to add clang include folder to docker image? Test case use this path for searching includes: `/root/emsdk-master/clang/include`. This path is returned by `llvm-config --cxxflags`, but path is empty on build server.

**Comment by caiiiycuk** [comment]
I have an idea, how to fix this test in better way. I will update this PR asap.

**Comment by caiiiycuk** [comment]
@kripken looks like CI is broken.

**Comment by kripken** [comment]
@caiiiycuk yes, sorry about that, was broken for a while. But it should be fixed now, I pushed a `pip` fix earlier today.

**Pull request closed without merging**
