### PR TITLE
Use python unittest method for skipping tests

### PR DESCRIPTION
**Pull request by sbc100**
Previously we were hand rolling our own skip methods.

### CODE REVIEW

**Comment by kripken** [comment]
@sbc100 something's still not right - all the requires_hardware tests quit instantly (reporting success). maybe in the non-skip case it's not returning the right type of thing?

**Comment by kripken** [comment]
Yes, I think it should return `func` instead of `lambda func: func`

**Comment by kripken** [comment]
I pushed a fix in d5e504987e37d3163024e7c5f4dac0a129015b28

**Comment by kripken** [comment]
Ah, my fix was not quite right - it got the normal case ok, but not when the env var is set to disable hardware tests.

But #6819 was opened meanwhile and it has what looks like a nice and proper fix.

**Comment by sbc100** [comment]
Oops, sorry about that.  Is it working as expected now?

**Comment by kripken** [comment]
Yeah, no problem, #6819 fixed it.

**Pull request merged**
