### PR TITLE
Use new style python classes

### PR DESCRIPTION
**Pull request by sbc100**
See: https://wiki.python.org/moin/NewClassVsClassicClass

### CODE REVIEW

**Comment by kripken** [comment]
lgtm

**Comment by sbc100** [comment]
I don't think I have permission to merge.

**Comment by kripken** [comment]
Added you now :)

**Comment by juj** [comment]
These types of refactoring are good, though it's good to be aware of any changes that might affect the minimum required Python version. We should probably document the expectation somewhere. Emscripten SDK currently ships with Python 2.7.5.3, so that is a hard requirement for minimum. I don't think we care about Python 2.6.x anymore.

**Pull request merged**
