### PR TITLE
freetype-js-port of Freetype 2.6.3

### PR DESCRIPTION
**Pull request by maxabrams**
To see the error:
1) Navigate to freetype-js-port
2) Launch a http server to host demand-loaded files. Easiest way (from freetype-js-port directory): python -m SimpleHTTPServer 8000
3) Open freetype.html and observe console output with text render

Command used to compile to JS: emcc -O3 --use-preload-plugins -s NO_EXIT_RUNTIME=1 -s EXPORTED_FUNCTIONS='["_main","_monochrome","_load_font","_find_font","_get_bitmap","_get_left","_get_top","_get_width","_get_height","_get_pitch","_get_advance"]' main.o objs/.libs/libfreetype.so -o freetype.js

### CODE REVIEW

**Comment by kripken** [comment]
In the issue we discussed using freetype from emscripten-ports. Does the problem not show up in ports?

The reason I am focused on the version in emscripten-ports is that it has fixes for undefined behavior in FreeType, some function pointer issues. For that reason, plain upstream FreeType might not work. Our existing tests in the test suite test for issues we've seen with that.

Is the code here plain upstream, or does it have our fixes in ports?

**Comment by maxabrams** [comment]
The Freetype 2.6.3 used for compile was modified  from upstream to include fixes.

**Comment by kripken** [comment]
Ok, good. Then if we can't get a reduced testcase for the 64-bit suspect, the next step here is to make this PR use the ports version. Then when we fix it we have the testing all ready (we can't merge another version of freetype in).

**Comment by kripken** [comment]
Ok, then we should upgrade ports to the version where the problem occurs (which is a good thing anyhow). And if this is a bug that we don't have a reduced testcase for, then we need full freetype to test it, so we need it in the test suite. To avoid having multiple freetype versions in the test suite, we should make the test suite use the updated ports version and nothing else. This would also give us easy way to check that the existing freetype tests pass on that version of freetype.

If that's too much work, then looking for a reduced testcase might be a better option. It sounded in the other issue that there was already a candidate, so that sounds promising.

**Comment by kripken** [comment]
This PR is quite old, closing. Feel free to reopen if still relevant.

**Pull request closed without merging**
