### PR TITLE
Reenable use of loadx and friends.

### PR DESCRIPTION
**Pull request by huningxin**
To fix https://github.com/kripken/emscripten/issues/3123, adding
loadx and friends into simd funcs.

### CODE REVIEW

**Comment by huningxin** [comment]
@sunfishcode , please take a look. It passes test_sse1 and benchmark_sse1 test. Thanks!

**Comment by huningxin** [comment]
@sunfishcode , thanks!

**Comment by huningxin** [comment]
@sunfishcode , could you please take a look? Thanks.

**Comment by sunfishcode** [comment]
The code looks good. Good catch on the _mm_loadl_pi index bug! I'm uncertain whether we should merge these before OdinMonkey can implement these first, as enabling them in emscripten.py will break all asm.js validation until such time.

OdinMonkey bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1113338

**Comment by huningxin** [comment]
Thanks for the review! I am comfortable to land this after OdinMoneky supports partial loads / stores.

**Comment by sunfishcode** [comment]
And it's now implemented. Thanks for your patience!

**Pull request merged**
