### PR TITLE
Let 'allocate' accept static memory that is defined as UTF-8 string with...

### PR DESCRIPTION
**Pull request by sbalko**
... character codepoints being the byte values

This is a small patch to the "allocate" function, which let's it accept a UTF-8 string, defining static memory. The Unicode character code points of that string are the byte values in the to-be-allocated memory. For performance reasons, the patch does not check for (non-Latin 1) code points being outside of the 0...255 range. 

In order to turn the static memory regions that are currently defined as integer arrays, I created a quick-and-dirty script, which needs to be run on the emscripten output: https://gist.github.com/anonymous/74196a36efbb4733a6f5

This pull request is now augmented with the changes to settings.js and emscripten.py, which help serializing static memory as UTF-8 string (see https://github.com/kripken/emscripten-fastcomp/pull/57).

### CODE REVIEW

**Comment by sbalko** [comment]
I rebased from incoming and fixed the code convention issues (all, I hope). The latest commit also includes the changes to the Python wrappers, which perform the UTF-8 rendering. This works fine with -O1. With -O3, UglifyJS kicks in and expands the shorter \xYZ escape sequences to the longer \uABCD sequences (and replaces all printable non-Latin 1 characters with Unicode escape sequences). This obviously diminishes the compression that is achieved with my patch.

AFAIR, you mentioned a commit that takes our UglifyJS from the toolchain for good (see here: https://github.com/kripken/emscripten-fastcomp/pull/57). However, I cannot find that commit in incoming. Did you actually push it?

**Comment by kripken** [comment]
I still see merge commits and other commits here - did you do a full rebase on latest incoming and force-push that to this branch?

Yes, on incoming `-O3` should use 100% passes in the native optimizer - last was `registerizeHarder`, you can verify it is in `NATIVE_PASSES` in `tools/js_optimizer.py`. We also have tests to verify that. Perhaps you're not on latest incoming?

**Comment by kripken** [comment]
I thought some more about `onMemoryInitialized` and I think I see your point. I added an `onRuntimeInitialized` option now that does that.

**Comment by sbalko** [comment]
Seems like I messed up a few things in my forked repository. Will force-push once I get this sorted out. 

And I think I am on the tip of incoming. If uglify is not the culprit in this case, then I wonder what causes the string re-formatting. My best guess (still need to verify) is that it's a JS file, which gets write-opened as a plain (ASCII-encoded) text file and not using my convenience function that makes sure that strings are encoded in UTF-8 encoding. Perhaps the native optimizer is at fault? I didn't check how it renders strings into the output file. Or I overlooked a place in the Python code where a new JS file is created. Will explore.

**Comment by sbalko** [comment]
Btw, I thought further about the option of encoding multiple bytes in a single UTF-8 character, which uses 1..4 bytes. As per the most recent UTF-8 specification (covering code points from 0x00...0x1fffff, we can clearly encode 2 bytes at once. According to Wikipedia, an older UTF-8 specification even supported a broader range, up to 0x7fffffff (2^31), theoretically making it possible to encode 3 bytes per character (at the expense of using up to 5 bytes per character). It is still unclear to me if JS parsers are able to handle these high code points and how to identify all non-printable characters >0xff (not sure if there are any). However, even being able to encode 2 bytes per character offers some nice extra compression. For "skewed" byte distributions, we may even see some additional compression that can theoretically match the size of a separate binary memory initialization file. That is, a sequence of two bytes being 0 results in a single character having a code point of 0 (0+0<<8 = 0). This character can almost always be represented by two bytes "\0". If even 3 bytes per character were supported by UTF-8, we could even beat the binary representation, because 0+0<<8+0<<16=0, again represented as "\0" (2 bytes). So all in all, I think we can come close(r) to the size of a binary memory initialization file, but without the overhead of an additional HTTP roundtrip, greater simplicity (i.e., being able to render the entire program in a single HTML file with inline JS), but at the expense of some extra CPU cycles being spent in parsing the UTF-8 strings and instantiating the corresponding "heap regions" from that.

**Comment by sbalko** [comment]
I've cleaned up this pull request from the other commits but still need to find the issue with UTF-8 string re-formatting when using -O3.

**Comment by sbalko** [comment]
So I dug into the Python code in emcc and js_optimizer.py in order to find out why js-optimizer.js is invoked (js-optimizer.js then invokes uglify). What happens is that in js_optimizer.py a static method "minify_shell" invokes "js-optimizer.js". "minify_shell" gets called from "run_on_js", which gets invoked with the passes: ['asm', 'eliminate', 'simplifyExpressions', 'simplifyIfs', 'registerizeHarder', 'minifyNames', 'cleanup', 'asmLastOpts', 'last', 'minifyWhitespace']. "run_on_js" is called from js_optimizer.py's run function, which is called from emcc's "run_passes" in "flush_js_optimizer_queue". 

I also added tracing to make use use_native returns 'true' for all passes (it does). So I guess there is a corner case not covered, which still invokes js-optimizer.js. Alon, can I ask you to look into this, please?

**Comment by sbalko** [comment]
I just pushed another commit, which introduces -s UTF8_STATIC_MEMORY=2. Using that setting, two (instead of 1) bytes are encoded into a single UTF-8 code point, i.e., producing a single character. Depending on the code point, that single character will then (implicitly) consume 1-4 bytes in the JS file. Alas, the JS parsers I tested (notably Chrome/V8) only support UTF-8 code points from U+0000...U+FFFF, limiting the number of bytes that can be packed into a single code point to 2. You can confirm the latter by trying this out in the JS console:

String.fromCharCode(0xffff+1).charCodeAt(0)

I validated this 2-byte-per-character patch by compiling (and trying out) cross-compiling ffmpeg, which works fine. The resulting file size reduction is quite noticeable, at the expense of having to perform some extra bit shifts when parsing the UTF-8 string. Probably the latter could be avoided by invoking "setValue" with "i16".

**Comment by kripken** [comment]
I don't understand what the corner case is that you are asking me to look into? A short list of concrete steps to follow would be helpful, as there is a lot of history to read at this point in this issue.

**Comment by chadaustin** [comment]
> Overall my concern is that while this decreases code size, it is still going to be significantly larger than a binary memory file. And compared to an array initializer in text, I worry this will be slower to parse. We should measure those, to see if there is a clear benefit to justify adding this complexity.

The last time I measured, parsing a string literal was significantly faster than parsing an array literal of numbers.  This intuitively makes sense, as it's a tighter, more limited loop in the parser, and the parse tree is a single string rather than a list node containing number nodes.

My intuition says that doing anything fancy with UTF-8 or encoding two bytes per character is going to be worth it, especially once gzip gets involved.

Also, once we prove (as I'm confident we will) that a string literal is strictly superior to an array literal containing numbers, we should remove the option and simply make the string literal the default behavior (when not using a meminit file).

**Comment by chadaustin** [comment]
Thanks @sbalko.  I agree that the 1-byte-per-character option is better for now.  The nice thing about human readability is you can quickly scan to see which string literals are taking up so much space.

That's actually what led us to implementing certain embind size optimizations -- though we had to discover it the hard way since the array-of-numeric-literals is not human-readable.

**Comment by kripken** [comment]
@chadaustin assuming utf8 is superior, then yes, I agree, we should have only utf8 or binary mem file

@sbalko what is your `EMCC_DEBUG=1` output when building with -O3? It should write out which optimizer it uses etc.

**Comment by sbalko** [comment]
@kripken see below - but that's exactly the problem here: it does in principle invoke the native optimizer *and* still invokes js-optimizer.js. This is what I suspect to be the "corner case" I talked about...

```
DEBUG    root: emcc: LLVM opts: -emscripten-no-exit-runtime -strip-debug -internalize -internalize-public-api-list=main,malloc,free,malloc,malloc,free,malloc,free,malloc,free,malloc -globaldce -globalopt -globaldce -pnacl-abi-simplify-preopt -pnacl-abi-simplify-postopt -disable-vectorize
DEBUG    root: emcc step "post-link" took 4.34 seconds
DEBUG    root: LLVM => JS
DEBUG    root: PYTHON not defined in ~/.emscripten, using "/usr/bin/python2"
DEBUG    root: not building relooper to js, using it in c++ backend
DEBUG    root: emscript: llvm backend: /home/parallels/dev/libav.js/emscripten-fastcomp/build/Release/bin/llc /tmp/tmpatINla/ffmpeg.bc -march=js -filetype=asm -o /tmp/emscripten_temp/tmpDtam4A.4.js -O3 -emscripten-max-setjmps=20
DEBUG    root:   emscript: llvm backend took 7.59992289543 seconds
DEBUG    root: emscript: js compiler glue
DEBUG    root:   emscript: glue took 0.20418715477 seconds
DEBUG    root: asm text sizes[[74268116, 18867, 25], 9101, 246, 5800, 0, 9261, 125792, 1982, 234, 4411, 4129]
DEBUG    root:   emscript: final python processing took 0.716519117355 seconds
DEBUG    root: emcc step "emscript (llvm=>js)" took 8.93 seconds
DEBUG    root: applying pre/postjses
DEBUG    root: applying transform: /home/parallels/dev/libav.js/embed/patch_js.sh
Now patching Javascript: /tmp/tmpatINla/ffmpeg.bc.o.js.pp.js.tr.js - Done.
DEBUG    root: optimizing memory initialization
DEBUG    root: emcc step "source transforms" took 11.89 seconds
DEBUG    root: running js post-opts
DEBUG    root: applying js optimization passes: ['asm', 'eliminate', 'simplifyExpressions', 'simplifyIfs', 'registerizeHarder', 'minifyNames', 'cleanup', 'asmLastOpts', 'last', 'minifyWhitespace']
Now calling JS optimizer.run ['asm', 'eliminate', 'simplifyExpressions', 'simplifyIfs', 'registerizeHarder', 'minifyNames', 'cleanup', 'asmLastOpts', 'last', 'minifyWhitespace']
chunkification: num funcs: 8633 actual num chunks: 25 chunk size range: 3095809 - 566525
DEBUG    root: building native optimizer: optimizer.exe
DEBUG    root:   using /home/parallels/dev/libav.js/emscripten-fastcomp/build/Release/bin/clang++
DEBUG    root: js optimizer using native
splitting up js optimization into 25 chunks, using 8 cores  (total: 70.86 MB)
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
running cleanup on shell code
DEBUG    root: emcc step "js opts" took 51.59 seconds
DEBUG    root: emcc step "final emitting" took 0.00 seconds
DEBUG    root: total time: 98.99 seconds
```

**Comment by kripken** [comment]
Ok, it's running the native optimizer properly. But for the non-asm.js shl elcode, we do still minify it by running uglify, thats the "running cleanup on shell code". That's what's happening here.

Uglify should support unicode strings (or any valid JS), so I'm surprised it doesn't just work. What is the input you are feeding it, and what is the output? (can run with `EMCC_DEBUG=2` to save all temp outputs in `/tmp/emscripten_temp`).

**Comment by sbalko** [comment]
Well, it does work - however, it "lengthens" the UTF-8 string. So for example, a hex escape sequence lijke "\xEF" becomes "\u00ef", i.e., we have more characters (and bytes) in the JS file. This partially defeats the purpose of introducing UTF-8 strings for the memory representation. My implementation (inspired by the "ministr" approach) uses the shortest-possible (AFAIK) escape sequences possible and for printable characters it always uses the printable character directly instead of a longer escape sequence...

**Comment by kripken** [comment]
Oh, I see. Well, we could modify Uglify to optimize that. Or, we could save it before uglify and restore it afterwards. But that sounds tricky, especially since we can have multiple such initializers. Modifying uglify is probably pretty simple.

**Comment by sbalko** [comment]
I currently use a simple node script which post-processes the JS file. This works well - but introduces another compiler “stage”, which is probably not preferable. 

https://gist.github.com/sbalko/378bcffd8c50c018181d <https://gist.github.com/sbalko/378bcffd8c50c018181d>

If modifying uglify is the way to go, one could maybe use this code. 

Soeren

**Comment by kripken** [comment]
I suppose its not so bad to do it using a separate node script. I'm ok with that.

**Comment by sbalko** [comment]
Are you OK with grabbing that script and incorporating it into the emscripten toolchain then? I don't exactly feel comfortable with making such an intrusive change myself...

**Comment by kripken** [comment]
I can guide you to the right place. Basically it should fit in emcc near the end of the entire process, probably right before we go to HTML if HTML was asked for. If `memory_init_file` is 0, then invoke node on your script. There is a pattern where you just assign to `final` the name of the new temp file your script creates, and that's it.

But, thinking right now, I am worried your script will also need to handle minified output - i.e. where `allocate(` has been minified into `$vb(` or such. I don't see how to do that in a reasonable way, offhand. Unless we can figure that out, it sounds like we would need to modify uglify.

**Comment by waywardmonkeys** [comment]
How's this coming along? We're interested in using this and seeing it land in the next stable release of emscripten if possible.

**Comment by kripken** [comment]
This PR is quite old, closing. Feel free to reopen if still relevant.

**Pull request closed without merging**
