### PR TITLE
A test case that creates invalid JS when compiled with -O0

### PR DESCRIPTION
**Pull request by TannerRogalsky**
```
WARNING:root:use EM_ALL_ENGINES=1 in the env to run against all JS engines, which is slower but provides more coverage
Test suites:
['test_core']
Running test_core: (1 tests)
test_unary_literal (test_core.default) ... (checking sanity from test runner)
INFO:root:(Emscripten: Running sanity checks)
(test did not pass in JS engine: ['/Users/tanner/code/c/emsdk_portable/node/8.9.1_64bit/bin/node'])
ERROR

======================================================================
ERROR: test_unary_literal (test_core.default)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/tanner/code/c/emsdk_portable/emscripten/incoming/tests/test_core.py", line 4867, in test_unary_literal
    self.do_run_in_out_file_test('tests', 'core', 'test_unary_literal')
  File "/Users/tanner/code/c/emsdk_portable/emscripten/incoming/tests/test_core.py", line 119, in do_run_in_out_file_test
    self.do_run_from_file(src, output, **kwargs)
  File "/Users/tanner/code/c/emsdk_portable/emscripten/incoming/tests/runner.py", line 656, in do_run_from_file
    self.do_run(open(src).read(), open(expected_output).read(), *args, **kwargs)
  File "/Users/tanner/code/c/emsdk_portable/emscripten/incoming/tests/runner.py", line 696, in do_run
    raise e
Exception: Expected to find '1.00
1.00
1.00
1.00
1.00
' in '/private/tmp/emscripten_test_default_gBVXjz/src.cpp.o.js:1932
 $12 = --1.0;
         ^^^

ReferenceError: Invalid left-hand side expression in prefix operation
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:599:28)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
', diff:

--- expected
+++ actual
@@ -1,6 +1,16 @@
-1.00
-1.00
-1.00
-1.00
-1.00
+/private/tmp/emscripten_test_default_gBVXjz/src.cpp.o.js:1932
+ $12 = --1.0;
+         ^^^

+ReferenceError: Invalid left-hand side expression in prefix operation
+    at createScript (vm.js:80:10)
+    at Object.runInThisContext (vm.js:139:10)
+    at Module._compile (module.js:599:28)
+    at Object.Module._extensions..js (module.js:646:10)
+    at Module.load (module.js:554:32)
+    at tryModuleLoad (module.js:497:12)
+    at Function.Module._load (module.js:489:3)
+    at Function.Module.runMain (module.js:676:10)
+    at startup (bootstrap_node.js:187:16)
+    at bootstrap_node.js:608:3
+



----------------------------------------------------------------------
Ran 1 test in 1.106s

FAILED (errors=1)```

### CODE REVIEW

**Comment by kripken** [comment]
Thanks!

As expected these fail now, and will fail until the new fastcomp is built. So after the next tagged version we should re-run the tests on this to verify, and at that point we can merge this.

**Comment by kripken** [comment]
I tagged 1.37.34 now, so as soon as the bots build that tag, we can merge incoming into here, verify tests pass, and merge this. Hopefully later today.

**Comment by TannerRogalsky** [comment]
We did it! It's nice when everything goes as planned.

**Comment by kripken** [comment]
Great, thanks!

**Pull request merged**
