### PR TITLE
EMULATED_FUNCTION_POINTERS: Don't export the entire table unless we are in a shared module

### PR DESCRIPTION
**Pull request by kripken**
See https://github.com/WebAssembly/binaryen/pull/1675#issuecomment-419678526

### CODE REVIEW

**Comment by kumpera** [comment]
This generates invalid js glue.

**Comment by kripken** [comment]
I see asm.js failures, and pushed a fix for that - is the js glue issue you mention on asm.js, or something not in the test suite?

**Comment by kripken** [comment]
Had to add a few test updates here, but now everything looks green, merging.

**Comment by kumpera** [comment]
I tried this patch through emscripten 1.38.12

`foo.c`:
```
#include <emscripten.h>

int do_not_export1 (int a, int b) { return a + b; }
int do_not_export2 (int a, int b) { return a - b; }
static void *x;

EMSCRIPTEN_KEEPALIVE void select_fun (int z) { 
	if (z == 1)
		x = &do_not_export1;
	if (z == 4)
		x = &do_not_export2;
}

EMSCRIPTEN_KEEPALIVE void blar () {
	int (*bin)(int, int) = x;
	bin (10, 20);
}
```

I'm compiling it with:
`emcc -g -Oz  foo.c -s EMULATED_FUNCTION_POINTERS=1  -o foo.html`

Here's what I'm seeing in the output that's not good.

`foo.js`:
```
function invoke_X() {
function ftCall_X(x) {
function invoke_iii(index,a1,a2) {
function ftCall_iii(x, a0, a1) {

Module.asmLibraryArg = { "abort": abort, "assert": assert, "enlargeMemory": enlargeMemory, "getTotalMemory": getTotalMemory, "abortOnCannotGrowMemory": abortOnCannotGrowMemory, "invoke_X": invoke_X, "invoke_iii": invoke_iii, "___setErrNo": ___setErrNo, "_abort": _abort, "_emscripten_memcpy_big": _emscripten_memcpy_big, "DYNAMICTOP_PTR": DYNAMICTOP_PTR, "tempDoublePtr": tempDoublePtr, "STACKTOP": STACKTOP, "STACK_MAX": STACK_MAX };

var FUNCTION_TABLE_X = [b0,asm['_do_not_export1'],asm['_do_not_export2'],b0];

Module["dynCall_X"] = dynCall_X
Module["dynCall_iii"] = dynCall_iii

```
None of the `invoke` and `ftCall` are needed. `FUNCTION_TABLE_X` is not referenced by anything.


`foo.wast`:
```
 (export "_do_not_export1" (func $_do_not_export1))
 (export "_do_not_export2" (func $_do_not_export2))
```
Neither functions should be exported. If I compile without `-s EMULATED_FUNCTION_POINTERS=1` they don't get exported.

**Comment by kumpera** [comment]
Looks like 1.38.12 claims to include this PR but it doesn't <o>

**Comment by kumpera** [comment]
Update, switching to `emscripten-incoming-64bit` Fixed the wasm part (not everything gets exported) but it still introduces all those imports that are not needed.

**Comment by kripken** [comment]
@kumpera I think those are because a debug build (`-g`) prevents some optimizations both in js and in wasm. Running with `-g1` (just to keep whitespace, but no other debuggability), I see only the expected exports, and most of the other stuff you mentioned vanishes.

I do still see `ftCall_X`, which is assigned to `dynCall_X`. I think the extra assignment is confusing the optimizer a little (the assignment doesn't happen without EMULATED_FUNCTION_POINTERS). That's worth fixing, but first, would be good to know how significant it is for size in a real-world project.

**Comment by kumpera** [comment]
You're right, with -g1 it goes away!

**Pull request merged**
