### PR TITLE
Prevent the name minifier choosing 'void' as a variable name

### PR DESCRIPTION
**Pull request by aidanhs**
Yes, I really did have enough functions to get all the way up to `void` in the naming!

### CODE REVIEW

**Comment by kripken** [comment]
Wow! That's a lot of functions...

How about adding all the 4-letter ones from https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Lexical_grammar ? We also should update `tools/optimizer/optimizer.cpp` (search for RESERVED).

**Comment by kripken** [comment]
I did the math - you really had > 221,175 functions? :)

**Comment by aidanhs** [comment]
```
$ em++ -o out.js -s EMULATE_FUNCTION_POINTER_CASTS=1 -O1 [...]
$ ls -hl out.js
-rw-r--r-- 1 user usergroup 612M Mar 10 12:05 out.js
$ grep -c 'function ' out.js
2161759
```

That's actually a fair bit smaller than when I saw this originally (per my messages on IRC) so I reckon it easily exceeded that:
```
12:43 < aidanhs> wow, EMULATE_FUNCTION_POINTER_CASTS took me from 100MB js file to 775MB
12:43 < aidanhs> I guess I'm going to need to consider alternative approaches
```

It was somewhat galling to try and load it in a browser and wait 10 minutes until it errored with "unexpected token void"!

(I've now attempted to find all function pointer cast locations in the codebase and eliminate them, so I'm back down to ~100MB now)

**Comment by aidanhs** [comment]
@kripken updated PR with all four-letter reserved words.

**Comment by kripken** [comment]
Thanks!

And yeah, makes sense now with emulating function pointer casts. I makes tons of thunk methods for each function pointer, to cast to another type...

**Pull request merged**
