### PR TITLE
Work around Chrome memory leak/crash by disabling IndexedDB

### PR DESCRIPTION
**Pull request by kripken**
Background: https://code.google.com/p/chromium/issues/detail?id=533648

This is a very severe memory leak, causing some Unity games to crash all of Chrome (not just a tab, but the whole browser). Testing locally, it looks like it is an IndexedDB bug in that browser, and disabling IndexedDB caching works around it. This patch does so, just in Chrome, so that other browsers are not negatively affected.

However, to just apply the workaround in Chrome, it checks the user agent, which is horrible of course. But I don't see a better solution here:

 * The bug is very severe, as mentioned before, games literally bring down the entire browser in a matter of seconds by runaway memory usage. On some systems this leads to thrashing memory to swap before the crash, during which the entire system is unresponsive.
 * The bug affects Chrome from stable to canary.
 * The bug was filed a month ago, but so far there is little progress on it.
 * Disabling IndexedDB in all browsers would avoid checking the user agent, but means duplicate downloads in some cases of quite large files, e.g., in the testcase in the linked bug, the data file is 80MB.

Given those, I think checking the user agent is the least of all evils. Thoughts?

### CODE REVIEW

**Comment by juj** [comment]
I think it's ok to sniff user agent. Perhaps we should print a warning message on Chrome when we disable indexedDB?

**Comment by kripken** [comment]
Sounds good, added a warning.

Also added another commit that warns on multiple syncfs operations in flight at once. That is not a bug, nor necessarily incorrect (might modify a file, syncfs, modify another, syncfs, and the first syncfs might only conclude after all that), but it is likely inefficient. This exacerbates the bug worked around in the first commit - it looks like after Chrome does one big IndexedDB operation, later ones are slower/take more memory, and so avoiding those can help.

**Comment by kripken** [comment]
lgty?

**Comment by juj** [comment]
The added warning on disabling IndexedDB looks good. However, I'm not sure about the added warning on multiple syncs in flight at once. If someone has multiple mounts, this will generate noise when it goes to sync each of them. Also, like mentioned, it's not necessarily incorrect on one mount either. The warning feels like it would have a chance of generating false positives. If syncing too many times is a performance issue, it should show up in profiling?

**Comment by kripken** [comment]
It isn't JS time - it's an async browser operation in native code. It would not show up in regular JS profiling, only profiling of the entire browser process. E.g. in the firefox profiler, it might show up if "show gecko symbols" is on, but that's off by default.

I do see the point about false positives, though. Perhaps we could throttle this, only show if there are more than N in flight at once, for N > 2? Or maybe just show it when `ASSERTIONS`?

**Comment by kripken** [comment]
feedback ping

**Comment by juj** [comment]
This does feel a bit uncomfortable, given that Firefox leaks here as well ( https://bugzilla.mozilla.org/show_bug.cgi?id=1223782 ), I wonder if it's just a coincidence, or if we might be mistreating IndexedDB somehow. Also, I wonder if we could do better by a bit more smarter tracking logic (#3908).

**Comment by kripken** [comment]
I suspect that hammering updates does indeed cause quadratic increases in memory, if the queue isn't emptied fast enough. It's just that chrome easily crashes the whole process, so it's more urgent to change there. Although, Unity has been the main sufferer, and they now have a local workaround, so maybe this is not urgent.

How about if we just land the warning, for now?

**Comment by juj** [comment]
Sounds ok, I agree it will be more work to create a precise tracking.

Though I wonder if we do even need to disable IndexedDB on Chrome at all, given that the Unity3D workaround should be effective? Perhaps it's enough to mitigate on Chrome as well?

**Comment by kripken** [comment]
Yes, we don't need to disable IndexedDB on chrome for Unity, the workaround they have is sufficient. I worry about other projects, however, with the warning they will at least have an easy way to debug this.

I'll land just the warning part, without the disabling.

**Comment by juj** [comment]
Ok, sounds good!

**Comment by kripken** [comment]
Landed the warning, closing since we don't want the rest.

**Pull request closed without merging**
