### PR TITLE
Revise the comments in preamble.js.

### PR DESCRIPTION
**Pull request by Becavalier**
@kripken Can you please help review this pr? Thanks!

### CODE REVIEW

**Comment by kripken** [comment]
Thanks for the PR @Becavalier!

Reading a little further down in this file, I see we already use TextDecoder for UTF8 and 16 decoding. In fact it looks like `Pointer_stringify` checks if the string is utf8, and if so calls `UTF8ToString`, which will use TextDecoder. So unless I an misreading it, I think the TODO comment here is out of date, and we can just remove it, without adding new code?

**Comment by Becavalier** [comment]
@kripken Yes, I see the following code in `UTF8ArrayToString`, let me update the PR to only remove the "TODO" comment. Thanks! 

> var UTF8Decoder = typeof TextDecoder !== 'undefined' ? new TextDecoder('utf8') : undefined;

**Comment by Becavalier** [comment]
@kripken  It looks okay now : )

**Comment by kripken** [comment]
Thanks! Looks good.

**Pull request merged**
