### PR TITLE
Make sure emcc.txt is ASCII-only

### LINKED ISSUE #6185: Missing .so file generation via emmake from 1.37.29
I am feeling I did something obvious mistake, but I couldn't pinpoint what it is - mind ask some help for this?

I've been building libprotobuf via emscripten (applying custom patch https://github.com/kwonoj/protobuf-wasm into protobuf source code) in docker image at https://github.com/kwonoj/docker-arch-emscripten. I have bumped up emscripten from `1.37.28` to `1.37.29`, and `emmake` result is different between two versions.

```
#run docker with 1.37.28
$docker build --tag test-1.37.28 --build-arg BUILD_TARGET=protobuf 
--build-arg PROTOBUF_VERSION=3.5.1.1 --build-arg EMSCRIPTEN_VERSION=1.37.28 .

...
drwxr-xr-x 2 builder builder     4096 Feb  4 00:41 .
drwxr-xr-x 1 builder builder     4096 Feb  4 00:41 ..
-rw-r--r-- 1 builder builder  1396644 Feb  4 00:41 libprotobuf-lite.a
lrwxrwxrwx 1 builder builder       22 Feb  4 00:41 libprotobuf-lite.la -> ../libprotobuf-lite.la
-rw-r--r-- 1 builder builder     1008 Feb  4 00:41 libprotobuf-lite.lai
lrwxrwxrwx 1 builder builder       26 Feb  4 00:41 libprotobuf-lite.so -> libprotobuf-lite.so.15.0.1
lrwxrwxrwx 1 builder builder       26 Feb  4 00:41 libprotobuf-lite.so.15 -> libprotobuf-lite.so.15.0.1
-rw-r--r-- 1 builder builder  1146056 Feb  4 00:41 libprotobuf-lite.so.15.0.1
-rw-r--r-- 1 builder builder 10168142 Feb  4 00:41 libprotobuf.a
lrwxrwxrwx 1 builder builder       17 Feb  4 00:41 libprotobuf.la -> ../libprotobuf.la
-rw-r--r-- 1 builder builder      973 Feb  4 00:41 libprotobuf.lai
lrwxrwxrwx 1 builder builder       21 Feb  4 00:41 libprotobuf.so -> libprotobuf.so.15.0.1
lrwxrwxrwx 1 builder builder       21 Feb  4 00:41 libprotobuf.so.15 -> libprotobuf.so.15.0.1
-rw-r--r-- 1 builder builder  8386364 Feb  4 00:41 libprotobuf.so.15.0.1
...
```
example job log: https://travis-ci.org/kwonoj/docker-arch-emscripten/jobs/337081030

```
#run docker with 1.37.29
$docker build --tag test-1.37.29 --build-arg BUILD_TARGET=protobuf 
--build-arg PROTOBUF_VERSION=3.5.1.1 --build-arg EMSCRIPTEN_VERSION=1.37.29 .

...
drwxr-xr-x 2 builder builder     4096 Feb  4 00:54 .
drwxr-xr-x 1 builder builder     4096 Feb  4 00:54 ..
-rw-r--r-- 1 builder builder  1396644 Feb  4 00:54 libprotobuf-lite.a
lrwxrwxrwx 1 builder builder       22 Feb  4 00:54 libprotobuf-lite.la -> ../libprotobuf-lite.la
-rw-r--r-- 1 builder builder      917 Feb  4 00:54 libprotobuf-lite.lai
-rw-r--r-- 1 builder builder 10168142 Feb  4 00:54 libprotobuf.a
lrwxrwxrwx 1 builder builder       17 Feb  4 00:54 libprotobuf.la -> ../libprotobuf.la
-rw-r--r-- 1 builder builder      902 Feb  4 00:54 libprotobuf.lai
...
```
example job log: https://travis-ci.org/kwonoj/docker-arch-emscripten/jobs/337085364

before 1.37.29, `emmake` emits `.so` files in build results but from 1.37.29 there aren't. Both images are using same protobuf version and patch code, also no configuration differences. Just fyi, I also tried latest release 1.37.33 and it works same as 1.37.29.

I'm bit confused by this result - is there any changes around emscripten requires additional configuration or is it just my simple mistakes around current configurations?

I run `emmake` for the build: 
`sh autogen.sh && emconfigure ./configure CXXFLAGS="-O2" && emmake make`
(https://github.com/kwonoj/docker-arch-emscripten/blob/3ad50b2ffdb5b982675e16aab4fd88bcfefba6d8/Dockerfile#L47)

### PR DESCRIPTION
**Pull request by Kagami**
Fixes #6185

### CODE REVIEW

**Comment by Kagami** [comment]
Btw, is it ok to specify env=python2 for emcc.py and use bare python for other calls:

https://github.com/kripken/emscripten/blob/29c0cc6/tools/shared.py#L1410-L1416

Note that in a lof of Linux distros python is being resolved to python3 by default.

**Comment by kripken** [comment]
Good find, thanks!

Let's also add a test for this. Can add a small one in `tests/test_other.py` that runs the command you mention in https://github.com/kripken/emscripten/issues/6185#issuecomment-364951823 and verifies the output.

> Btw, is it ok to specify env=python2 for emcc.py and use bare python for other calls

It should be ok to use python 2 or 3, we should support both now, so just `python` is ok. Not sure I understand the question though, is that what you're asking?

**Comment by kripken** [comment]
cc @saschanaz as this is a python2/3 issue.

**Comment by Kagami** [comment]
Yes, I was asking is it fine to run emcc with python3.

**Comment by Kagami** [comment]
Added test.

**Comment by kripken** [comment]
Thanks, looks good, and looks like no one else has any concerns here, merging.

**Pull request merged**
