### PR TITLE
Libcxx version bump to 4.0.1

### PR DESCRIPTION
**Pull request by dirkvdb**
As discussed in https://groups.google.com/forum/#!topic/emscripten-discuss/-ZVIcSRHwLQ

99% of the changes are simply overwriting the libcxx files with libcxx release 4.0.1
Modifications to the libcxx code are marked with XXX EMSCRIPTEN (only 2)

One important note: I had to update the stdexcept.cpp file from libcxxabi to the one from libcxxabi release 4.0.1. Otherwise I got an unresolved symbol __refstring_imp.

I briefly tried to upgrade libcxxabi as well, but that turned out to have a bigger impact then I hoped since they split off libunwind from libcxxabi. 

Test suite runs ok.
I also tested the result agains a project that uses C++17 features added in release 4 (optional/variant) and that seems to work fine.

### CODE REVIEW

**Comment by waywardmonkeys** [comment]
Very happy to see this!

I landed a fix upstream after 4.0.1 and prior to the branch for 5.0 that may be significant for some people. It was a performance fix for std::vector::clear so this might be good to revisit again soon when 5.0 is released.

In the past, we grabbed random snapshots of libc++ so the progression to being able to use an actual release is nice. :)

**Comment by kripken** [comment]
Thanks @dirkvdb!

 * Please add yourself to AUTHORS.
 * And please make sure that `python tests/runner.py` and `python tests/runner.py other` both pass.

@waywardmonkeys I'm curious about that `clear` optimization, do you happen to have the changeset?

**Comment by waywardmonkeys** [comment]
https://github.com/llvm-mirror/libcxx/commit/50145cc3e9013e35be1d2471590b0841f5b639da

**Comment by kripken** [comment]
Interesting, thanks!

**Comment by dirkvdb** [comment]
@kripken 
I updated the AUTHORS file.

I also verified the 'other' test suite. One test failed for me:
```
Test suites:
['test_other']
Running test_other: (1 tests)
test_llvm_lit (test_other.other) ... ['/usr/bin/python', '/Users/dirk/Projects/emsdk/clang/fastcomp/build_incoming_64/bin/llvm-lit', '-v', '/Users/dirk/Projects/emsdk/clang/fastcomp/src/test/CodeGen/JS']
llvm-lit: /Users/dirk/Projects/emsdk/clang/fastcomp/src/test/lit.cfg:164: fatal: No site specific configuration available!
FAIL

======================================================================
FAIL: test_llvm_lit (test_other.other)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/dirk/Projects/emsdk/emscripten/incoming/tests/test_other.py", line 3483, in test_llvm_lit
    assert p.returncode == 0, 'LLVM tests must pass with exit code 0'
AssertionError: LLVM tests must pass with exit code 0

----------------------------------------------------------------------
Ran 1 test in 0.165s
```
Seems like I'm missing some site config file

**Comment by kripken** [comment]
Yeah, that failure is just that the LLVM install is missing the test config file, but it's not relevant here. Ok good, let me run some tests locally to confirm, then I'll merge this with a version bump.

**Comment by kripken** [comment]
Thanks!

**Pull request merged**
