### PR TITLE
Python 3 compatibility: check type before numeric comparison

### PR DESCRIPTION
**Pull request by SaschaNaz**
Python 3 does not allow comparison between `NoneType` or lists and numbers, while Python 2 did (`None` is smaller than any number and `list()` is larger than any number).

This PR tries to mimic the current behavior on both Python 2 and 3 by checking type before comparison, when options.llvm_opts can be a list and options.llvm_lto can be `None`.

### CODE REVIEW

**Comment by dschuff** [comment]
I think instead we should just never use the same variable to store either a number or a list. Is that what we are doing with these options?

**Comment by kripken** [comment]
Yeah, we could make `llvm_opts` always contain a list, by changing `LLVM_OPT_LEVEL` to return a list (so `3 => ['-O3']`, and remove handling of int values in the places we pass it too.

**Comment by SaschaNaz** [comment]
The new change removes `pick_llvm_opts` as the only remaining call site was on runner.py. Shouldn't change the behavior but slightly worried about the removed long comment.

**Comment by SaschaNaz** [comment]
Some tests fails, I will try a fix soon.

**Pull request closed without merging**
