### PR TITLE
Add pointer-masking runtime validation checks. 

### PR DESCRIPTION
**Pull request by JSStats**
These replace the bitand operation with a call to a function that checks that the result of masking the index equals the argument, in other words that the bitand operation is a nop.

Some cases have been found in which replacing a[(i+c)&m] with a[(i&m)+c] can give invalid results, in particular when 'i' is negative, and this runtime test will detect this.

While runtime checks are not a good long term solution, they help validate benchmarks used to test JS implementation performance and this avoids blocking JS implementation development.

This patch also adds support for blacklisting some functions from using the above transform, and for these functions all accesses are emitted as a[(i+c)&m].

### CODE REVIEW

**Comment by kripken** [comment]
If `i` is negative, isn't the code access invalid anyhow?

**Comment by JSStats** [comment]
The index `(i+c)` can still be within bounds when `i` is negative. This issue was found in poppler, but the runtime checks have not found any such issues in the other tests. Longer term, I think the matter can be addressed by only applying the transform to the addition of a constant offset to a pointer rather than to an integer index. This patch is supplied for now to allow confidence in benchmarks used to target JS implementation development which has a long lead time, and it might be of continued use in testing.

**Comment by juj** [comment]
Do you know what the original C code pattern was that generated this?

**Comment by JSStats** [comment]
A C code pattern such as `a[i+c]`, where `i` was a signed value that is then offset by a positive constant `c` to give a positive index for lookup in a table `a`. Saw this in poppler for color translation code.

**Comment by kripken** [comment]
I think relying on dynamic checks here is not practical. It limits the usefulness of this approach to where you can only truly rely on it in small hand-written asm.js methods - which is still useful, but not a general solution. Emscripten in fact has in the far past depended quite a lot on dynamic checks for speed, and the experience was negative; we've been moving away from it ever since.

I wonder though if we can't figure out a way to mask that avoids this problem?

cc @bmeurer who was interested in pointer masking

**Comment by JSStats** [comment]
Please see the comment submitted with this patch 'While runtime checks are not a good long term solution, they help validate benchmarks used to test JS implementation performance and this avoids blocking JS implementation development.'

This problem can not be avoided. A destructive transform is being made. I believe this will be practical using reasonable heuristics and aided by some type information, and the runtime checks give further support for this position. For example, it is probably sound for most code to assume that pointers are not negative, and that code does not depend on pointer wrapping. This makes the transform of `a[(p+c)&m]` to `a[(p&m)+c]` practical, and it is also practical when `p` can be proven non-negative. This might be further limited to only assuming that pointers obtain via certain paths are non-negative. More can be done.

These transforms simply can not be made by the JS implementation without dynamic guards (except where they can be proven valid by type information). It has always been my intention to make such transforms in Emscripten where they can be guided by heuristics, and more are planned to support the hoisting of the masking.

This patch is needed to double check such heuristics, and as a method to validate benchmarks used for JS implementation development. It can certainly give confidence in a deterministic benchmark.

I'll probably be focused on helping JS implementations emit great code for these patterns in the short term, and using the validated benchmarks to track progress.

I am fine with forking Emscripten, and don't want to push these on anyone. It could always be merged in future if proven useful, and there is still a lot of common ground. Just let me know if it's too experimental?

**Comment by kripken** [comment]
If this is a destructive pattern that cannot be made into something that is valid and always works, I fear that you may be wasting your time on working on this path, on the JS engine patches, etc. I think it makes sense to first figure out a way to make it always valid - or reconsider this approach. Requiring dynamic checks means almost no application developer will want to use this option.

A random idea of what I mean: `a[(i+c)&m] => a[i >= 0 ? (i&m)+c : (i+c)&m] `. That pattern is always valid. But it's large and I don't recommend it. Perhaps there is a way to improve it.

**Comment by JSStats** [comment]
Can anyone recall C code written that stores negative pointers that only become valid after adding an offset?

I guess there might be such hazards lurking in some large code bases, and the thought of a destructive transform breaking this might put off some developers. However I suspect that a lot of developers would accept this risk, particularly after some testing with runtime checks enabled and suitable code coverage, or after code inspection.

Optimizing JS implementations to better support such patterns has much more general utility than just for Emscripten. It can help optimize hand written JS code, and JS code converted from languages that do not have negative pointer hazards such as Fortran numerical libraries. Even if it is only used to optimize some hot loops in larger Emscritpen converted code bases then it has some utility.

The idea is not to have dynamic checks in the final code. Your transform can be improved if `i` is know by Emscripten to be non-negative by type derivation, or using heuristics. I am not suggesting emitting runtime tests as in your transform, rather only applying the transform when appropriate.

I'm confident that a lot of C pointers can be reasonable assumed to be non-negative: stack pointers, object pointers, etc. The only hazard I have found so far is in an array index computation, `pointer + index + offset`, and I am confident these cases can be detected.

The code writer often has more information than the JS implementation and so is more capable of making these optimization transform decisions.

There is surely a some deal of speculation in choosing development paths, but the results can be objectively tested for performance and usability etc, so I am happy to agree to disagree and work on a separate fork?

**Comment by bmeurer** [comment]
I'm pretty sure that pointer wrapping is undefined behavior in both C and C++. So as long as we're talking about C/C++ only, your optimization is sound. I'm not sure about other LLVM frontend languages however.

**Comment by kripken** [comment]
@JSStats - of course i have no concerns about you working on your own branch (open source! :) ), but I do feel sad at the effort you are putting into this. It is starting to feel like a dead end to me.

I understand that the dynamic checks are just on the developer's machine. This is exactly what emscripten used to do a long time ago, as I mentioned - we did runtime profiling to find out when we needed to actually emit sign corrections and stuff like that; back then, it made a big difference in speed. But now and then, it led to really weird bugs that showed up after development. It was just not worth the risks. When we moved to a model that preserves C++'s semantic guarantees perfectly (or as perfectly as possible in JS), everyone was much happier.

What does seem feasible is to use this in hand-written code. Emscripten's standard library contains memcpy etc. implementations that are hand-tuned. Manually pointer-masking in there sounds quite reasonable, assuming there are speedups.

@bmeurer - it seems to me like there are 2 issues here. In C++ it is undefined to wrap pointers, but asm.js like that can occur from simple indexing, not necessarily from wrapping a pointer. `a[b+c]` in C++ might have b negative and c positive, and that's defined behavior, but it would look the same here as the dangerous situation.

In principle if we knew which of those stem from C++ undefined behavior and which do not, we could optimize the former, which would be the most common. But this seems to require integration all the way in the backend and through the optimizer. At first thought, that seems tricky to do in a feasible way.

**Pull request closed without merging**
