### PR TITLE
emscripten_get_global_libc is only needed in pthreads builds

### PR DESCRIPTION
**Pull request by kripken**
Unless I'm missing something? As far as I can tell, it was added with the last musl update, and is only used with pthreads, but was unnecessarily kept alive in non-pthreads builds too. cc @juj @jgravelle-google

### CODE REVIEW

**Comment by kripken** [comment]
Added a commit with more avoidance of pthreads overhead in non-pthreads mode: errno depended on pthreads. The commit suggests we avoid that overhead when not in pthreads mode (it can store errno in a global location, not separately in a pthread struct).

**Comment by kripken** [comment]
ping @juj @jgravelle-google - this is a short PR, but very useful for removing unnecessary code we emit right now :)

**Comment by kripken** [comment]
Thanks. I'll merge this in with a version number bump (for system lib rebuilding).

**Comment by juj** [comment]
This is perfect, looks good to me as well.

**Pull request merged**
