### PR TITLE
Run binaryen wasm-opt on wasm backend output

### PR DESCRIPTION
**Pull request by kripken**
This proposes we run the binaryen optimizer on wasm-backend output. It makes that output 5-10% smaller. This came up again today when looking at the clang running in the browser demo, which is from the wasm backend, and part of the reason for the large size is not running binaryen opts.

Debatable whether this makes sense to do by default or not - in -O1 and above it shrinks the output but increases build time, it's a tradeoff - but I lean towards emcc doing what emits good code. That clang build is adding binaryen to the build process, but emcc could do it by default so other people don't miss it. Also, there is no change to the speed of -O0 builds for fast iteration.

This PR also contains some closure fixes I noticed when running the test suite locally. I'm surprised these weren't noticed on the bots, maybe they don't have java and so skip closure, I guess?

### CODE REVIEW

**Comment by saschanaz** [comment]
>maybe they don't have java and so skip closure, I guess?

No, it installs java so it shouldn't be the case.

**Comment by kripken** [comment]
Sorry, I should have been clearer, I meant the wasm bot, which runs latest llvm+wasm backend stuff, https://wasm-stat.us/console , not the CI we have here (which doesn't test the wasm backend yet).

**Comment by jgravelle-google** [comment]
We do run closure on the wasm waterfall, which is currently red because of it.
https://logs.chromium.org/v/?s=chromium%2Fbb%2Fclient.wasm.llvm%2Flinux%2F27799%2F%2B%2Frecipes%2Fsteps%2FExecute_emscripten_testsuite__emwasm_%2F0%2Fstdout
This is something I was looking into, but had gotten far enough to realize I didn't know what to do with the error it was giving me and was about to start bisecting. So, thank you. Trying this patch locally this fixes the issue.

**Comment by dschuff** [comment]
+1, I'd favor going with better code for now. I'd like to get to some backend optimization work in LLVM before too long, and hopefully that way we can improve code quality without the cost of serializing through another tool.

**Comment by jgravelle-google** [comment]
I forgot to mention explicitly, but also +1 for optimization

**Pull request merged**
