### PR TITLE
Fix multiple calls for game loop.

### PR DESCRIPTION
**Pull request by asRIA**
If we call `emscripten_resume_main_loop` inside a blocker function, then game loop will be registered two times.

It was that because if we call `resume` during blocker execution then body of `Browser.mainLoop.runner` will be replaced. Next frame will be schedule. This will create/schedule first source of main loop update. 

But we are still inside old `Browser_mainLoop_runner` so after blocker function execute it will self schedule runner by: `setTimeout(Browser.mainLoop.runner, 0)` In this case it will schedule newly created runner. It will create second source of main loop. 

We have following condition in line src/library_browser.js:1114 
```
if (thisMainLoopId < Browser.mainLoop.currentlyRunningMainloop) return;
```
But it will not capture this, because after running `resume` and increment `currentlyRunningMainloop` function `emscripten_set_main_loop` will be called so that new closure for runner will be created (with captured `thisMainLoopId`). 

Proposed solution in pull request will preserve closure, so that sanity check will work after self scheduling by releasing blocker code. 

---

As an alternative solution before `setTimeout(Browser.mainLoop.runner, 0)` it could be placed: 
```
if (thisMainLoopId < Browser.mainLoop.currentlyRunningMainloop) return;
```

Main difference between those two solutions is that first one will preserve closure which could be less error prone in the future. 

---

Not sure that this particular logic could be tested with avoiding time based unit test. 
Issue could be related to: https://github.com/kripken/emscripten/issues/2325

### CODE REVIEW

**Comment by asRIA** [comment]
I pushed a change to one test to detect this error. It is time based what is not really predictable. 

Minimal time for frame has beer raised up from 1ms to 16ms to ensure timing. Albeit for detecting this error it could be OK to rise up to ~8ms. 

Cheers,

**Comment by kripken** [comment]
Sorry for the delay here.

I would prefer to not use `arguments.callee`. How about directly detecting when the main loop is resumed while the main loop is still blocked, and if so, we ignore the resume request?

**Comment by asRIA** [comment]
Hi,
Ignoring is not the right solution. Context when I've discovered this issue was that I created a blocker. Inside blocker call I paused main loop and I've started IndexedDB initiation and synchronization. Once it is finished I resumed main loop. Problem was when mounting IDBFS failed immediately and resume happen in described above context. 

Yes this will work, but I preferred to not add new variable that flags performing blockers queue and I've tried to reuse current mechanisms. 

As you prefer I removed `arguments.cally` and I used simple if statement which works just fine.

What do you think about it?

**Comment by kripken** [comment]
Yes, good point. Ok, that looks like a nice way to solve this. The one thing I'd ask to change is to not affect the existing test in that file. Either copy the file and modify that, and add a test, or use a `#define` and run the test in both modes. I just want to be sure we are still testing what was done before, as well as this new thing.

**Comment by asRIA** [comment]
I'm closing this one. I squashed commits to one, and I applied review notes.
New pull request: https://github.com/kripken/emscripten/pull/3917

**Pull request closed without merging**
