### PR TITLE
Travis browser tests

### PR DESCRIPTION
**Pull request by kripken**
This adds an option to run browser tests without opening a browser, so it just checks compilation in that case. This is used on travis, where it gives us coverage of compilation errors in the browser suite.

This may be useful for testing #5765 and others.

Any opposition to landing it first, with the new errors it creates?

### CODE REVIEW

**Comment by nazar-pc** [comment]
I like an idea of checking compilation errors without actually running the output code. It can be used as kind of a linter, since Closure Compiler can identify a wide range of errors and suspicious constructions on its own.

**Comment by asRIA** [comment]
Hi @kripken: As a further improvement to the process, it's possible to run a headless mode of Firefox and Chrome, those can be run from Docker image.

**Comment by saschanaz** [comment]
I tried Firefox headless but it does not support disabling popup blocker. Chrome does, with [a known renderer issue](https://github.com/kripken/emscripten/issues/5668).

**Comment by saschanaz** [comment]
It seems most of (if not all) the tests are failing because of Closure errors, then I think #5765 should be merged first to get CI green again. (Everred CI is not helpful for me to debug...)

**Comment by kripken** [comment]
Makes sense, merging it from master to here now.

**Comment by kripken** [comment]
@juj the CI here will use `emsdk latest`, when will that get a new fastcomp build (to fix the sse failures)? Do we need a version tag for that? Or at what frequency does it happen?

**Comment by juj** [comment]
> Do we need a version tag for that?

Yes, we will need a new version tag. However we should not tag until Emsdk has been updated with new Java version (or alternatively revert the Closure update), because that will otherwise break using Emscripten for Windows users.

**Comment by nazar-pc** [comment]
Is Java update a big undertaking though?

**Comment by juj** [comment]
It needs preparing new portable installation binaries, upload them to CDN, hook in to emsdk and test. Not sure about "big" or "small", but just recognizing that we are now in a bad state on `incoming` that it does not work for emsdk users on Windows, and if we tagged now, also people using latest released tags will break. I am working on the update as a priority since this is a critical breakage, and would be best that we don't tag in the meanwhile before we know that the generated tag will be good.

**Comment by kripken** [comment]
Ok, everything looks good here after @nazar-pc's closure fixes. I just had to disable `browser.test_emrun_info` when running without a browser. All tests should pass now (but the sse known issues).

**Comment by kripken** [comment]
Tests look as expected. Any objections to landing this?

Side note, if we don't think those sse failures will be fixed in a day or so, we can just disable those tests until the next tag.

**Comment by juj** [comment]
lgtm

**Pull request merged**
