### PR TITLE
Support loading a global or function in a side module that is provided by a later side module

### PR DESCRIPTION
**Pull request by kripken**
In asm.js we handle this by the side module's JS creating indirection functions (so that when the property is actually used later, after loading the other side module, we find it). In wasm, though, side modules are pure wasm and cannot help in their own loading in such a manner.

To get around that, this adds a JS proxy on the `env` object, which sees when the side module tries to load a missing property. If it's a global helper function (`g$` prefix in the current side module model), then we create it at that time.

Fixes at least part of #6951

### CODE REVIEW

**Comment by kripken** [comment]
Realized just as I woke up that the exact same issue happens for function pointers too. Fix added + testing. This should fix #6951 completely now.

**Comment by awtcode** [comment]
@kripken , sorry for the late reply, I was busy debugging the Chrome crash and finally got down to this. Thanks, this PR does fix all issues with the import of global variables. However, I found another issue with using multiple bc for side modules. Unfortunately, I wasn't able to find a dynamic linking test that uses multiple bc for the build so I have temporarily hosted my testcase here:

https://github.com/awtcode/dylink_exceptions

Do you mind working with this repo first while I find out how to use multiple bc for the dynamic linking test? I have removed the proxy-to-worker and you only need to run 'node index.js'.

Once again, thanks so much for your help.

**Comment by kripken** [comment]
Thanks, merging this.

I'll try to look at that testcase soon.

**Comment by kripken** [comment]
@awtcode I found some time to look into this. I believe I identified the issue, a fix is in #7049. (Btw, the test in that PR is a good example of what I mentioned to you in the past - submitting bug reports with testcases in that format would be optimal.)

**Comment by awtcode** [comment]
Thanks for working on this @kripken, really appreciate it :) In the future, I will try to embed the test case in the Emscripten test suites itself.

Just curious, could we replace the invoke_x calls with a Wasm call_indirect? In this case, I believe the code is crashing when it is trying to call the constructor of the derived class, so perhaps, we can even make a direct call to the derived class's constructor when exceptions are enabled?

**Comment by kripken** [comment]
Are you saying that an optimizer should be able to prove an exception is not thrown in this case, and reduce the `invoke` (which can handle a possible exception) to an indirect call (which can't)?

It's possible the LLVM optimizer could be improved on various things like that. We could also add optimizations for it in Binaryen if we find something that justifies that work.

**Comment by awtcode** [comment]
Sorry for the late reply @kripken. I guess my question is simpler in nature. As in, my current understanding is that the invoke is a wrapper around a Wasm function that cannot throw an exception anyway. Why is it that an invoke can possibly handle an exception here then? I must be missing something. Thanks.

**Comment by kripken** [comment]
The question is whether the optimizer knows that the called function cannot throw an exception.

In LLVM, if the function is in another compilation unit, the only way it can tell is if it was marked noexcept. Otherwise, if it's optimized together (same compilation unit, or doing LTO), it might be able to figure it out (but there are no guarantees).

If this doesn't work in LLVM, as I said another option is to optimize it in Binaryen. We don't do that yet, but we do usually look at the whole program there, so certainly simple cases should be easy to optimize.

**Comment by awtcode** [comment]
Thanks @kripken

**Pull request merged**
