### PR TITLE
fix_embind_unsigned_32bit

### LINKED ISSUE #5277: emscripten::val::as<uint32_t> - 'RuntimeError: integer result unrepresentable' where value >= 0x80000000
Using `sdk-incoming-64bit`/`binaryen-master-64bit`:

```cpp
// test.cpp
#include <emscripten/bind.h>
#include <emscripten/emscripten.h>
#include <cstdio>
static void set_bind_f64(emscripten::val val) {
    printf("set_bind_f64: %x\n", (uint32_t)val.as<double>());
}
static void set_bind_u64(emscripten::val val) {
    printf("set_bind_u64: %x\n", (uint32_t)val.as<uint64_t>());
}
static void set_bind_u32(emscripten::val val) {
    printf("set_bind_u32: %x\n", val.as<uint32_t>());
}
extern "C" {
    EMSCRIPTEN_KEEPALIVE void set_c_u64(uint64_t v) {
        printf("set_c_u64: %x\n", (uint32_t)v);
    }
    EMSCRIPTEN_KEEPALIVE void set_c_u32(uint32_t v) {
        printf("set_c_u32: %x\n", v);
    }
}
EMSCRIPTEN_BINDINGS(TEST) {
    emscripten::function("set_bind_f64", &set_bind_f64);
    emscripten::function("set_bind_u64", &set_bind_u64);
    emscripten::function("set_bind_u32", &set_bind_u32);
}
```

```js
// test.js
function MAKE_TEST(fn) {
	return function() {
		setTimeout(function() {
			try {
				Module[fn](2147483648);
			} catch (e) {
				console.error(fn, e);
			}
		}, 0);
	}
}
Module["postRun"] = [
	MAKE_TEST('set_bind_f64'),
	MAKE_TEST('set_bind_u64'),
	MAKE_TEST('set_bind_u32'),
	MAKE_TEST('_set_c_u64'),
	MAKE_TEST('_set_c_u32')
]
```

Execute the following:
`emcc --bind --emrun -s WASM=1 --std=c++11 --post-js test.js -o index.html test.cpp`
`emrun index.html`

Results: 
* `RuntimeError: integer result unrepresentable` for calls to `set_bind_u32`
* Both `_set_c_u32` and `_set_c_u64` function correctly in both WASM and non-WASM builds.
* `set_bind_u32` works correctly for non-WASM builds.
* Additionally `set_bind_u64` fails with binding error in all versions.

Previously known to work with the following revisions:
emscripten/incoming: `e6e11c01709f082c7a6f7ed1d46c004ad7011c2f`
binaryen/master: `d6508e1f9cef33c43016e4da7dd4b94392f280a9`

### PR DESCRIPTION
**Pull request by juj**
Fix support for passing 32-bit unsigned integers through with embind in wasm build mode. Fixes #5277 for 32-bit case.

### CODE REVIEW

**Comment by kripken** [comment]
cc @AlexPerrot

**Comment by juj** [comment]
Any concerns here @AlexPerrot ? This should be good to merge.

**Comment by AlexPerrot** [comment]
No concerns, lgtm.

**Comment by juj** [comment]
Thanks for the review!

**Pull request merged**
