### PR TITLE
fix_test_fs_nodefs_home

### PR DESCRIPTION
**Pull request by juj**
Fix test test_nodefs_home on Windows.

### CODE REVIEW

**Comment by juj** [comment]
Btw the test is a bit evil in that it works inside user's home directory. This is also racy from the perspective of the multithreaded test runner I think, although I did not see a failure by hammering `python tests/runner.py ALL.test_fs_nodefs_home` a couple of times. I don't have a better suggestion what to do about it though, except to perhaps move it to `sanity` or `other`, although that would reduce coverage of the different build modes.

**Comment by kripken** [comment]
lgtm, but good point about this test being sort of evil, especially writing to the home dir. Perhaps we should remove that part, and just check the location of the home dir or something like that, which has no side effects and no race conditions?

**Comment by saschanaz** [comment]
It seems Windows does provide HOME env var but only for PowerShell, which is the default shell on the latest Windows 10.

**Comment by saschanaz** [comment]
>especially writing to the home dir.

The test only does `readdir()` for home dir, which shouldn't do any conflicting write operation.

**Comment by juj** [comment]
> The test only does readdir() for home dir, which shouldn't do any conflicting write operation.

Err, good point and sorry, I read through the test a couple of times and parsed it again and again to create the directory `nodefs_home` inside user's HOME, but now with a fresh morning and a cup of coffee I see it uses that as a mount point for the home directory, so all should be well.

**Pull request merged**
