### PR TITLE
Gorry fix 20170215

### PR DESCRIPTION
**Pull request by gorry**

### CODE REVIEW

**Comment by kripken** [comment]
Hi, could you please make the PR directly to the `incoming` branch? That's where we merge new code. (It's ok sometimes for PRs to be to master, we can just merge them manually to incoming, but if there is a conflict or duplicate commits, it's better to have the PR go to incoming directly.)

(Github doesn't let you modify a PR that way, so I think you need to create a new one.)

**Comment by sebcrozet** [comment]
@kripken Any update on this? I face the same issue. It seems the PR now targets the `incoming` branch as requested.
Thanks!

**Comment by kripken** [comment]
Thanks for the ping @sebcrozet , it seems github doesn't notify on branch changes so I didn't notice this change. And thanks @gorry and @saschanaz as well of course.

**Comment by sebcrozet** [comment]
Thanks @kripken .

**Pull request merged**
