### PR TITLE
path is not defined -> use nodePath

### PR DESCRIPTION
**Pull request by ralphtheninja**
`path` is undefined so `path.join()` will crash, use `nodePath['join']` instead.

I'm not sure how to test this, feel free to give feedback so I can correct that if needed.

### CODE REVIEW

**Comment by kripken** [comment]
Looks good, thanks.

Let's add a test to `tests/test_other.py`. A simple way might be to call `Module.read` directly from an `EM_ASM` block. And before, python would create the file to be read, etc.

**Comment by ralphtheninja** [comment]
> Looks good, thanks.
> 
> Let's add a test to tests/test_other.py. A simple way might be to call Module.read directly from an EM_ASM block. And before, python would create the file to be read, etc.

Sweet. I'll dig deeper tomorrow!

**Comment by ralphtheninja** [comment]
@kripken I'm thinking we could scrap this PR and I could create a new one that removes that if-statement completely. Or does it solve some special use case?

**Comment by kripken** [comment]
I'm not sure. Might be worth looking in git history, using git blame for that line etc.

It's possible this was a workaround for an old node bug. That's my only guess. Yes, since it's wrong, and we have no bug reports, very likely it is no longer being hit. So if git history doens't turn up anything surprising, it does seem removing that if is the right thing.

**Comment by ralphtheninja** [comment]
> It's possible this was a workaround for an old node bug. That's my only guess. Yes, since it's wrong, and we have no bug reports, very likely it is no longer being hit. So if git history doens't turn up anything surprising, it does seem removing that if is the right thing.

I'll do some code archeology tomorrow and see if I can dig something up.

**Comment by ralphtheninja** [comment]
@kripken Here are my findings:

1. It seems the first `if (!ret ..)` check comes from your commit [here](https://github.com/kripken/emscripten/commit/556decb19a4bcb32daad1569402fcc385d49b1d4#diff-b0b85d67c2201828828422795fb44581R31), since you're actually checking the result from the previous row which uses `.toString()` so that makes sense if you want to check for an empty string (which obviously is falsey)
2. @siggybar later added [this commit](https://github.com/kripken/emscripten/commit/f829735cc3e20e5d2165a020e87c4128d2ed9792#diff-8f35bc569987bab9a3691d986d90e75fR34) where the first usage of `path` comes into play. Something to note here is that `path` has been undefined from day 1 so this code can never have worked. Also note that the exact same code shows up in `src/compiler.js`. We're still doing `.toString()` here though, so code wise it still makes sense to have the `if (!ret ..)` check
3. After this you [move the `.toString()` call](https://github.com/kripken/emscripten/commit/f8c930551e1684cdc8c186e0a58e9e00cb602b8a#diff-8f35bc569987bab9a3691d986d90e75fR35) to the end of this function, so from this commit an onwards the if-statement is dead code, since `ret` will always be a buffer which is never falsey
4. On a side note, if you check `src/compiler.js` and `tools/js-optimizer.js`, they were both patched to remove the exact [same code](https://github.com/kripken/emscripten/commit/0bd9bff496b894af1e211a830df5cce4c80dcfd5#diff-b0b85d67c2201828828422795fb44581L38), which in itself is a good indication that we should clean up this as well from `src/shell.js`.

I propose we change it to something like:

```js
Module['read'] = function read(filename, binary) {
  if (!nodeFS) nodeFS = require('fs');            
  if (!nodePath) nodePath = require('path');      
                                                  
  filename = nodePath['normalize'](filename);     
  var ret = nodeFS['readFileSync'](filename);     
  return (binary ? ret : ret.toString());         
};                                                
```

**Comment by kripken** [comment]
Thanks for investigating! Yes, all that sounds right, and the solution looks good.

**Pull request closed without merging**
