### PR TITLE
benchmark_functions

### PR DESCRIPTION
**Pull request by juj**
Add synthetic benchmark for different types of function falls.

### CODE REVIEW

**Comment by kripken** [comment]
lgtm. commit comment has an amusing typo though, "falls" ;)

**Comment by juj** [comment]
Thanks, reauthored the commit message and merged.

**Comment by juj** [comment]
For reference, timings against SpiderMonkey Wasm support from today's mozilla-central reads

```
test_foreign_functions (test_benchmark.benchmark) ... 
        clang: mean: 1490.832 (+-27.257) secs  median: 1478.899  range: 1452.684-1514.700  (noise: 1.828%)  (3 runs)
          gcc: mean: 1438.508 (+-2.907) secs  median: 1437.112  range: 1434.498-1441.300  (noise: 0.202%)  (3 runs)   Relative: 0.96 X slower
     sm-asmjs: mean: 12955.126 (+-31.634) secs  median: 12937.776  range: 12913.323-12989.827  (noise: 0.244%)  (3 runs)   Relative: 8.69 X slower
      sm-simd: mean: 12794.448 (+-69.396) secs  median: 12749.740  range: 12714.709-12883.864  (noise: 0.542%)  (3 runs)   Relative: 8.58 X slower
      sm-wasm: mean: 12854.449 (+-24.356) secs  median: 12839.984  range: 12823.793-12883.378  (noise: 0.189%)  (3 runs)   Relative: 8.62 X slower
ok
test_native_function_pointers (test_benchmark.benchmark) ... 
        clang: mean: 1286.792 (+-49.099) secs  median: 1252.085  range: 1250.578-1356.207  (noise: 3.816%)  (3 runs)
          gcc: mean: 1286.464 (+-45.120) secs  median: 1254.564  range: 1253.595-1350.263  (noise: 3.507%)  (3 runs)   Relative: 1.00 X slower
     sm-asmjs: mean: 2071.410 (+-57.291) secs  median: 2030.931  range: 2028.156-2152.368  (noise: 2.766%)  (3 runs)   Relative: 1.61 X slower
      sm-simd: mean: 2143.560 (+-21.555) secs  median: 2134.689  range: 2113.221-2161.301  (noise: 1.006%)  (3 runs)   Relative: 1.67 X slower
      sm-wasm: mean: 3465.875 (+-299.668) secs  median: 3254.052  range: 3244.354-3889.521  (noise: 8.646%)  (3 runs)   Relative: 2.69 X slower
ok
test_native_functions (test_benchmark.benchmark) ... 
        clang: mean: 1479.958 (+-2.973) secs  median: 1478.036  range: 1476.562-1483.803  (noise: 0.201%)  (3 runs)
          gcc: mean: 1496.853 (+-33.888) secs  median: 1484.217  range: 1448.953-1522.125  (noise: 2.264%)  (3 runs)   Relative: 1.01 X slower
     sm-asmjs: mean: 1876.486 (+-36.412) secs  median: 1863.584  range: 1824.991-1902.289  (noise: 1.940%)  (3 runs)   Relative: 1.27 X slower
      sm-simd: mean: 1901.081 (+-28.267) secs  median: 1885.031  range: 1864.399-1933.181  (noise: 1.487%)  (3 runs)   Relative: 1.28 X slower
      sm-wasm: mean: 2185.264 (+-19.266) secs  median: 2174.046  range: 2160.657-2207.699  (noise: 0.882%)  (3 runs)   Relative: 1.48 X slower
ok
```

**Comment by kripken** [comment]
Interesting data. ffis being slow is a known issue with ongoing work I believe. However wasm being slower on function pointer calls and regular function calls seems surprising to me? cc @lukewagner @sunfishcode

**Pull request merged**
