### PR TITLE
responsive_main_thread_futex_wait_slices

### PR DESCRIPTION
**Pull request by juj**
Revise the order of emscripten_main_thread_process_queued_calls() operations in timedwait(), wait() and usleep() loops for best responsiveness. In main thread, only ever sleep 1 msec slices in futex waits to stay responsive for proxied operations for pthreads. This improves the test case in #3922 from 3232 msecs to 45 msecs.

### CODE REVIEW

**Comment by kripken** [comment]
lgtm, nice.

Just a thought - 1ms sleeping is going to be bad for battery life, but I suppose that won't be an issue in practice for applications doing heavy computation anyhow. However, in the long term, there might be projects hit by this. Perhaps we could document this somewhere?

**Comment by juj** [comment]
Thought about that too, which is why I opted to have the 1ms waits only for the main browser thread, which is the thread that can't do blocking loops anyways, and is expected to yield back to the browser runtime periodically. Before SAB, we didn't have sleep, and I imagine this won't be any worse, at least we have 1ms sleeps.

I'll add a note about that in the pthread docs page and push.

**Comment by juj** [comment]
Ok, documented and pushed.

**Comment by gouletr** [comment]
Interesting. I'll try this out to see if I can re-enable our file i/o thread. Thanks!

**Pull request merged**
