### PR TITLE
emscripten_audio API for Web Audio

### PR DESCRIPTION
**Pull request by kripken**
This is not done yet (needs testing), but putting it up for feedback.

This provides a C API to Web Audio. It is based on Unity's approach, which in practice seems to be the best in terms of results of all the options across multiple browsers. They are ok with us using their code, so I reworked it into this pull request.

This provides access to some of the core parts of Web Audio, specifically creating buffers and channels, and playing them, and adjusting some parameters. It's very bare-bones and minimalistic (less than 200 lines of code), but by being closer to the actual browser API, perhaps it can help projects like JSMESS get better audio.

### CODE REVIEW

**Comment by kripken** [comment]
Oops, hit wrong button. before, sorry. @juj, would be great to hear your thoughts on this.

**Comment by kripken** [comment]
Added basic test.

**Comment by juj** [comment]
This looks great @kripken !

Some thoughts came to mind when reading this:

1) I think the function `emscripten_audio_load()` should accept callback pointers for success and failure cases. The ability to poll completion with `emscripten_audio_get_load_state()` is useful, but with the callbacks one could use an event-based approach to detecting success and failure.

2) I wonder if the API should be multi-context aware? I.e. having an object to refer to a handle of a web audio context that is returned by init, and then the functions would either take a context object handle representing which context to call to, or having an implicit `emscripten_audio_make_current()` which sets the currently active audio context for the thread. There is currently no `emscripten_audio_deinit()` function to clean up everything.

3) I think we need to ask what this API does that OpenAL and SDL cannot do? Currently it looks like the benefit is that we have the new function `emscripten_audio_load()` which is able to load and decode compressed audio data, which OpenAL doesn't support (SDL mixer API does).

4) Would it make sense to have a version of `emscripten_audio_load_vfs(const char *filename)` that loads the compressed file from the Emscripten VFS? This would help avoid having to route the file from the VFS to Emscripten HEAP in order to decode. This kind of optimization can of course be added later.

5) Perhaps it would be better to have a separate typedef for audio channels and loaded audio buffers instead of reusing `EMSCRIPTEN_AUDIO_INSTANCE` to mean either?

6) For JSMESS and other emulators, I think this doesn't unfortunately solve the issue that they have. These emulators don't model their audio by one-off playable audio clips, but it is more like streaming audio data from small-sized blocks (that the emulator is generating on the fly). What they need to have is an audio channel where one can push back audio buffers to be played back in a queue, i.e. something like

    channel = emscripten_audio_create_channel(...);
    emscripten_audio_queue(channel, buffer1);
    emscripten_audio_queue(channel, buffer2);
    emscripten_audio_queue(channel, buffer3);
    emscripten_audio_queue(channel, ...);

with the expectation that if the channel is starved/quiet, buffer1 will immediately start to play on the first queue command, and the subsequent buffers will seamlessly join to produce a smooth audio stream. (then a second function to ask how long the queue currently is) This is the problem/use case that Web Audio is not currently able to handle, i.e. it cannot give such a guarantee that seamless joins would be glitch-free. This is being worked on the spec level, and as I remember, AudioWorkers should be able to enable this kind of abstraction (https://github.com/WebAudio/web-audio-api/issues/113).

7) An issue with `.decodeAudioData` in `emscripten_audio_load` is that it will decode everything up front, so it's not feasible to play e.g. music clips by fully decoding using this function. Two solutions to this are either using 6) above (and requiring that caller manages streamed decoding in small chunks manually), or perhaps adding a `emscripten_audio_play(const char *ptrToEncodedFileInMemory, float startPos, float duration, bool loop)` (and also possibly `emscripten_audio_play_vfs(const char *filename, float startPos, float duration, bool loop)`).

So there's three cases that game engines typically need:

A. those one-off short shotgun.wav sound clips that are ok to be fully decoded, stored and played back in one go.
B. efficient playback of long clips that will need streamed decoding and playback, because music.mp3 is too large to decode in one go.
C. streamed playback of content that is generated on the fly, e.g. rendered by the game (JSMESS, ScummVM, DosBox etc. emulators) or coming from some other live source in a stream.

The API in this PR is good already for A, and I think we could extend it to be good for B as well. We could also create an API to it to enable expressing C, but currently with Web Audio, there is no guarantee yet that it will sound right.

If one uses OpenAL to do A-C, he will have to find some solution for decoding (Ogg Vorbis seems like the most popular way for Emscripteners that I've seen) and for B have to write a custom streamed decoding loop, but the API is able to enable A-C each. In OpenAL, C is implemented in a push model, i.e. in the way that the `emscripten_audio_queue()` example above works.

If one uses SDL, there is also option to do A-C. SDL mixer has two backends, playing with the audio element you(?) wrote, and playing with web audio that I added later. The mixer playback with audio element supports A and B, whereas the mixer playback with web audio only supports A. Then there's the low-level `SDL_OpenAudio()` thing to support C, which is what JSMESS is (was?) using, but they may have added some custom API for that since.

The fundamental problem with SDL support for case C compared to OpenAL support for case C is that SDL support is a pull model instead of the push model in OpenAL. Therefore it means that the basic operation in SDL is to do a setTimeout loop to pull in audio data, but since timers have jitter and lag, this is worse than push model in JS context. That is why I authored the pull request at https://github.com/kripken/emscripten/pull/2651 in order to do the pulling of audio data by piggybacking to requestAnimationFrame, so that the use of extra timers could be avoided. I think that worked in practice to mitigate the issue.

If we added B and C, then this API would be better (in terms of features A-C above) than OpenAL because this API would be able to handle compressed audio data, which OpenAL doesn't do. And it would be better than the SDL API because of not being quite as crude, and for not having a pull model for C, but a proper push model.

Adding features B and C to this API would be nice and feasible, but even if we did that, the fundamental problem with Web Audio is still there, and we'll have to wait for the spec to evolve. So I'm not sure what the best course here is right now.

**Comment by floooh** [comment]
Please allow me to give my 2c :) Like @juj says, the API looks good for firing audio effects, but what's typically also needed is a set of functions for streaming data in chunks of either decoded, or generated audio data (at least for playing large pieces of background music).

I'm aware of 2 methods to provide new data: buffer queueing like in OpenAL, or writing to a single circular buffer like in DirectSound, the app code also needs to know when to provide new data, either by polling, or through a callback.

The OpenAL model typically uses a small number of pre-allocated buffers (the size of the buffer indicates the minimum latency of the playback system), buffers are enqueued for playback, and recycled after they have been played. The problem in OpenAL is that to prevent clicks and pops you want to enqueue enough data beforehand to take care of unexpected pauses or delays in code execution, but once data is enqueued, it can't be discarded once a new sound effect becomes active. So if I want to be click-and-pop-safe and enqueue 500ms of sound data beforehand, there's no way to discard and rewrite these 500ms, but new data can only be enqueued with that 500ms delay.

That's where the DirectSound model is better (http://msdn.microsoft.com/en-us/library/ee419014(v=vs.85).aspx). It allows to create one big circular buffer which can be as long as the application wants (e.g. several seconds), but exposes a current 'write cursor' position a few milliseconds ahead of the 'play cursor'. This distance between play and write cursor is the playback latency, and is completely decoupled from the buffer size (big buffer is better to prevent pops and clicks). 

I'm not sure how this would map to the WebAudio API, but I think streaming functionality is needed one way or other.

It would also be good to have a way to query available sample format data (e.g. 16 or 8 bit signed or unsigned), and it would be nice if there would be a way to disable any conversion / resampling inside the API (again, not sure if WebAudio allows such detailed control).

If something needs to be tested I'm happy to help, I'm working on a small 8-bit-tunes sound module here which is using streaming buffers and generated audio data via the OpenAL API, should be easy to add an emscripten code path once a streaming API is available: http://floooh.github.io/oryol/SynthTest.html

**Comment by juj** [comment]
Thanks @floooh for the comments. In the above `emscripten_audio_queue` example, buffer1, buffer2 and so on are all free to be of arbitrary length, so it doesn't mean that the user needs to use buffers that are all the same size each. I think this makes the approach equivalent to the circular buffer approach (except for memory storage).

Unfortunately Web Audio does not support anything except 32-bit float audio data. I've raised an issue about it here: https://github.com/WebAudio/web-audio-api/issues/283

**Comment by floooh** [comment]
@juj, do you know the root cause of the 'typical' clicking problems that emulators have? Is it a builtin-problem of WebAudio, or is it caused by the emscripten OpenAL or SDL wrappers, or the application code which can't provide new data at the right time? Would it help to move the application-side buffer update and queueing code into a dedicated web worker thread? That's what native game engine usually do to decouple the buffer update code from the game loop. Can WebAudio be controlled from a WebWorker yet?

**Comment by kripken** [comment]
Thanks for all the comments!

1. Makes sense, will add callbacks to `load`.
2. I would prefer to not add multicontext support now. My goal here is just to make the minimal thing that we know works well in browsers, and is easy to use, and is sufficient for serious applications. This approach is basically what Unity does, with good results, so I think that is good evidence is covers a large set of uses. See later down for more on why simplicity is better.
3. The goal is not to do more than other APIs, but to do less - to do just what is known to work well. People can shoot themselves in the foot with the other ones, with this it's just a tiny wrapper around Web Audio, so hopefully not. Btw, I looked into implementing SDL on top of this - it wasn't a good match actually, because of extra stuff SDL wants. But if apps don't need that extra stuff, best to use this new API, I think. Most game engines should be ok to use this API.
4. Make sense to add a filesystem call, will add.
5. I think the API is simpler this way, personally, with one "object" handle.
6. Agreed about this not solving JSMESS's problem. I realized that friday when talking to them on IRC. I think therefore that as a first stage, what is done here is good for the Unity-style use case, which is probably the most common - a palette of sounds. For JSMESS, I think the best result will be if we run it in a worker - that way, each frame sends off a buffer of audio, and even if the next frame is slow, the buffer can still be played on the main thread, where web audio is done (i.e. the game on the worker fires off audio chunks, and a separate thread actually pushes them to web audio at the right time). This is another reason to keep the API super-simple - it's easier to remote these things that way. So the goal here is to have a palette API, as already done, then add a "streaming" API - not show how, still thinking about both of yours' comments, we should all discuss this some more - then add remoting for both. I think that's our best shot at a simple story for good audio.
7. Regarding music, I'm not sure why the size is an issue? (Surely Unity has music, and it works for them?)

**Comment by juj** [comment]
@floooh: The issues are fundamental in Web Audio (although in PR https://github.com/kripken/emscripten/pull/3124 it was just shown that the latest refactoring I had done had introduced an issue to the audio scheduling that DOSBox suffered with. That PR was tested on JSMESS, where the problem did not occur). The spec does not guarantee that buffers laid back to back are seamlessly joined.

@kripken: For 7, Unity will have the same issues with music if they don't stream. Only a 5 minute music clip at 44kHz will consume `5(minutes)*60(seconds)*44100(samples/second)*4(bytes/sample)*2(stereo) = 100 MB` worth of RAM if stored fully decoded, so it's not feasible to decodeAudioData even a 5 minute audio clip to memory. Also e.g. on FFOS when I accidentally did that, decoding ~3 minutes of music in one go with decodeAudioData takes on the order of 10 seconds of computation, which is a long delay. On very fast desktop computers it probably takes only a few seconds at most, but still it's not realtime (and consumes a lot of power).

**Comment by floooh** [comment]
I just stumbled over this PR again since I'm currently integrating soloud into my engine (http://sol.gfxile.net/soloud/). This is easy to get working on emscripten using the SDL Audio wrapper (see the soloud backend for this, which is extremely minimal, basically just feeding new audio data when SDL Audio needs it: https://github.com/jarikomppa/soloud/blob/master/src/backend/sdl_static/soloud_sdl_static.cpp)

IMHO such a scenario where a higher level audio engine does all the mixing work, and just requires playback buffers which will be filled would be the perfect use case for a really minimal emscripten_audio API (even more minimal what's in this PR). That way I would neither need the OpenAL or SDL intermediate layers, just a new new minimal soloud backend which would build directly on top of a new emscripten_audio.

**Comment by kripken** [comment]
Not sure I'll have time for this soon. Would be nice if someone wants to pick it up and drive it, in particular after the feedback of @floooh's last comment.

**Comment by juj** [comment]
Discussing last month in SF about the upcoming AudioWorklets and the limitations of Web Audio API with respect to looping and pitch adjusting compressed audio, the need for an Emscripten-specific audio solution has begun to make more sense - there are many features that we would not want to require developers to reimplement, including multithreading support for audio. This is on my radar for later this year.

**Comment by kripken** [comment]
Closing this PR, I don't think I'll have time for it.

@floooh, did you have time to work on your idea for a new minimal audio API?

**Comment by kripken** [comment]
In the long term we may get wasm => JS API support that can make writing such libraries easier, yeah.

For now we can point people to sokol_audio.h I guess :)

**Pull request closed without merging**
