### PR TITLE
Unwind the stack around every invoke

### LINKED ISSUE #6666: STACKTOP is not unwound by longjmp()
It appears that STACKTOP is not restored when setjmp() returns with a nonzero result, i.e.,. when unwinding from a longjmp().  Addresses of C variables in linear memory stack frames are maintained in Javascript variables derived from STACKTOP and are correctly restored, so that the values of local variables prior to the setjmp() are preserved as expected.  Subsequent function calls, however, allocate their linear memory frame at the extent of the stack where the longjmp() occurred.   This results in unexpected stack usage, particularly when the longjmp() is thrown due to imminent exhaustion of linear stack space.

The following test case illustrates the issue:

```
#include <stdlib.h>
#include <setjmp.h>
#include <stdio.h>

jmp_buf jb;

void bar()
{
    int dummy;
    printf("before longjmp: %p\n", &dummy);
    longjmp(jb, 1);
}

void foo()
{
    void* temp = alloca(1024);
    bar();
}

void baz()
{
    int dummy;
    printf("after longjmp: %p\n", &dummy);
}

volatile int* savePtr = NULL;

int main()
{
    volatile int dummy;
    savePtr = &dummy;
    dummy = 12345;

    printf("before setjmp: %p\n", &dummy);

    if (!setjmp(jb)) {
        printf("dummy = %d\n", dummy);	
        foo();
        return 0;
    } else {
        baz();
        printf("dummy = %d\n", dummy);	
        return 1;
    }
}

```
When compiled and run, the following output is produced:

before setjmp: 0x1394
dummy = 12345
before longjmp: 0x17b4
after longjmp: 0x17c4
dummy = 12345

### PR DESCRIPTION
**Pull request by kripken**
That ensures the stack is unwound from any functions we entered during the invoke, which may not unwind themselves due to an exception or longjmp being called.

This adds some overhead - a call in each invoke() - but only for setjmp/C++ exceptions using code, so it may be worth it for correctness.

Fixes #6666

### CODE REVIEW

**Comment by wmaddox3rd** [comment]
Is it possible to avoid the function call to saveStack() and reference STACKTOP directly?  The call to stackRestore() occurs only in the exceptional case, but saveStack() is called for every invoke.  I was able to get several of my test cases to run with the following hacky patch.  It doesn't deal with exceptions in general, and may fail if there are multiple setjmp() instances within a function that need to capture a different value of STACKTOP, but it may suggest an alternate approach.

```
diff -u6 a/CallHandlers.h b/CallHandlers.h
--- a/CallHandlers.h	2018-06-11 19:08:05.551485571 -0700
+++ b/CallHandlers.h	2018-06-11 19:08:15.430905080 -0700
@@ -220,13 +220,13 @@
 DEF_CALL_HANDLER(emscripten_cleanup_setjmp, {
   return "_free(_setjmpTable|0)";
 })
 DEF_CALL_HANDLER(emscripten_setjmp, {
   // env, label, table
   Declares.insert("saveSetjmp");
-  return "_setjmpTable = _saveSetjmp(" + getValueAsStr(CI->getOperand(0)) + ',' + getValueAsStr(CI->getOperand(1)) + ",_setjmpTable|0,_setjmpTableSize|0)|0;_setjmpTableSize = " + getTempRet0();
+  return getAdHocAssign("saveStackTop", Type::getInt32Ty(CI->getContext())) + "STACKTOP|0; _setjmpTable = _saveSetjmp(" + getValueAsStr(CI->getOperand(0)) + ',' + getValueAsStr(CI->getOperand(1)) + ",_setjmpTable|0,_setjmpTableSize|0)|0;_setjmpTableSize = " + getTempRet0();  
 })
 DEF_CALL_HANDLER(emscripten_longjmp, {
   Declares.insert("longjmp");
   return CH___default__(CI, "_longjmp");
 })
 DEF_CALL_HANDLER(emscripten_check_longjmp, {
@@ -235,12 +235,13 @@
   std::string Assign = getAssign(CI);
   Declares.insert("testSetjmp");
   Declares.insert("longjmp");
   return "if (((" + Threw + "|0) != 0) & ((threwValue|0) != 0)) { " +
            Assign + "_testSetjmp(HEAP32[" + Threw + ">>2]|0, _setjmpTable|0, _setjmpTableSize|0)|0; " +
            "if ((" + Target + "|0) == 0) { _longjmp(" + Threw + "|0, threwValue|0); } " + // rethrow
+           "STACKTOP = saveStackTop|0; " +
            setTempRet0("threwValue") + "; " +
          "} else { " + Assign + "-1; }";
 })
 DEF_CALL_HANDLER(emscripten_get_longjmp_result, {
   std::string Threw = getValueAsStr(CI->getOperand(0));
   return getAssign(CI) + getTempRet0();
```

**Comment by kripken** [comment]
Yeah, doing this in the backend is another option. It will be faster. However, it's somewhat more complicated, only works for longjmp but not C++ exceptions, and doesn't work for the LLVM wasm backend (we'd need to modify that backend too). So overall I think doing it in invoke() is simpler and good enough, given that speed usually matters less in code using setjmp and exceptions, which are slow anyhow. But, I didn't measure this, and maybe there are use cases where the perf difference is noticeable?

**Comment by kripken** [comment]
Note that the main reason I didn't measure this is the lack of a good benchmark for either setjmp or C++ exceptions, might be worth finding one.

**Comment by kripken** [comment]
Thanks for confirming @wmaddox3rd !

Let's leave this open a little longer to see if people have concerns about the perf aspect.

**Comment by kripken** [comment]
Testing on https://github.com/jpakkane/zipexcept which was suggested on twitter, I see a slight startup slowdown - the extra JS code to parse, it seems - but no significant impact to perf (55K invoke calls over 1 second of work).

**Comment by kripken** [comment]
Enabling exceptions in Bullet, a lot of calls end up going through invokes (seems LLVM can't prove exceptions don't happen), which slows things down by an extra 17%, which basically doubles the penalty of exceptions on Bullet.

Testing this on Lua, which uses setjmp, there is no noticeable impact.

Overall, it seems like for setjmp the risk is low as it's just in the setjmp-calling function that we need invokes. For C++ exceptions, the risk is everywhere the compiler can't get rid of an invoke.

**Comment by kripken** [comment]
Been over a week with no concerns, even after I linked to this on Twitter ;) so we can probably merge this.

Before that I added a mention in the changelog, so if people do see issues, at least bisecting them to a version should help find this PR (without needing to bisect on specific commits). If we get reports of issues, we can investigate further optimization here.

**Pull request merged**
