### PR TITLE
Module['print'] fix for Edge/IE11 when devtools are not open.

### PR DESCRIPTION
**Pull request by MarcelKlammer**
When the dev tools in Edge/IE11 are not open having console.log without a surrounding function(){} will break asm.js output. Same goes for print and printErr. This change to shell.js fixes this issue and make asm.js output work again in IE11 and Edge.

### CODE REVIEW

**Comment by kripken** [comment]
Thanks!

I'd like to understand this better. For IE11 I could imagine it's just an old bug, but that this happens on Edge suggests it's something serious. Is the issue that
```
var x = console.log;
x('hi');
```
fails while
```
var x = function(x) { console.log(x) };
x('hi');
```
works? If so, is it because the `this` property needs to be set? Does `console.log.bind(this)` work? (it's shorter)

Also, what is the connection to the devtools being open - I guess `console` is defined differently in those two cases, on these browsers?

Finally, how is this related to asm.js? Or do you mean not literally the asm.js code but the regular JS code breaks due to the `this` issue?

**Comment by MarcelKlammer** [comment]
Here is a bare bone example (with results from Edge and IE11 as comments below the script):
[https://gist.github.com/MarcelKlammer/bcca34a4cc185806b45f8f9e5876b87d](https://gist.github.com/MarcelKlammer/bcca34a4cc185806b45f8f9e5876b87d)

Testable here:
[https://tastenkunst.s3.amazonaws.com/demos/brfv4/win/ie11_console.html](https://tastenkunst.s3.amazonaws.com/demos/brfv4/win/ie11_console.html)

It seems there are different behaviors with open and closed devtools in Edge and IE11. The thrown TypeError is being "catched" in the function that calls x("hi") and prevents further execution of that function. So wrapping an anonymous function around that call will lead to stopping that anonymous function, but prevents the module scoped script to stop.

**Comment by brion** [comment]
Seems to work to use `console.log.bind(console)`, which'll be less verbose than wrapper functions. Tweaked version of test case at https://brionv.com/misc/ie11_console.html using that works for me in IE 11 and Edge both with and without dev tools open.

Weird that the console object seems to vary depending on whether you've got dev tools open, though!

**Comment by MarcelKlammer** [comment]
Yes, I can confirm that bind(console) prevents the TypeError. Will you do the changes yourself or do you want me to update the pull request?

**Comment by MarcelKlammer** [comment]
Btw. I can also confirm that the fix is working in our BRFv4 asm.js version in Edge and IE11:
https://tastenkunst.s3.amazonaws.com/demos/brfv4/win/minimalImageO3.html

**Comment by MarcelKlammer** [comment]
So what can I do about this failed test? The details doesn't make sense to me.

**Comment by kripken** [comment]
Thanks @MarcelKlammer and @brion!

Looks good, before we merge please just
 * Add yourself to AUTHORS
 * Add a comment in a line above those, something like "for IE11 and Edge it is necessary to .bind() the call to console.log" (so in the future we know why that's there).

That browser error looks like a random failure that can be ignored - we just added the browsers tests on CI here, still stabilizing things there.

We should probably file a bug on Edge for this, as it seems like a bug (we'll need the workaround for IE11 anyhow, though).

**Comment by kripken** [comment]
Thanks, looks good. Just waiting on tests to finish before merging.

**Comment by kripken** [comment]
The pthreads browser tests that fail here also seem to fail on other PRs, so looks unrelated. Merging, thanks!

**Pull request merged**
